### ISSUE TITLE
links in examples

### ISSUE THREAD

**Issue by pytrisss** [Kitt-AI/snowboy#100]
Hi guys,

I'm playing with snowboy and alexa and I still can't get it to work. So I wanted to debug using your python examples, but they seem a little broken to me.

I go to the folder with the examples and in python console I do this:
`>>> import snowboydecoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snowboydecoder.py", line 5, in <module>
    import snowboydetect
ImportError: No module named snowboydetect`

The file snowboydetect.py is a link:
` snowboydetect.py -> ../../swig/Python/snowboydetect.py`

same goes for
`_snowboydetect.so -> ../../swig/Python/_snowboydetect.so`

Both files don't seem to exist in that location and I can't find them anywhere else.

PS: I'm new to this so sorry if it's something stupid on my part :)

**Comment by chenguoguo** [comment]
Hi, if you want to use the example in the repository, you have to go to `swig/Python/` and compile the library for Python through swig. We have a Makefile there.

Alternatively, you can download our pre-compiled Python demo from here: https://snowboy.kitt.ai/docs (search for download)

**Comment by pytrisss** [comment]
I thought I missed something. Thank you!
