### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit__snowboydetect)

### ISSUE THREAD

**Issue by zsdonghao** [Kitt-AI/snowboy#101]
I am using Macbook, snowboy works well with Python2.
But I get error with Python3 on Quick Start for Python Demo.
```
ImportError: dynamic module does not define init function (PyInit__snowboydetect)
```
Anyone have idea about that?

**Comment by chenguoguo** [comment]
Likely you used the python-config from python2, see the post here:

https://groups.google.com/a/kitt.ai/forum/#!topic/snowboy-discussion/3G0fobzUw-0

**Comment by zsdonghao** [comment]
@chenguoguo Thank you so much let me have a try ~~

**Comment by chenguoguo** [comment]
I guess the issue has been resolved? Closing this. Feel free to re-open it if it's not resolved.

**Comment by DarioBernardo** [comment]
Hey, I know this is a closed issue, but I am having the same problem. Can you explain how do I use the python-config for python3 ? I created a symbolic link, but not sure it is the right way, what exactly do I have to do?

**Comment by chenguoguo** [comment]
@DarioBernardo you might have to use something like python3-config

**Comment by DarioBernardo** [comment]
emmm thanks for the reply, but what exactly that means? I never used python3-config before, what do I have to do exactly? Sorry for the noob question.

**Comment by chenguoguo** [comment]
How did you set it up? Did you go to `swig/Python3/` and type `make`? When you type `python3-config` in the command line, does that give you any errors?

**Comment by fl118543** [comment]
I know this is an old thread but I provide you my solution in case this could be useful to someone with the same issue.
Recently I tried to install snbowboy on my Ubuntu laptop with Python3 and I got the same importerror. My python configuration was ok and I had installed all the packages/modules required to run snowboy.
Finally I decided to recompile snowboy for Python3. The error disappeared and now snowboy is working correctly.
For what it's worth I had the same issue when I installed snowboy on my RPi on Raspbian stretch and I fixed it the same manner so I assume this is not a hardware or system related issue.

**Comment by chenguoguo** [comment]
By recompile do you mean `make` under `swig/Python3`?

**Comment by fl118543** [comment]
Yes, this is what I did. I cloned the git repository and I did a make under swig/Python3. I thought this was ok to do that, let me know if I did something wrong.
By the way there was an issue in the Makefile. The first line is "SWIG := swig" and when I ran a make it complained about swig not found. I did some checks and I noticed that wen I installed swig3.0, the binary name is swig3.0 so I changed the line by "SWIG := swig3.0" and this time make finished correctly.

**Comment by fl118543** [comment]
Another way to correct the swig binary issue is to create a symbolic link /usr/bin/swig which points to /usr/bin/swig3.0. I don't know which one is the best.

**Comment by chenguoguo** [comment]
OK thanks a lot. Yes people are supposed to `make` under `swig/Python3` because we don't provide pre-compiled libraries for Python3.

**Comment by karthikbalu** [comment]
@zsdonghao It was actually due to the anaconda3 path, its mentioned in the makefile to be changed

use PYLIBS := -L/anaconda3/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation in your makefile

**Comment by hack-r** [comment]
A very useful thread. I think I'm having the python 2 vs 3 issue because it works for me on 2 but I get this error on 3. May I ask if I should be concerned that I don't have a SWIG folder anywhere (and it seems their project site is down due to a SourceForce outage).

**Comment by hack-r** [comment]
I had the python 2 vs 3 issue. It works on 2, but I get this error on 3. I cloned the SWIG repo. Did `sh autogen.sh` then `./configure` so that I could run `make`, but it requires PCRE. So, I downloaded and built that within the SWIG folder for convenience. ./configure still doesn't find PCRE.

**Comment by DarioBernardo** [comment]
Yes, you need to fix the SWIG issue, then it will work. Probably you will
have to modify the snowboy swig/Python Makefile too.
I had to do the same, I downloaded the swig source code and compiled it
locally to have it working.
I hope it helps.

**Comment by hack-r** [comment]
@DarioBernardo  Thanks. Yes some of my confusion was from using the version of SnowBoy compressed into an archive specifically for Raspberry Pi. That one doesn't have anything related to SWIG in it. But eventually I cloned the main repo which of course has SWIG.

**Comment by chenguoguo** [comment]
@Flowdeeps just a double check, you did `make` under `swig/Python3` right?

You might want to try it under a Python3 virtual environment.

**Comment by Flowdeeps** [comment]
There is no swig folder. It is the precompiled RPi zip from the how-to.

The folder contains the following:

```
demo2.py
demo.py
light.py
__pycache__
README.md
requirements.txt
resources
snowboydecoder.py
snowboydecoder.pyc
snowboydetect.py
_snowboydetect.so
version
```

**Comment by BaileyVu** [comment]
Hi guys, sorry if this is closed but after reading all of your comments, I got the same issue when trying to run the demo.py on anaconda/spyder3
`
ImportError: dynamic module does not define init function (PyInit__snowboydetect)
`
Then when tried the solution to type `make` under `swig/Python3` but when I look into my `swig` folder. There is no `Python3` folder only `python` with much of .i files. Then I do try to type `make` under `swig/python` then it returned `make: *** No targets specified and no makefile found.  Stop.`
So I tried manually create a `Makefile` and `snowboy-detect-swig.i` (as it required when I type `make` command) then it returned:
 `Error: Unable to find 'include/snowboy-detect.h'
make: *** [snowboy-detect-swig.cc] Error 1`
I am really sorry for this noob question but I haven't resolve this problem and it is bugging alot. Please help. Thank you!

**Comment by henryliuser** [comment]
Hi, I'm still having trouble with this issue. I'm using python3 on mac os
I have tried 2 methods and both give the same error.
    1. I have tried speechrecognition library's snowboy integration with listen() method.
    2. I downloaded the precompiled mac os library, and tried to run the demo files.
 
Both of these give:
`ImportError: dynamic module does not define module export function (PyInit__snowboydetect)`

Earlier in this thread you advised people to do `make` in `swig/Python3`, sorry for the stupid question but where can I find this `swig/Python3` directory?

**Comment by ilyakava** [comment]
I got here from [picovoice](https://github.com/Picovoice/wake-word-benchmark), so running python 3.6. Up until this point I had followed the following directions:

```
cd snowboy/
sudo apt-get install python-pyaudio python3-pyaudio sox
pip install pyaudio
wget http://downloads.sourceforge.net/swig/swig-3.0.10.tar.gz
sudo apt-get install libpcre3 libpcre3-dev
tar -zxvf swig-3.0.10.tar.gz 
cd swig-3.0.10/
./configure --prefix=/usr                          --without-clisp                            --without-maximum-compile-warnings
make
make install
sudo make install
sudo install -v -m755 -d /usr/share/doc/swig-3.0.10
sudo cp -v -R Doc/* /usr/share/doc/swig-3.0.10
sudo apt-get install libatlas-base-dev
cd ..
```

Then I got the `ImportError: dynamic module does not define init function (PyInit__snowboydetect)` error trying to run the demo.

To fix this error:
```
cd snowboy/swig/Python3
vim Makefile
# and add before the all rule add: CXXFLAGS += -fno-lto
make
```

Then edit a python file:
```
cd snowboy/examples/Python3
vim snowboydecoder.py
```
and as in #316 comment out the line `from . import snowboydetect` and add the lines:
```
from os.path import dirname
curpath = dirname(__file__)
import imp
snowboydetect = imp.load_source('snowboydetect', curpath+'/snowboydetect.py')
```


Then I was able to do the following while in `snowboy/examples/Python3`:
```
>>> import snowboydecoder
>>> def detected_callback():
...   print("hotword detected")
... 
>>> detector = snowboydecoder.HotwordDetector("../../resources/models/snowboy.umdl", sensitivity=0.5, audio_gain=1) 
```

Since I don't have a microphone:

```
cd snowboy/examples/Python3
python demo3.py ../../resources/snowboy.wav ../../resources/models/snowboy.umdl
```
