### ISSUE TITLE
Problem with python swig compile

### ISSUE THREAD

**Issue by algeroth-jeedom** [Kitt-AI/snowboy#103]
Hi !

This the log when make on swig/python

make: python-config: commande introuvable
make: python-config: commande introuvable
g++  -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
snowboy-detect-swig.cc:157:21: fatal error: Python.h: Aucun fichier ou dossier de ce type
compilation terminated.
Makefile:47: recipe for target 'snowboy-detect-swig.o' failed
make: *** [snowboy-detect-swig.o] Error 1

thanks

**Comment by chenguoguo** [comment]
It seems like python-config is not installed on your system.

You can try `sudo apt-get install python-dev` on your system (if it's ubuntu like system) or search on google how to install python-config on your system.

**Comment by algeroth-jeedom** [comment]
hi !
thanks it's work

but on compiled fil i don't have the file snowboydecoder.py ...
I've only snowboydetect.py

DEBUG: models=alexa,jarvisse,snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
ImportError: No module named snowboydecoder

thanks

**Comment by chenguoguo** [comment]
The file is here: https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/snowboydecoder.py

**Comment by algeroth-jeedom** [comment]
Ok thanks it's the same for all arm platform ? no deed to compile anything else ?

**Comment by algeroth-jeedom** [comment]
I have this error 
File "/home/snowboy/snowboydecoder.py", line 91, in init
TypeError: init() got an unexpected keyword argument 'model_str'

**Comment by chenguoguo** [comment]
Yes the snowboydecoder.py is just a wrapper and it should work for all the platforms. The only part you have to compile (in your case) is things under `swig/Python`

Are you using Python3? If you are using Python3 you have to make sure your python-config also comes from Python3 instead of Python2.

**Comment by algeroth-jeedom** [comment]
i think it is good ? python-configparser (3.3.0r2-2) ...

**Comment by chenguoguo** [comment]
@algeroth-jeedom so when you run `python-config --includes`, it gives you things for Python3 instead of Python2, and you are using Python3 on your system? Sometimes it's possible that you have both Python2 and Python3 and they are somehow mixed together.
