### ISSUE TITLE
[Python] swig_import_helper() (snowboydetect.py line 28) Error

### ISSUE THREAD

**Issue by OceanCoding** [Kitt-AI/snowboy#104]
Hey,
I am new to GitHub and I am new to Snowboy. I am trying to get `snowboydecoder.py` to work with my project, for this, I have installed `sox`, `swig` and `pyaudio` via `homebrew` (I am on OS X 10.12.11) and `pip`.
But when `snowboydecoder.py` tries to import `snowboydetect.py`, I do get this error:

> File ".../Snowboy/snowboydecoder.py", line 5, in <module>
>     import Snowboy.snowboydetect as snowboydetect
>   File ".../Snowboy/snowboydetect.py", line 28, in <module>
>     _snowboydetect = swig_import_helper()
>   File ".../Snowboy/snowboydetect.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_snowboydetect', fp, pathname, description)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: dynamic module does not define module export function (PyInit__snowboydetect)

The `_snowboydetect.so` file is in the same directory as `snowboydecoder.py` and `snowboydetect.py`

I hope you can help me and sorry if this is a dumb question :)
Thanks!

Raph

**Comment by chenguoguo** [comment]
Hi, you have to compile it using swig, see the directory here: https://github.com/Kitt-AI/snowboy/tree/master/swig/Python

Or you can use the pre-compiled version from the documentation: http://docs.kitt.ai/snowboy/#downloads

**Comment by OceanCoding** [comment]
Alright, I knew that I missed something. Thanks for your quick help. Have a great day :)
