### ISSUE TITLE
How to break loop after callbacks ?

### ISSUE THREAD

**Issue by jello2545** [Kitt-AI/snowboy#105]
Hi there,

I'm not much of a programmer here. Using snowboy with the Python script, i'm trying to figure out what I need to do in order to break the main loop only after the hotword has run its main callbacks:

callbacks = [lambda: subprocess.call("perl /home/me/script.pl", shell=True)]

And once the script.pl (script that basically do some checks) is done, I just want it to break its main loop and exit. Can I just append a kind of sys.exit() to the callbacks ? Not sure that would work. Tried to look at snowboydecoder.py but like I said, I'm not that good at programming so not sure what to do in there.

Guess there is an arg I can add somewhere to break the loop ?

Thank you very much

**Comment by chenguoguo** [comment]
See here: https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/snowboydecoder.py#L172

After detection, you call the callback(). You can add one more line to break the while loop.
