### ISSUE TITLE
Problem with Snowboy Hot word detection for Android

### ISSUE THREAD

**Issue by mrunalpatekar** [Kitt-AI/snowboy#106]
Hi, I am trying to develop an Android app, in which i want the ap to get triggered when I say some keyword. 

I am following
```
cd swig/Android
# Make sure you set up the NDKROOT variable in Makefile before you run.
# We have only tested with NDK version r11c.
make
```
So in the MakeFile i have done the following changes:
```

NDKINSTALLEDROOT := $(PWD)/ndk_install
NDKROOT := Users/mrunalpatekar/Desktop/android-ndk-r11c
```
I downloaded NDK  r11c from the NDK website as a zip file, and stored it on the desktop. And i gave the link of the "android-ndk_install" in the makefile. 
I am getting the following error:

```
collect2: error: ld returned 1 exit status
make: *** [jniLibs/armeabi-v7a/libsnowboy-detect-android.so] Error 1
```

I am not sure if this is the right way. 
If anyone has any demo App that I could see, would be useful.

**Comment by mrunalpatekar** [comment]
Can I get any working example of Snowboy with Android. @BillWSY

**Comment by BillWSY** [comment]
I think after my PR #93 you should be able to just "make" to get the wrapper, without changing the Makefile or download the NDK (there is a script does this for you).

**Comment by chenguoguo** [comment]
@mrunalpatekar, as @BillWSY said you should be able to compile Snowboy for Android using the latest Makefile.

@BillWSY in the meanwhile, if you have some simple examples of using Snowboy on Android, and you are open to share them with others, I'd be very happy to check them in under `examples/Android`. I think people will really appreciate this kind of examples :-)

**Comment by mrunalpatekar** [comment]
Yes. Thank you

**Comment by amitkumarsharma008** [comment]
Hi All,
For Android integration, I am able to build the file "libsnowboy-detect-android.so" using the Makefile.
It generated two folders "java" and "jniLibs". I have copied these two folders to my app project.

In my java file, 
public class snowboy {

    static {
        System.loadLibrary("libsnowboy-detect-android");
    }
}

This is giving the below error -
01-30 15:33:25.612 25269-25269/hubble.hubblealexa E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.example, PID: 25269
                                                                    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.yyy/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.yyy/lib/arm64, /data/app/com.xxx.yyy/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "liblibsnowboy-detect-android.so"
                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                        at java.lang.System.loadLibrary(System.java:1076)
                                                                        at ai.kitt.snowboy.snowboy.<clinit>(snowboy.java:21)
                                                                        at com.xxx.yyy.onCreate(VoiceService.java:77)
                                                                        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3808)
                                                                        at android.app.ActivityThread.access$2100(ActivityThread.java:222)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Please help ..

Also do we need to do anything with the file Kitt-AI/snowboy/tree/master/lib/android/armv7a/libsnowboy-detect.a as mentioned in the github ?

Any example Android project and steps will be appreciated from your side

**Comment by chenguoguo** [comment]
You should probably use something like:

```
static {
    System.loadLibrary("snowboy-detect-android");
}
```

I do have an Android example in preparation. It's working but it's not ready for release yet.

**Comment by nandinicbit1981** [comment]
@chenguoguo can you please share android example

**Comment by chenguoguo** [comment]
We will do in the next few days. We also made some changes to the Android interface.

**Comment by nandinicbit1981** [comment]
@chenguoguo the documentation on snowboy site is very sparse for integrating with android app.
Can you please provide a starting point? Is it possible to share some extra info.

I am testing to see if snowboy fits our requirement or not.

**Comment by chenguoguo** [comment]
@nandinicbit1981 what is your time line? We need a few days to wrap things up and we will release the Android sample app as well. We are moving from hardfp to softfp, and we've also done other optimizations for Android on arm. If you can wait a few more days, that will make it much more easier for you.

**Comment by nandinicbit1981** [comment]
@chenguoguo I need to check whether snowboy work or not before monday so that we can move on to evaluate others. It would be great to get atleast some example code so that i can see if it works. I just need to verify the integration, so any code sample ( even if its not production ready) would be great.

**Comment by chenguoguo** [comment]
Please send an email to guoguo@kitt.ai, let's talk offline.

**Comment by xuchen** [comment]
Hi Guys,

I worked on the https://github.com/Kitt-AI/snowboy/tree/android-demo branch and pushed a demo there. Could you please check it out and give comments?

https://github.com/Kitt-AI/snowboy/blob/android-demo/examples/Android/README.md

I'll merge this branch in about a week's time. Your opinion on this is much appreciated.

**Comment by futhrevo** [comment]
@xuchen I am getting following error while executing `private SnowboyDetect detector = new SnowboyDetect(commonRes, activeModel);`
```
03-21 17:03:49.854 3530-3530/in.hedera.reku.speechtrial I/AppResCopy: snowboy directory has 2 files.
03-21 17:03:49.855 3530-3530/in.hedera.reku.speechtrial W/AppResCopy: /storage/emulated/0/snowboy/ already exists! 
03-21 17:03:49.897 3530-3530/in.hedera.reku.speechtrial I/AppResCopy: snowboy/OkGadget.pmdl is file
03-21 17:03:49.898 3530-3530/in.hedera.reku.speechtrial E/AppResCopy: overriding file /storage/emulated/0/snowboy/OkGadget.pmdl
03-21 17:03:49.905 3530-3530/in.hedera.reku.speechtrial I/AppResCopy: copy to /storage/emulated/0/snowboy/OkGadget.pmdl ok!
03-21 17:03:49.950 3530-3530/in.hedera.reku.speechtrial I/AppResCopy: snowboy/common.res is file
03-21 17:03:49.952 3530-3530/in.hedera.reku.speechtrial E/AppResCopy: overriding file /storage/emulated/0/snowboy/common.res
03-21 17:03:49.954 3530-3530/in.hedera.reku.speechtrial I/AppResCopy: copy to /storage/emulated/0/snowboy/common.res ok!
03-21 17:03:49.993 3530-3530/in.hedera.reku.speechtrial E/AudioDataSaver: /storage/emulated/0/snowboy//recording.pcm
03-21 17:03:49.998 3530-3530/in.hedera.reku.speechtrial A/libc: /usr/local/google/buildbot/out_dirs/aosp-ndk-r11-release/build/tmp/build-8979/build-libc++/ndk/sources/cxx-stl/llvm-libc++/../llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::runtime_error: ERROR (void snowboy::ExpectToken(bool, const char*, std::__ndk1::istream*)():snowboy-io.cc:166) Expected token "<ResourceFileOffsets>", got instead "../../../../../resources/common.res".
                                                                
                                                                [stack trace: ]
                                                                Backtrace for Android has not been implemented yet.
                                                                " failed
03-21 17:03:49.998 3530-3530/in.hedera.reku.speechtrial A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3530 (eku.speechtrial)
```

Please advise what is wrong

**Comment by chenguoguo** [comment]
We put `common.res` as a soft link, it's likely that you moved the app to some other directory. In that case, make sure you copy those files follow the symbolic links.

**Comment by chenguoguo** [comment]
We have added the Android demo, so closing this one.

**Comment by ankitmaisuriya** [comment]
Hi chenguoguo..I have configured the Android Demo provided by the Snowboy . Its working very fine. But please help me out how to integrate this demo with my own application and enable hot keyword detection alexa in my app.

Thanks.

**Comment by chenguoguo** [comment]
It's really an Android issue... what problems you are seeing? you basically only have to integrate the JNI library to your app, and you should be able to do it by following the demo...
