### ISSUE TITLE
libsnowboy-detect.a has error on Debian 8 AMD 64 with AVS sample project

### ISSUE THREAD

**Issue by chanffdavid** [Kitt-AI/snowboy#108]
My VM installation
Linux ddff 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

Error log due to setup https://github.com/alexa/alexa-avs-sample-app

Scanning dependencies of target wakeWordAgent
[  7%] [ 15%] [ 23%] [ 30%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/SensoryWakeWordEngine.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
Linking CXX executable wakeWordAgent
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
../ext/lib/libsnowboy-detect.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:388: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chenguoguo** [comment]
What's your platform? By default the wake word agent uses the library we compiled for Raspberry Pi which has ARM processors. You can play with our other library.

BTW there's a bug in the frontend processing part in our library, it stopped working couple of weeks back, so you'll likely see quite a performance degradation for the current version. We will update the library tomorrow.

**Comment by chanffdavid** [comment]
Thanks for your reply. We try to run the sample on Debian OS in my Parallels VM in x86 architecture

**Comment by chenguoguo** [comment]
If it's x86 architecture, you may be able to use the ubuntu library.

**Comment by 1337AD** [comment]
I have similar problems to make the wakeWordAgent on my Raspberry Pi.
I am getting the Error:

make[2]: *** No rule to make target '../ext/lib/libsnowboy-detect.a' , needed by 'wakeWordAgent'. Stop.

**Comment by 1337AD** [comment]
Sorry - have my problem resolved - the file was not in the right repository. I had to copy it into wakeWordAgent/ext/lib from my github clone.

**Comment by chenguoguo** [comment]
Closing this since the issue was resolved.
