### ISSUE TITLE
Snowboy iOS demo is...lacking.

### ISSUE THREAD

**Issue by patrickjquinn** [Kitt-AI/snowboy#121]
I know there is the aurioTouch demo showing how snowboy is implemented on iOS but given the size of that boilerplate project its almost inaccessible (Was there special compiler configs used for this? which libc library is the right one to use etc). 

Given the fact support for iOS exists can there be a clearly defined set a docs or maybe even a very small demo project which contains an example of snowboy in action at some point?

A Pod would be the ideal solution here with a bridged Obj-C interface.

**Comment by chenguoguo** [comment]
We were hoping to add demos for iOS and Android, but have been too busy with other stuff... We may have to leave this up for a while. In the meanwhile, any PRs on those demos are welcome!

**Comment by patrickjquinn** [comment]
I've been attempting to put together a example application for snowboy with the native AVAudioRecorder class in the hopes of making a PR, but i've been unable to due to libc compiler issues. If i can get that working i'll create a proper Obj-C wrapper for it.

In terms of Android, this client for one of my project, P-Brain (Built by the awesome timestableford) https://github.com/timstableford/P-BrainAndroid makes use of snowboy and includes training etc. If you wanted to take an hour to strip out all the P-Brain.ai related stuff you could bang together a solid demo for Android in no time.

**Comment by chenguoguo** [comment]
Could you be more specific about your "libc compiler issues"? I'm not an expert in iOS but if there is anything we can improve on the Snowboy side to make the process easier for you, we are happy to do that.

**Comment by grimlockrocks** [comment]
I am using Xcode 8 + Swift 3, which I need to have a Briding-Header.h file. The file imports the header:
#import "snowboy-detect.h"

However, Xcode is not able find relevant C++ standard library, such as memory and string. I got an error: "memory" file not found. 

I have Googled and tried to set things such as compiler type, header search path, etc, but could not get it working. Any help is appreciated!

**Comment by patrickjquinn** [comment]
@chenguoguo Sorry for the delay, I actually rolled back my changes so i'll have to re-implement them and get back to you (gimme an hour), I was however seeing something similar to @grimlockrocks set of issues.

**Comment by patrickjquinn** [comment]
First issue `ld: '/<my_home>/<my_project>/libsnowboy-detect.a(snowboy-detect.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7`

So i'll disable Bitcode and then see what the next bath of issues are.

**Comment by patrickjquinn** [comment]
Upon doing so I see ```
Ld /Users/<my_home>/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Intermediates/P-Brain.build/Debug-iphoneos/P-Brain.build/Objects-normal/arm64/P-Brain normal arm64
    cd /Users/patrickquinn/P-Brain.ai-iOS
    export IPHONEOS_DEPLOYMENT_TARGET=10.2
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/patrickquinn/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Products/Debug-iphoneos -L/Users/patrickquinn/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Products/Debug-iphoneos/XCDYouTubeKit -L/Users/patrickquinn/P-Brain.ai-iOS/P-Brain -F/Users/patrickquinn/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Products/Debug-iphoneos -filelist /Users/patrickquinn/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Intermediates/P-Brain.build/Debug-iphoneos/P-Brain.build/Objects-normal/arm64/P-Brain.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=10.2 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/patrickquinn/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Intermediates/P-Brain.build/Debug-iphoneos/P-Brain.build/Objects-normal/arm64/P-Brain_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -stdlib=libc++ -ObjC -lXCDYouTubeKit -framework JavaScriptCore -framework MediaPlayer -framework QuartzCore -lsnowboy-detect -framework Foundation -framework Speech -framework AVFoundation -framework AudioToolbox -lPods-P-Brain -Xlinker -dependency_info -Xlinker /Users/patrickquinn/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Intermediates/P-Brain.build/Debug-iphoneos/P-Brain.build/Objects-normal/arm64/P-Brain_dependency_info.dat -o /Users/patrickquinn/Library/Developer/Xcode/DerivedData/P-Brain-ftnorchkstrokjbzenygrweqttko/Build/Intermediates/P-Brain.build/Debug-iphoneos/P-Brain.build/Objects-normal/arm64/P-Brain

Undefined symbols for architecture arm64:
  "_cblas_snrm2", referenced from:
      snowboy::VectorBase::CosineDistance(snowboy::VectorBase const&) const in libsnowboy-detect.a(vector-wrapper.o)
  "_cblas_sgemv", referenced from:
      snowboy::VectorBase::AddMatVec(float, snowboy::MatrixBase const&, snowboy::MatrixTransposeType, snowboy::VectorBase const&, float) in libsnowboy-detect.a(vector-wrapper.o)
  "_cblas_sger", referenced from:
      snowboy::MatrixBase::AddVecToRows(float, snowboy::VectorBase const&) in libsnowboy-detect.a(matrix-wrapper.o)
  "_cblas_sgemm", referenced from:
      snowboy::MatrixBase::AddMatMat(float, snowboy::MatrixBase const&, snowboy::MatrixTransposeType, snowboy::MatrixBase const&, snowboy::MatrixTransposeType, float) in libsnowboy-detect.a(matrix-wrapper.o)
  "_cblas_sdot", referenced from:
      snowboy::VectorBase::AddDiagMat2(float, snowboy::MatrixBase const&, snowboy::MatrixTransposeType, float) in libsnowboy-detect.a(vector-wrapper.o)
      snowboy::VectorBase::DotVec(snowboy::VectorBase const&) const in libsnowboy-detect.a(vector-wrapper.o)
      snowboy::VectorBase::CosineDistance(snowboy::VectorBase const&) const in libsnowboy-detect.a(vector-wrapper.o)
  "_cblas_saxpy", referenced from:
      snowboy::MatrixBase::AddMat(float, snowboy::MatrixBase const&, snowboy::MatrixTransposeType) in libsnowboy-detect.a(matrix-wrapper.o)
      snowboy::Vector::Read(bool, bool, std::__1::basic_istream<char, std::__1::char_traits<char> >*) in libsnowboy-detect.a(vector-wrapper.o)
  "_cblas_sscal", referenced from:
      snowboy::MatrixBase::AddMat(float, snowboy::MatrixBase const&, snowboy::MatrixTransposeType) in libsnowboy-detect.a(matrix-wrapper.o)
      snowboy::VectorBase::ApplySoftmax() in libsnowboy-detect.a(vector-wrapper.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Which is the exact same output as last time. Building against generic device as a target.

**Comment by chenguoguo** [comment]
Let's first try to fix those missing symbols. Those are from CBLAS, did you add the `Accelerate` framework when you compile?

See here:
https://developer.apple.com/reference/accelerate

The `Accelerate` framework contain those symbols.

In my old demo, I used the following frameworks: `CoreAudio`, `AudioToolbox`, `AudioUnit`, `CoreServices`. But I was using those through object-c, and I haven't really played with swift.

Let me know if playing with the frameworks helps!

**Comment by grimlockrocks** [comment]
Aha, "You cannot import C++ code directly into Swift. Instead, create an Objective-C or C wrapper for C++ code." according to https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/index.html#//apple_ref/doc/uid/TP40014216-CH2-ID0

One workaround is to write a Objective-C wrapper for snowboy-detect.h. The bridging header only links Objective-C files, therefore, the compiler failed to compile. 

Ideally, (I know that's lots of work for you), it would be great if you can provide .framework file instead of the static library. This would make our lives easier :)

**Comment by patrickjquinn** [comment]
@chenguoguo Yep adding accelerate seems to have solved the issue! No longer getting any build errors 👍

**Comment by chenguoguo** [comment]
@patrickjquinn are you using swift or objective-c? @grimlockrocks is having some trouble with swift, and I don't have any experience with that. If you are using swift, could you let @grimlockrocks what is your setting?

**Comment by patrickjquinn** [comment]
Sadly Obj-C only, havent attempted to build a bridge header yet. 

In other news i'll be submitting a PR to you guys with a sample Obj-C application using Snowboy

**Comment by chenguoguo** [comment]
Awesome!

**Comment by grimlockrocks** [comment]
I got it working for Swift 3 as well - all I needed was Objective-C wrapper, then the Swift 3 code can call the Objective-C code to instantiate a new instance of SnowboyDetect.

**Comment by grimlockrocks** [comment]
@patrickjquinn Let me know if the detection works well for your Obj-C code, I always get -2 for some reason... I chopped my recording to 3 seconds, with the following settings:
let recordSettings =
                [AVEncoderAudioQualityKey: AVAudioQuality.high.rawValue,
                 AVEncoderBitRateKey: 128000,
                 AVNumberOfChannelsKey: 1,
                 AVSampleRateKey: 16000.0] as [String : Any]

Then I persisted the audio to a ".wav" file. The play back sounds right to me. I used the following code to convert into a float array:
let file = try! AVAudioFile(forReading: soundFileURL)
let format = AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: 16000.0, channels: 1, interleaved: false)
let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: 1024)
 try! file.read(into: buffer)
let floatArray = Array(UnsafeBufferPointer(start: buffer.floatChannelData?[0], count:Int(buffer.frameLength)))
                
let result = wrapper.runDetection(UnsafeMutablePointer(mutating: floatArray), length: Int32(buffer.frameLength))

This will always return -2. "floatArray" looks about right to me in terms of positive/negative floats all over the place. Thanks!

**Comment by chenguoguo** [comment]
Snowboy uses 16 bit signed-integer, so make sure your audio format is correct.

**Comment by patrickjquinn** [comment]
The Obj-C demo isn't quite ready to go but if you check https://github.com/patrickjquinn/P-Brain.ai-iOS/blob/master/P-Brain/ViewController.mm in my P-Brain.ai iOS client, specifically the `initSnowboy` & `initMic` methods you'll see the right setup and audio format settings.

This demo (and my own project) makes use of EZMic direct input instead of piping to a file or any other method 👍

**Comment by grimlockrocks** [comment]
Thank you. I will take a look. I think I am getting very close. I do not know C++/Obj-C that well, and I think the problem stays with how I pass the integer array to the API: int RunDetection(const int16_t* const data, const int array_length); via the Obj-C wrapper, somehow only the pointer to the first element in the array was passed in, therefore sizeof data is very small (only 8 bytes in my case).

**Comment by grimlockrocks** [comment]
Here you go: https://github.com/grimlockrocks/kitt-snowboy-swift3-sample-app

**Comment by chenguoguo** [comment]
Awesome! Could you like to submit a PR and put it under e.g., `examples/Swift`? Feel free if you'd prefer keeping it as an independent project.

**Comment by patrickjquinn** [comment]
I've submitted a PR with the iOS Obj-C demo, its rock solid but I can make any changes you see if 👍  https://github.com/Kitt-AI/snowboy/pull/125

**Comment by grimlockrocks** [comment]
I have submitted a pull request too, basically just copy/paste but let me know if you want me to make any changes.

**Comment by chenguoguo** [comment]
Thanks you very much guys! I'll take a look and merge them this afternoon as I'm getting a little bit of free time from other stuff.

**Comment by peternann** [comment]
Nice! My timing is impeccable. Just started looking to stand up an iOS demo, and lo and behold!, one has appeared here just a few hours ago.
Thanks guys!
I got the spanking new iOS/Obj-c example running trivially in XCode 8.2.1. Simulator successfully detects my "Alexa" hot word when spoken. Thanks again.

**Comment by patrickjquinn** [comment]
Really glad to hear that @peternann ! It doesn't have any fancy bells and whistles but hopefully its enough to get everything off the ground without too much effort 👍  The real thanks should go to the Kitt.ai team for making such an awesome project open and offline!

**Comment by chenguoguo** [comment]
Great. I'll finishing merging both demos today.

**Comment by satputepritam** [comment]
@grimlockrocks  one quick question, Is snoyboy free when we have to submit app to AppStore.
I am using snowboy in swift 3 and it's working fine. Just get to know that is it free ??

**Comment by grimlockrocks** [comment]
@satputepritam You may need to check with them and understand the licensing, depends on whether you will use it personally or commercially I guess. I was just playing for fun, not for real app.

**Comment by chenguoguo** [comment]
It depends. If you are selling this as a commercial product, then you'll need to get a license form us. If there will be a license fee, or how much will the license fee be, that depends on your actual product. For more information, please send an email to snowboy@kitt.ai
