### ISSUE TITLE
Error when switching audio rate

### ISSUE THREAD

**Issue by glennglennglenn** [Kitt-AI/snowboy#123]
After I detect a hotword and try to read additional audio from the microphone I get this error on a Mac:
||PaMacCore (AUHAL)|| Error on line 2490: err='-10863', msg=Audio Unit: cannot do in current context
||PaMacCore (AUHAL)|| Error on line 2490: err='-10863', msg=Audio Unit: cannot do in current context

Someone else has experienced this error but the answer was not written: https://github.com/Kitt-AI/snowboy/issues/37

Does anyone know how to fix it?

**Comment by glennglennglenn** [comment]
I figured it out. I had to set PyAudio's setting to be the same for both recorders.

**Comment by chenguoguo** [comment]
OK, closing this then.

**Comment by sarendsen** [comment]
@glennglennglenn Any pointers on how and where todo this?

**Comment by glennglennglenn** [comment]
For Alexa Voice Service you need to use the same audio rate.

THRESHOLD = 500
CHUNK_SIZE = 1024
FORMAT = pyaudio.paInt16
**RATE = 16000**

**Comment by renatodmb** [comment]
Same issue!
I'm using with the Snowboy the python speech recognition.
I could not find where can I change this rate.
Can you guys help me where can I configure this Rate into snowboy?

Tks.

**Comment by renatodmb** [comment]
here is the link: https://pypi.python.org/pypi/SpeechRecognition/

**Comment by glenncameronjr** [comment]
I believe it is line 75 here: https://github.com/Uberi/speech_recognition/blob/master/speech_recognition/__init__.py 

Try changing sample_rate=None to sample_rate=16000

**Comment by mikelibg** [comment]
I using snowboy in a project where I also use google speech recognition for longer audio. Google works properly as long as it is triggered before snowboy detection is used. Running google speech after snowboy causes this error:

**||PaMacCore (AUHAL)|| Error on line 2490: err='-10863', msg=Audio Unit: cannot do in current context
||PaMacCore (AUHAL)|| Error on line 2490: err='-10863', msg=Audio Unit: cannot do in current context**

Both google and snowboy using pyaudio but they are using different streams (which are closed eventually) so I do not see the point of setting both streams to the same sample rate (as proposed), although in my case the rate is the same for both and I am still getting this error. 

Please help

**Comment by chenguoguo** [comment]
The best way is to change your code and make Google and Snowboy share the same stream. If that's too much work for you, you could also terminate Snowboy before starting Google, see here:https://github.com/Kitt-AI/snowboy/issues/12

**Comment by mikelibg** [comment]
@chenguoguo, i didn't want to use the same pyaudio so that those two components (snowboy,google) would be separate modules without external dependencies on pyaudio library, but it seems that this is the only things that is left to try.

I was always terminating the stream and audio that Snowboy uses before starting Google and it is not working.

**Comment by cnhnlin** [comment]
Hi @mikelibg, I have no idea about that how to use different pyaduio instances and different streams.
 Would you show me some examples codes? thank you so much!

**Comment by Vricken** [comment]
after terminating i still get the error:
_||PaMacCore (AUHAL)|| Error on line 2490: err='-10863', msg=Audio Unit: cannot do in current context_

```
import snowboydecoder
import signal
import ait2

interrupted = False


def signal_handler(signal, frame):
    global interrupted
    interrupted = True


def interrupt_callback():
    global interrupted
    return interrupted


signal.signal(signal.SIGINT, signal_handler)

detector = snowboydecoder.HotwordDetector("AiT.pmdl", sensitivity=0.5, audio_gain=1)
print('Listening... Press Ctrl+C to exit')

detector.start(detected_callback=ait2.run,
               interrupt_check=interrupt_callback,
               sleep_time=0.03)

detector.terminate()

```

How do i terminate since it does not seem to be working?
pls help

**Comment by nspeer12** [comment]
I was getting the same issue and was able to fix it by implementing start and stop functions for the pyaudio stream

```
def start_audio_stream(self):
		self.audio = pyaudio.PyAudio()

		self.audio_stream = self.audio.open(
								rate=self.porcupine.sample_rate,
								channels=1,
								format=pyaudio.paInt16,
								input=True,
								frames_per_buffer=self.porcupine.frame_length)


	def stop_audio_stream(self):
		self.audio_stream.close()
		self.audio.terminate()
```

I'm storing the audio stream in the class I created. My main loop looks something like this

````
def loop():
    self.start_stream()
    while run:
        # detect hotword
        pcm = self.audio_stream.read(self.porcupine.frame_length)
        pcm = struct.unpack_from("h" * self.porcupine.frame_length, pcm)
        keyword_index = self.porcupine.process(pcm)
    
       if keyword_index >= 0:
            self.stop_audio_stream()
	    print("Hotword Detected")

            #  call function with different pyaudio stream
	    self.listen()

	    # start the stream again when listen function returns
            self.start_audio_stream()
		
```
