### ISSUE TITLE
PS3 eye unplug/plug

### ISSUE THREAD

**Issue by Jeepster60** [Kitt-AI/snowboy#13]
Hi guys, great work!
have big Interest in snowboy and I've got it working on a Raspi with PS3 eye.
Problem is: after each reboot, ps3 eye isn't working. lsusb shows it, but no rec possible until I unplug and plug the Cam.
After days of testing and searching I'm now hoping for a little hint for configuring the cam correct.
uname -r shows 4.4.11+
OS is a raspian jessie 2016-05-10 with dist-upgrade

many greetings Michael

**Comment by xuchen** [comment]
I experienced exactly the opposite issue and I think it's a driver problem. Sometimes after we plug in the PS3 eye, we have to reboot to have it recognized. The only way out I'd say is use a different camera?

**Comment by Jeepster60** [comment]
ok, an old MS Lifecam works. But the hotword hits are better with the ps3 eye at greater distances. Want to make Homeautomation and with the ps3 eye it reacts even in the next room.
Just now I would go on with the Lifecam. Later I would spend some time with the ps3 eye boot/unplug issue.

**Comment by xuchen** [comment]
Good to know! Let us know if you find out. The PS3 Eye has 4 channels of audio and should pick up voice in the distance better.
