### ISSUE TITLE
Model umdl

### ISSUE THREAD

**Issue by josep112** [Kitt-AI/snowboy#130]
I searched but did not find how I can create imdl models
Thanks

**Comment by chenguoguo** [comment]
I guess you meant umdl models? You cannot do it by yourself. Currently there are two ways to get the umdl models:

1. On our website `snowboy.kitt.ai`, if a certain hotword has more contributed recordings then its threshold, we will train the universal hotword and give it back to the community, for non-commercial purpose.

2. We provide a service for training universal hotwords, for more details please email snowboy@kitt.ai

**Comment by josep112** [comment]
Ok thanks

**Comment by midshipman** [comment]
so umdl is the trained model, what does it stand for? what DNN framework you use to build it, MXNet, TF, etc?

**Comment by chenguoguo** [comment]
It stands for "universal model". We have our internal DNN implementation.
