### ISSUE TITLE
Android instructions only work on Unix

### ISSUE THREAD

**Issue by peternann** [Kitt-AI/snowboy#133]
I understand you can't do everything all at once...

But could the project README at least mention the fact that the Android instructions only work on Unix?
(Or maybe a fully-fledged Cygwin setup on Windows)

Just headed down this path only to find I am probably at a dead-end on Windows.

**Comment by chenguoguo** [comment]
Correct. We don't have good support for Windows. Will add that to README.

**Comment by peternann** [comment]
Thanks. I see the line you've added at the top.

Perhaps you could mention it specifically in the Android section? I suppose most Windows users will be jumping there, as they are not on *nix, and they are not on OSX, so that mostly leaves Android!

You could also mention there that it _might_ be possible to make the Android setup work with a sufficiently configured Cygwin (or maybe MinGW) setup - Minimally adding make and gcc over the defaults.
I got some of the way through this but gave up. The road ahead may or may not be clear I admit...

Anyway, really excited about this working on iOS. I have some app ideas...
Thanks to you and the contributors.

**Comment by xuchen** [comment]
@peternann advice taken, thanks for looking into that. I just modified README per your request. I didn't add the cygwin part as we didn't test it and don't want to misguide users.
