### ISSUE TITLE
Confidence indicator?

### ISSUE THREAD

**Issue by Stan92** [Kitt-AI/snowboy#138]
Hi,

Is there a way to get a confidence percentage on detected hotword?
I think it could help.

**Comment by evancohen** [comment]
It would help to know what you want to use it for. You can't get confidence (that I know of), but you can adjust the detector threshold (which accomplishes the same thing as getting the confidence and setting a threshold in your own code)

**Comment by Stan92** [comment]
Example, let's say if the recognition is less than 75%, this value means the detection is not "efficient/sure" and I can, for my need, ask the user to repeat again the hotword... 
it could be also use to ignore the detected hotword under a certain percentage.
I don't know if it could be done using the threshold.
From my tests using snowboy, sometimes some hotwords are detected as other hotwords.
Probably, but I may be wrong, with this indicator, I'll be able to manage the action to perform.

**Comment by chenguoguo** [comment]
The threshold here is related to the confidence score: a confidence score above the threshold will be treaded as the detection.

We don't have the confidence score in the current API.

How many hotwords are you using at the same time? You could probably design the hotwords so that they sound different from each other.

**Comment by Stan92** [comment]
I'm using 10 hotwords. sometimes they are well detected sometimes not.
I'll play with the threshold value.. 
I thank you for your feedback.

**Comment by GiovanniBalestrieri** [comment]
Hi, could you point us to the section of code that implements this
> a confidence score above the threshold will be treaded as the detection.

**Comment by chenguoguo** [comment]
It's internal code.
