### ISSUE TITLE
IOError: [Errno -9997] Invalid sample rate

### ISSUE THREAD

**Issue by nomadic-squirrel** [Kitt-AI/snowboy#14]
Hey guys!
   Great stuff! This is pretty much exactly what I was trying to build! But you guys are way further than I ever would have gotten. Er, but I didn't get very far. 

I'm running this on a raspberry pi model B with a Cyber Acoustics USB microphone. I can successfully record something using `AUDIODEV=hw:1,0 rec t.wav`. 

Anyway, when attempting the demo with this command:
```
pi@raspberrypi:~/Downloads/snowboy $ python demo.py ./resources/snowboy.umdl 
```
I get a bunch of garbage from ALSA that is apparently just warnings. But the last bit dumps this:
```
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/Downloads/snowboy/snowboydecoder.py", line 115, in __init__
    stream_callback=audio_callback)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9997] Invalid sample rate
```

I saw this while playing with another voice recognition and I was able to get past it by passing a sample rate. Is there an easy way to pass sample rate to your decoder?

For reference, here is the get_device_count dump:
```python
import pyaudio
p = pyaudio.PyAudio()
for i in range(p.get_device_count()):
    print p.get_device_info_by_index(i)
```

Output: (formatted for reading!)
```
{
    'defaultSampleRate': 44100.0,
    'defaultLowOutputLatency': 0.005804988662131519,
    'defaultLowInputLatency': -1.0,
    'maxInputChannels': 0 L,
    'structVersion': 2 L,
    'hostApi': 0 L,
    'index': 0,
    'defaultHighOutputLatency': 0.034829931972789115,
    'maxOutputChannels': 2 L,
    'name': u 'bcm2835 ALSA: - (hw:0,0)',
    'defaultHighInputLatency': -1.0
} {
    'defaultSampleRate': 44100.0,
    'defaultLowOutputLatency': 0.005804988662131519,
    'defaultLowInputLatency': -1.0,
    'maxInputChannels': 0 L,
    'structVersion': 2 L,
    'hostApi': 0 L,
    'index': 1,
    'defaultHighOutputLatency': 0.034829931972789115,
    'maxOutputChannels': 2 L,
    'name': u 'bcm2835 ALSA: IEC958/HDMI (hw:0,1)',
    'defaultHighInputLatency': -1.0
} {
    'defaultSampleRate': 48000.0,
    'defaultLowOutputLatency': -1.0,
    'defaultLowInputLatency': 0.007979166666666667,
    'maxInputChannels': 2 L,
    'structVersion': 2 L,
    'hostApi': 0 L,
    'index': 2,
    'defaultHighOutputLatency': -1.0,
    'maxOutputChannels': 0 L,
    'name': u 'Cyber Acoustics USB device: Audio (hw:1,0)',
    'defaultHighInputLatency': 0.032
} {
    'defaultSampleRate': 44100.0,
    'defaultLowOutputLatency': 0.005804988662131519,
    'defaultLowInputLatency': -1.0,
    'maxInputChannels': 0 L,
    'structVersion': 2 L,
    'hostApi': 0 L,
    'index': 3,
    'defaultHighOutputLatency': 0.034829931972789115,
    'maxOutputChannels': 128 L,
    'name': u 'sysdefault',
    'defaultHighInputLatency': -1.0
} {
    'defaultSampleRate': 44100.0,
    'defaultLowOutputLatency': 0.005804988662131519,
    'defaultLowInputLatency': -1.0,
    'maxInputChannels': 0 L,
    'structVersion': 2 L,
    'hostApi': 0 L,
    'index': 4,
    'defaultHighOutputLatency': 0.034829931972789115,
    'maxOutputChannels': 128 L,
    'name': u 'default',
    'defaultHighInputLatency': -1.0
} {
    'defaultSampleRate': 48000.0,
    'defaultLowOutputLatency': 0.021333333333333333,
    'defaultLowInputLatency': -1.0,
    'maxInputChannels': 0 L,
    'structVersion': 2 L,
    'hostApi': 0 L,
    'index': 5,
    'defaultHighOutputLatency': 0.021333333333333333,
    'maxOutputChannels': 2 L,
    'name': u 'dmix',
    'defaultHighInputLatency': -1.0
}
```

**Comment by chenguoguo** [comment]
Hi, regarding changing the sampling rate, Snowboy requires a specific sampling rate which you can see by calling the SampleRate() function. For now it's 16k. You can use different sampling rate for PyAudio, but when you feed the data to Snowboy detector, you will have to convert the data to 16k sampling rate.

As for the "Invalid sample rate" error, there's a long discussion in [this](https://github.com/sammachin/AlexaPi/issues/82) thread. It might has something to do with pulseaudio. Some people mentioned that they were able to fix the issue by using a fresh installation of the OS. You can go through the thread to see what's the best fix.

Please do let us know if you end up with a nice solution to the issue!

**Comment by nomadic-squirrel** [comment]
Ok, thanks for the update. For now I started new with a fresh image of Raspbian jesse. If I run into this issue there, I'll dig further. I was doing a lot with installing libraries and messing with the microphone, so maybe something got whacky in that.

**Comment by chenguoguo** [comment]
@nomadic-squirrel could you let me know if this was fixed eventually? If yes how did you fix it? Thanks!

**Comment by cjolif** [comment]
I've got similar error on Raspberry with the C++ sample.

```
Fail to open PortAudio stream, error message is "Invalid sample rate"
Listening... Press Ctrl+C to exit
```

and nothing works.

ALSA description of my microphone is:

```[ Default Input ]
Name                        = USB PnP Sound Device: Audio (hw:1,0)
Host API                    = ALSA
Max inputs = 1, Max outputs = 0
Default low input latency   =   0.0087
Default low output latency  =  -1.0000
Default high input latency  =   0.0348
Default high output latency =  -1.0000
Default sample rate         = 44100.00
Supported standard sample rates
 for half-duplex 16 bit 1 channel input =
	44100.00, 48000.00
```

**Comment by chenguoguo** [comment]
Snowboy requires a sample rate of 16k, it could be that the 16k sampling rate is not supported by your microphone. If you have other microphones by hand, you can give them a try.

**Comment by sriranjanr** [comment]
I am having the same invalid sample rate issue, The sample rate support by my USB mic is 44100. So where and how should I set the sample rate?

**Comment by chenguoguo** [comment]
There are usually two options:

1. Try another microphone

2. Try the arecord demo: https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/demo_arecord.py
