### ISSUE TITLE
Android platform

### ISSUE THREAD

**Issue by caohaoping** [Kitt-AI/snowboy#142]
The integration tutorial on Android is too simple, you can step by step and then detailed?

**Comment by xuchen** [comment]
Duplicate of https://github.com/Kitt-AI/snowboy/issues/106

What's your Android platform and CPU? We currently have a more detailed version but it won't come out until next week.

**Comment by xuchen** [comment]
@caohaoping I worked on the https://github.com/Kitt-AI/snowboy/tree/android-demo branch and pushed a demo there. Could you please check it out and give comments?

https://github.com/Kitt-AI/snowboy/blob/android-demo/examples/Android/README.md

I'll merge this branch in about a week's time. Your opinion on this is much appreciated.
