### ISSUE TITLE
Correspond to Bitcode

### ISSUE THREAD

**Issue by ysak-y** [Kitt-AI/snowboy#143]
## OverVIew

[As patrickjquinn mentioned,](https://github.com/Kitt-AI/snowboy/issues/121#issuecomment-279455960) build will error with `ENABLE_BITCODE` option.

He avoid this error disabling `ENABLE_BITCODE` option. But it's makeshift strategy. Using bitcode provides a [large benefit](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35-SW2) to us.

So please re-build `libsnowboy-detect.a(snowboy-detect.o)` corresponding to bitcode.

**Comment by xuchen** [comment]
@chenguoguo will be on it

**Comment by chenguoguo** [comment]
@ysak-y we'll take a look and see if there's any drawbacks (e.g., security issues) enabling it. Most likely we will enable it in the next release, which should be very soon.

**Comment by chenguoguo** [comment]
We enabled it, so closing it.
