### ISSUE TITLE
Question: stream audio from browser

### ISSUE THREAD

**Issue by celevra** [Kitt-AI/snowboy#145]
Hi,

i'm searching for a solution to recognize a hotword and only then stream the sound to webkits speechrecognition.

i could think of a model like streaming the audio to a node.js server through websockets, if it recognizes the hotwork it sends back an event and then the normal browser speechrecognition is used.

could it be realized with snowboy?

regards

celevra

**Comment by chenguoguo** [comment]
Technically this should be doable. This is actually how we set up the testing in our website. We use websockets streams the audio data to the server, let the Python library does the detection, and then sends back the results. You could of course use the node.js module as well.

**Comment by chenguoguo** [comment]
I'm going to close this since the question has been answered. Feel free to re-open it or ask another question.

**Comment by celevra** [comment]
Thank you for guiding in the right Directory!
