### ISSUE TITLE
Python3.6: Symbol not found: _PyClass_Type

### ISSUE THREAD

**Issue by zikphil** [Kitt-AI/snowboy#146]
Hey guys,

So i've compiled the Python version of snowboy, while replacing python-config with python3-config as i did before on older python3 versions. I can't get it to work for some reason... It keeps throwing the following:

```
Traceback (most recent call last):
  File "/.../demo.py", line 1, in <module>
    import snowboydecoder
  File "/.../snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/.../snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/..../snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/.../_snowboydetect.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /..../_snowboydetect.so
  Expected in: flat namespace
 in /.../_snowboydetect.so```

**Comment by chenguoguo** [comment]
Do you have multiple version of Python installed on your system? It's most likely a version mismatch, see the following posts when I searched "Symbol not found: _PyClass_Type" on Google:

http://stackoverflow.com/questions/25794288/linking-fails-while-interfacing-with-swig
http://stackoverflow.com/questions/19865757/importerror-usr-lib-libboost-python-so-1-54-0-undefined-symbol-pyclass-type

**Comment by zikphil** [comment]
Most of us on Mac do. Python2.7 is built-in to OSX. I installed Python3.6 using homebrew. Is there something specific this library is doing that would make it not work? The _PyClass_Type symbol is not part of Python3. Has anyone been able to successfully compile it using Python3 on Mac?

None of the link you sent me regards solution i can do trying to compile it, it seems more like things we could do in the snowboy c level.

Thoughts? Do you have a version compiled on 3.6 laying around? :)

**Comment by xuchen** [comment]
@zikphil I just tested on Ubuntu 16.04 with Python 3.6 and 3.5, both worked. Could you please confirm this is a Mac-specific issue?

**Comment by chenguoguo** [comment]
@zikphil could you post the output of the following commands?

```
python3 --version

# If on OSX
python3-config --includes
python3-config --ldflags

# If on Linux
python3-config --cflags
python3-config --ldflags
```

**Comment by zikphil** [comment]
```
~ $ python3 --version                                                                                                                                                                                                                                     12:12:50
Python 3.6.0
~ $ python3-config --includes                                                                                                                                                                                                                             12:12:52
-I/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/include/python3.6m
~ $ python3-config --ldflags                                                                                                                                                                                                                              12:13:00
-L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation
```

**Comment by chenguoguo** [comment]
Did you also make sure that you change from this line
```
$(SWIG) -I$(TOPDIR) -c++ -python -o $(SNOWBOYDETECTSWIGCC) $(SNOWBOYDETECTSWIGITF)
```
to something like
```
$(SWIG) -I$(TOPDIR) -c++ -python3 -o $(SNOWBOYDETECTSWIGCC) $(SNOWBOYDETECTSWIGITF)
```

I have only tried Python 3.5 on my OSX, I will have to try it in virtual environment later.

**Comment by zikphil** [comment]
changing that line gives me the following:
```
/V/P/s/s/Python (master|✔) $ make
swig -I../../ -c++ -python3 -o snowboy-detect-swig.cc snowboy-detect-swig.i
swig error : Unrecognized option -python3
Use 'swig -help' for available options.
make: *** [snowboy-detect-swig.cc] Error 1
```

**Comment by zikphil** [comment]
Ok @chenguoguo sent me on the right path. You actually need to add a flag to the swig command in the Makefile. It should read like this:

`$(SWIG) -I$(TOPDIR) -c++ -python -py3 -o $(SNOWBOYDETECTSWIGCC) $(SNOWBOYDETECTSWIGITF)`
