### ISSUE TITLE
Python binding error 

### ISSUE THREAD

**Issue by saurabhvyas** [Kitt-AI/snowboy#151]
I am using raspberry pi 3 and raspbian jessie , I have installed snowboy package from npm and cloned the repo , I was trying to follow instructions for python bindings but make command is throwing error

```
pi@orangepi:~/snowboy/swig/Python $ make
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
make: swig: Command not found
Makefile:48: recipe for target 'snowboy-detect-swig.cc' failed
make: *** [snowboy-detect-swig.cc] Error 127

```

**Comment by chenguoguo** [comment]
You have to install swig, make sure you have swig version 3.0.10 or above.

**Comment by saurabhvyas** [comment]
I did install swig 3.0

**Comment by chenguoguo** [comment]
Two things:

1. You have to install swig 3.0.10 or above, swig 3.0 will have issues.

2. Did you put swig in your path? For example, if you type swig in your command, does it come up?

**Comment by saurabhvyas** [comment]
When I type in swig , It doesnt show up , regarding version I am not sure , I just installed it with 
sudo apt-get install swig3.0 python-pyaudio python3-pyaudio sox

**Comment by chenguoguo** [comment]
That means your installation failed and that's why you are seeing the issues.

You could use the following script to install swig:

```
#!/bin/bash

# SWIG is a tool to compile c++ code into Python.

echo "Installing SWIG"

if [ ! -e swig-3.0.10.tar.gz ]; then
  wget -T 10 -t 3 \
    http://prdownloads.sourceforge.net/swig/swig-3.0.10.tar.gz || exit 1;
fi

tar -xovzf swig-3.0.10.tar.gz || exit 1
ln -s swig-3.0.10 swig

cd swig

# We first have to install PCRE.
if [ ! -e pcre-8.37.tar.gz ]; then
  wget -T 10 -t 3 \
    ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.37.tar.gz || exit 1;
fi
Tools/pcre-build.sh

./configure --prefix=`pwd` --with-pic
make
make install

cd ..
```

And make sure you put that in your path. If you don't know how to do that, simply searching that in google should give you the answer.

**Comment by Shreyash23** [comment]
The default version of swig from debian repo's is 3.0.2

Install the latest swig from git - https://github.com/swig/swig

This fixed problems for me.

**Comment by saurabhvyas** [comment]
Thanks but I am getting errors on swig installanation from github repo

```
pi@orangepi:~ $ git clone https://github.com/swig/swig.git
Cloning into 'swig'...
remote: Counting objects: 145041, done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 145041 (delta 29), reused 0 (delta 0), pack-reused 144940
Receiving objects: 100% (145041/145041), 56.95 MiB | 143.00 KiB/s, done.
Resolving deltas: 100% (99995/99995), done.
Checking connectivity... done.
pi@orangepi:~ $ cd swig
pi@orangepi:~/swig $ ./autogen.sh
+ test -d Tools/config
+ aclocal -I Tools/config
./autogen.sh: 11: ./autogen.sh: aclocal: not found
pi@orangepi:~/swig $ sudo ./autogen.sh
+ test -d Tools/config
+ aclocal -I Tools/config
./autogen.sh: 11: ./autogen.sh: aclocal: not found
pi@orangepi:~/swig $ ./configure --prefix=/some/directory
-bash: ./configure: No such file or directory
pi@orangepi:~/swig $ ./configure --prefix=/swig
-bash: ./configure: No such file or directory

```

**Comment by chenguoguo** [comment]
@saurabhvyas you have to install `aclocal` first, searching on Google you will find the following command to install it...

```
sudo apt-get install autotools-dev
```

**Comment by saurabhvyas** [comment]
Thanks , I think Ill close this now

**Comment by GiovanniBalestrieri** [comment]
For those who have the same problem:

```
git clone https://github.com/swig/swig.git

cd swig
./configure
make
sudo make install
```
