### ISSUE TITLE
pa_ringbuffer.h dependency error for C++ example

### ISSUE THREAD

**Issue by sshtel** [Kitt-AI/snowboy#152]
Hi, I am trying to build C++ example but included portaudio(install shell script) is too old so it causes dependency error.

Would you upgrade portaudio library for C++?

**Comment by chenguoguo** [comment]
What is your OS? PortAudio is not well maintained. We are using PortAudio for audio capturing just for demo purpose. If you have your own audio capturing, you can remove PortAudio and replace it with your own.

**Comment by chenguoguo** [comment]
The bug was introduced in this commit and we have fixed it: https://github.com/Kitt-AI/snowboy/commit/e53c3fb272bd4feedc706cb61e86bb76365b434b

Closing it.
