### ISSUE TITLE
Node JS example doesn't work because lib/node/index.js is missing.

### ISSUE THREAD

**Issue by sshtel** [Kitt-AI/snowboy#159]
In 'example/Node/file.js', It require('../..').Detector
And package.json's main field is 'index.js' but index.js has gone.

Do I need to transpile typescript code(index.ts) for index.js?

P.S. which branch is stable version?

**Comment by sshtel** [comment]
Issued closed.
npm install did not fully work on Fedora Linux ARMv7.
I installed packages manually and solved problem..

Well, still I have problem of libgfortran.so.3 dependecy though.

**Comment by xuchen** [comment]
@sshtel you mean you need a copy of `libgfortran.so.3` on Fedora ARMv7?
