### ISSUE TITLE
Doc issue: .asoundrc, not .asound

### ISSUE THREAD

**Issue by nomadic-squirrel** [Kitt-AI/snowboy#16]
Hey guys,
   I was going through the set up again and found I needed to set the hw value to get `rec t.wav` to work. I pasted in the settings doc'd in the "Set up audio" here: https://snowboy.kitt.ai/docs, but that says to save the file as `.asound` not `.asoundrc` which did work.

**Comment by chenguoguo** [comment]
Thanks for the catch. We have updated our documentation which should be available int he next deployment.
