### ISSUE TITLE
snowboy-io.cc:315 Fail to open input file

### ISSUE THREAD

**Issue by grimlockrocks** [Kitt-AI/snowboy#162]
Hello,

Continue with the iOS app, I have included the latest library and header file, re-downloaded common.res and the Alexa model file. However, when I call the constructor, I got the following error:

ERROR (Input():snowboy-io.cc:315) Fail to open input file "<path/to/common.res>"
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error

The file does exist. Can you share the implementation of snowboy-io.cc around line 315, what could throw an error like this?

Thank you!

**Comment by chenguoguo** [comment]
It simply says it cannot open the file, could you double check if "<path/to/common.res>" exists?

**Comment by grimlockrocks** [comment]
Ah, I figured it out. Thanks for the info. I wrongly used an absolute path which is not part of the app, therefore those files are not packed with the app. I am closing this issue now.

**Comment by grimlockrocks** [comment]
@chenguoguo I think there _may be_ a bug within the C/C++ library how the input file path is handled when the file path contains space. For examples:

ERROR (Input():snowboy-io.cc:315) Fail to open input file "/Library/Developer/CoreSimulator/Devices/5F6EA65A-5D89-4BE2-9FA3-276820395CBC/data/Containers/Bundle/Application/E1E5EAB9-A2F5-4195-A0D7-342FA00A3A9C/Alexa"

Adding the escape \ before calling Snowboy Detect constructer:

ERROR (Input():snowboy-io.cc:315) Fail to open input file "/Library/Developer/CoreSimulator/Devices/5F6EA65A-5D89-4BE2-9FA3-276820395CBC/data/Containers/Bundle/Application/E1E5EAB9-A2F5-4195-A0D7-342FA00A3A9C/Alexa\ iOS\ App.app/common.res"

Although the file path does exist. 

When I used a path without space, it worked fine.

**Comment by chenguoguo** [comment]
Yes try to avoid space for now.

**Comment by pallaviMN** [comment]
@grimlockrocks can you please tell me how did you correct because for me its not working "\"
