### ISSUE TITLE
 Input audio data is not block aligned

### ISSUE THREAD

**Issue by sunyore1972** [Kitt-AI/snowboy#163]
我的系统是Aarch64 的 Ubuntu 16.04, 我用 sonwboy 提供的Pine64的静态库编译，编译参数用的是Ubuntu 64的参数。
编译后没有报错。
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
g++ -I/usr/include/python3.5m -I/usr/include/python3.5m  -Wno-unused-result -Wsign-compare -g -fstack-protector-strong -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x  -shared snowboy-detect-swig.o \
../..//lib/pine64/libsnowboy-detect.a -L/usr/lib/python3.5/config-3.5m-aarch64-linux-gnu -L/usr/lib -lpython3.5m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas -o _snowboydetect.so

启动sonwboy时报错，
WARNING:snowboy:Error initializing streams or reading audio data
WARNING (RunDetection():snowboy-detect.cc:40) SnowboyDetect: input audio data is not block aligned.
INFO:snowboy:------ans=-1----
WARNING:snowboy:Error initializing streams or reading audio data
WARNING (RunDetection():snowboy-detect.cc:40) SnowboyDetect: input audio data is not block aligned.
INFO:snowboy:------ans=-1----
WARNING:snowboy:Error initializing streams or reading audio data
WARNING (RunDetection():snowboy-detect.cc:40) SnowboyDetect: input audio data is not block aligned.
INFO:snowboy:------ans=-1----
WARNING:snowboy:Error initializing streams or reading audio data
WARNING (RunDetection():snowboy-detect.cc:40) SnowboyDetect: input audio data is not block aligned.
INFO:snowboy:------ans=-1----

**Comment by chenguoguo** [comment]
Could you first make sure the C++ demo works? Most likely it's an issue with Python3 setup, if the C++ demo works.

**Comment by sunyore1972** [comment]
谢谢了，Python2  编译就没有问题了。
