### ISSUE TITLE
make: python-config: Command not found

### ISSUE THREAD

**Issue by nomadic-squirrel** [Kitt-AI/snowboy#17]
Hello again,
   After git clone of snowboy, I did:
```
cd swig/Python
make
```
And got these errors:
```
pi@raspberrypi:~/Downloads/snowboy/swig/Python $ make
make: python-config: Command not found
make: python-config: Command not found
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
make: swig: Command not found
Makefile:45: recipe for target 'snowboy-detect-swig.cc' failed
make: *** [snowboy-detect-swig.cc] Error 127
```

I was able to get around this by running
```
pip install python-config
sudo apt-get install python-dev swig
```

Question though.... I see the set up section uses swig3.0. But when I ran make, it couldn't find swig until I installed just `swig`. Is there an issue with installing these `3` version of things? I see it also in the `python3-pyaudio`.

**Comment by chenguoguo** [comment]
Yes, you'll have to install python-dev to get the Makefile work. Regarding swig, I normally don't do apt-get install swig, as I experienced issues (the detection doesn't work properly) with swig installed from apt-get install. I usually install it from source code, using the following commands:

`# SWIG is a tool to compile c++ code into Python.

echo "Installing SWIG"

if [ ! -e swig-3.0.7.tar.gz ]; then
  wget -T 10 -t 3 \
    http://prdownloads.sourceforge.net/swig/swig-3.0.7.tar.gz || exit 1;
fi

tar -xovzf swig-3.0.7.tar.gz || exit 1
ln -s swig-3.0.7 swig

cd swig

# We first have to install PCRE.
if [ ! -e pcre-8.37.tar.gz ]; then
  wget -T 10 -t 3 \
    ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.37.tar.gz || exit 1;
fi
Tools/pcre-build.sh

./configure --prefix=`pwd` --with-pic
make
make install

cd ..`

If you see wired issues, you can try to install swig from source code. BTW, if you are only using the python wrapper, we do provide precompiled versions for Raspberry Pi, see [here](https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.0.2.tar.bz2).

**Comment by nomadic-squirrel** [comment]
Woohoo!! It works! 
Yea, I removed swig and ran your script, but I did a global install, so I removed the `--prefix=${pwd}` (How does one escape markdown?? lol) and then changed `make install` to `sudo make install`. This raspberry will be dedicated to using this snowboy so I think that should be ok.

**Comment by stridera** [comment]
if you follow the instructions (and apt-get swig3.0) you can edit the make file to do this:

**Comment by richardfuchs** [comment]
I also had the Error:
TypeError: __init__() got an unexpected keyword argument 'model_str'

My Setup:

- Hardware: Raspberry Model B - Generation 1
- OS: Raspbian Jessie

I fixed it running a modified version of the above scipt:
```
#!/bin/bash

# SWIG is a tool to compile c++ code into Python.

echo "Installing SWIG"

if [ ! -e swig-3.0.7.tar.gz ]; then
  wget -T 10 -t 3 \
    http://prdownloads.sourceforge.net/swig/swig-3.0.7.tar.gz || exit 1;
fi

tar -xovzf swig-3.0.7.tar.gz || exit 1
ln -s swig-3.0.7 swig

cd swig

# We first have to install PCRE.
if [ ! -e pcre-8.37.tar.gz ]; then
  wget -T 10 -t 3 \
    https://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.gz || exit 1;
fi
Tools/pcre-build.sh

./configure --with-pic
make
sudo make install

cd ..
```
I also installed the needed programs/libs:
https://github.com/Kitt-AI/snowboy#ubunturaspberry-pi
**and** compiled snowboy myself (the pre-compiled/provided version had the above error)
https://github.com/Kitt-AI/snowboy#compile-a-python-wrapper
