### ISSUE TITLE
Streaming short bursts of audio data over websocket

### ISSUE THREAD

**Issue by richtier** [Kitt-AI/snowboy#171]
I'm streaming continuous audio data from the browser to the server via a websocket, every 10ms.

I see from [this demo](https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/demo3.py#L34) I can pass the audio data into `RunDetection`, but if the decector only receives 10ms of the wakeword, then it will  not detect the wakeword has been said.

Is there a common/existing solution to this?

I'm considering:
 - create a bufffer that keeps a second of audio
 - when a new 10ms is received over the websocket it removes 10ms from the start of the buffer and add the new 10ms to the end
 - every 10ms pass the 1 second of audio stored in the buffer to `RunDetection`.

This feels like a common problem to solve though. Is there ane existing way to do this?

**Comment by xuchen** [comment]
Could you please use the forum for discussion, rather than raising an issue? Thanks!

**Comment by richtier** [comment]
sure. terrible sorry.
