### ISSUE TITLE
Compile a Python Wrapper for all Python version?

### ISSUE THREAD

**Issue by Sispheor** [Kitt-AI/snowboy#175]
Hi. I have a question.
Do we need to compile the `_snowboydetect.so` for each Python version? I mean one binary for py2, one for py3.4, another for 3.5 and 3.6?
Or it is possible to generate a unique binary that would be usable by all interpreter?
Maybe this is more a swig question. I'm not totally sure.
Thank you !

**Comment by chenguoguo** [comment]
Yeah I think it's more likely a swig question :-)

I think if you compile Snowboy for Python 3.4, you can likely use it for Python 3.5 or 3.6. But if you compile it for e.g. Python 2.7, it's most likely not going to with with Python 3.4. So you may have to compile at least one for Python 2.x and one for Python 3.x

**Comment by Sispheor** [comment]
Thanks!
