### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'model_str'

### ISSUE THREAD

**Issue by nomadic-squirrel** [Kitt-AI/snowboy#18]
After successfully building from source, I'm running the demo, but ran into this error:

```
pi@raspberrypi:~/Downloads/snowboy/examples/Python $ python demo.py ./resources/snowboy.umdl 
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/Downloads/snowboy/examples/Python/snowboydecoder.py", line 91, in __init__
    resource_filename=resource, model_str=model_str)
TypeError: __init__() got an unexpected keyword argument 'model_str'
```

Lines 90s in `snowboydecoder.py`:
```python
        self.detector = snowboydetect.SnowboyDetect(
            resource_filename=resource, model_str=model_str)        # 91
        self.detector.SetAudioGain(audio_gain)
        self.num_hotwords = self.detector.NumHotwords()
```

But looking at snowboydetect.py, the constructor takes a pointer, so I'm not sure what it is complaining about. My python skills aren't great. 
```python
class SnowboyDetect(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SnowboyDetect, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SnowboyDetect, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _snowboydetect.new_SnowboyDetect(*args)
        try: self.this.append(this)
        except: self.this = this
```

**Comment by chenguoguo** [comment]
Could you try the swig installation commands I pasted [here](https://github.com/Kitt-AI/snowboy/issues/17)? I suspect it's an issue with swig.

**Comment by chenguoguo** [comment]
Closing this since the issue was resolved through https://github.com/Kitt-AI/snowboy/issues/17

**Comment by richardfuchs** [comment]
I also had the Error:
TypeError: __init__() got an unexpected keyword argument 'model_str'

My Setup:

- Hardware: Raspberry Model B - Generation 1
- OS: Raspbian Jessie

I fixed it running a modified version of the https://github.com/Kitt-AI/snowboy/issues/17#issuecomment-224766173 scipt:
```
#!/bin/bash

# SWIG is a tool to compile c++ code into Python.

echo "Installing SWIG"

if [ ! -e swig-3.0.7.tar.gz ]; then
  wget -T 10 -t 3 \
    http://prdownloads.sourceforge.net/swig/swig-3.0.7.tar.gz || exit 1;
fi

tar -xovzf swig-3.0.7.tar.gz || exit 1
ln -s swig-3.0.7 swig

cd swig

# We first have to install PCRE.
if [ ! -e pcre-8.37.tar.gz ]; then
  wget -T 10 -t 3 \
    https://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.gz || exit 1;
fi
Tools/pcre-build.sh

./configure --with-pic
make
sudo make install

cd ..
```
I also installed the needed programs/libs:
https://github.com/Kitt-AI/snowboy#ubunturaspberry-pi
**and** compiled snowboy myself (the pre-compiled/provided version had the above error)
https://github.com/Kitt-AI/snowboy#compile-a-python-wrapper

**Comment by chenguoguo** [comment]
@richardfuchs could you give me the link of the pre-compiled version that doesn't work? I should fix that.

**Comment by richardfuchs** [comment]
@chenguoguo https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.0.4.tar.bz2
