### ISSUE TITLE
Will not get installed in aarch64 systems (Nvidia TX2)

### ISSUE THREAD

**Issue by koolkarni** [Kitt-AI/snowboy#182]
when we try to run    "example/c++/install_portaudio.sh"

It gives problem with config.guess and config.sub 

by replacing the below attached files in portaudio.tar.gz file you will be able to install it 

NOTE: remove .txt from both files once copied 

[config.sub.txt](https://github.com/Kitt-AI/snowboy/files/980277/config.sub.txt)
[config.guess.txt](https://github.com/Kitt-AI/snowboy/files/980278/config.guess.txt)

**Comment by xuchen** [comment]
You are right, the portaudio version we currently use doesn't support `aarch64` yet. We'll need to do more test of the newest portaudio to make sure that this replacement doesn't break other systems. Thanks for reporting!

**Comment by koolkarni** [comment]
I am not able to install wiringpi on aarch64 any ideas ?

**Comment by xuchen** [comment]
we don't have experience with wiringpi 😢
