### ISSUE TITLE
When using node-record-lpcm16, hotword is not detected if its the last word of the sentence

### ISSUE THREAD

**Issue by Vikaton** [Kitt-AI/snowboy#184]
Using `node-record-lpcm16` likes this:
```js
let cmd = record.start({
            sampleRateHertz: 16000,
            threshold: 0.5,
            silence: '2.0',
            verbose: true
          }).pipe(detector)
```
and saying the hotword as the last word of the sentence (Or in this case, even just saying the hotword by itself), wont trigger snowboy to detect the word. But If I say another word after the hotword it will detect it

When using this however, a continuous stream:
```js
record.start({
          sampleRateHertz: 16000,
          threshold: 0,
        }).pipe(detector);
```

I can say the hotword and it will detect it. I piped the first example to the detector and a file to make sure it's getting it and the audio file says the hotword just fine.

Any reason as to why this is?

**Comment by Vikaton** [comment]
I feel like this may be an issue with `node-record-lpcm16` as when I'm trying to pipe audio data using the first example with Google Speech API, the last word is either cut off or dictated horribly.

**Comment by chenguoguo** [comment]
Not sure what happened with `node-record-lpcm16`, by looking at here: https://github.com/gillesdemey/node-record-lpcm16#options, it seems like it has something to do with the silence detection. But if you can hear the recording just fine, it really should work... Perhaps @evancohen has more insights?

**Comment by Vikaton** [comment]
So the issue I'm really seeing is that when the silence threshold is met with that library, it stops streaming(?) data to whatever writeable stream your piping to unless it exceeds a silence threshold which makes the streaming resume again, which in turn makes snowboy able detect it.

For example, I set the silence threshold to 10 seconds, started recording with verbose mode on, and I spoke the wake phrase.

After I said the phrase there was silence, and no sign of my wake phrase being triggered in the console(I have it to just print `true` if encountered) , but when I made some noise about 7 seconds in, the streaming "resumed" but it seemed like it was recording all along and streaming to snowboy cause when it did resume, my console.log immediately filled up with `Recording x bytes` and when I scrolled up a bit I saw the code trigger for my wake phrase in the console.

Maybe that gives some more insight on the problem? You could try replicating the issue on your side to maybe get a better idea of what I'm trying to get at.

**Comment by chenguoguo** [comment]
If it won't cause a CPU surge (?), perhaps you can set `threshold` to 0 and `silence` to 0. Internally Snowboy has a voice activity detector so I think it's not necessary to use the voice activity detector from `node-record-lpcm16`

**Comment by Vikaton** [comment]
So the objective is after I say a wake phrase in a continuous stream, that continuous stream ends and a new recording instance is started that is now recording to a wav file. Now snowboy is trying to detect certain command phrases, but if no command phrases are heard, then that audio file is sent to Alexa Voice service, but if it does detect a command phrase, then that audio file isn't sent to AVS, which is why I don't want a continuous stream in case its a command that's being sent to AVS and there is no way of ending the recording without waiting for silence (I'd rather not have an `end` keyword or have a fixed set time to end recording)

**Comment by chenguoguo** [comment]
Yes give that a try. [Sonus](https://github.com/evancohen/sonus) (which has Snowboy integration) might have the things you need too.
