### ISSUE TITLE
Can't run SnowBoy's demo. Getting an error.

### ISSUE THREAD

**Issue by zacharisharris** [Kitt-AI/snowboy#185]
I am in the process of setting up SnowBoy and I have trained my model, I am trying to run the demo using my model but I am getting this error:

`ImportError: libcblas.so.3: cannot open shared object file: No such file or directory`

What is wrong?

**Comment by Vikaton** [comment]
https://github.com/Kitt-AI/snowboy/issues/176#issuecomment-298404180
