### ISSUE TITLE
make fails with swig/Android/ndk_install/bin/arm-linux-androideabi-g++: No such file or directory

### ISSUE THREAD

**Issue by troyibm** [Kitt-AI/snowboy#189]
Trying to get the android example building (also tried the code in the android-demo branch) but both fail with the following error on macOS version 10.12.4.

`swig/Android/ndk_install/bin/arm-linux-androideabi-g++: No such file or directory`

Update: this problem solved by installing wget.

**Comment by xuchen** [comment]
Did you run go to `swig/Android` and build swig wrappers for Snowboy:

    cd swig/Android
    make

**Comment by troyibm** [comment]
yes.

```
~/git/snowboy/swig/Android$ make
./install_ndk.sh: line 12: wget: command not found
make: [/Users/troyibm/git/snowboy/swig/Android/ndk_install] Error 1 (ignored)
Cloning into 'OpenBLAS-Android'...
remote: Counting objects: 28641, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 28641 (delta 38), reused 0 (delta 0), pack-reused 28568
Receiving objects: 100% (28641/28641), 20.38 MiB | 4.12 MiB/s, done.
Resolving deltas: 100% (22447/22447), done.
Checking out files: 100% (8807/8807), done.
Branch arm_soft_fp_abi set up to track remote branch arm_soft_fp_abi from origin.
Switched to a new branch 'arm_soft_fp_abi'
HEAD is now at b5c96fcf Support ARM SOFTFP ABI for saxpy, sdot, snrm2, sscal, sgemv, sger.
C Compiler (/Users/troyibm/git/snowboy/swig/Android/ndk_install/bin/arm-linux-androideabi-gcc) is something wrong.
1 at ./c_check line 29.
make[1]: *** [config.h] Error 2
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:925: Makefile.: No such file or directory
make[1]: *** No rule to make target `Makefile.'.  Stop.
make: [OpenBLAS-Android/install/lib/libopenblas.a] Error 1 (ignored)
/Users/troyibm/git/snowboy/swig/Android/ndk_install/bin/arm-linux-androideabi-g++ -O3 --sysroot=/Users/troyibm/git/snowboy/swig/Android/ndk_install/sysroot -std=c++0x -rdynamic -I../../ -Werror -Wall -fsigned-char -fpic -fPIC -mfloat-abi=softfp -march=armv7-a -mfpu=neon -DNDEBUG -ffast-math -fomit-frame-pointer -O3 -pie -fPIE -DHAVE_NEON=1 -fno-strict-aliasing -Wno-unused-function -shared -c snowboy-detect-swig.cc -o snowboy-detect-swig.o
make: /Users/troyibm/git/snowboy/swig/Android/ndk_install/bin/arm-linux-androideabi-g++: No such file or directory
make: *** [snowboy-detect-swig.o] Error 1
```

**Comment by chenguoguo** [comment]
It says `wget` is not installed, so try to install `wget` first.

**Comment by troyibm** [comment]
Thanks.  I think that should be on the list of requirements somewhere (probably at the beginning of the Android section if wget is required just for making that).

However, even after installing wget, I get this error when running make from the swig/Android directory:

```
/Users/troyibm/git/snowboy/swig/Android/ndk_install/bin/arm-linux-androideabi-g++ -O3 --sysroot=/Users/tdugger/git/snowboy/swig/Android/ndk_install/sysroot -std=c++0x -rdynamic -I../../ -Werror -Wall -fsigned-char -fpic -fPIC -mfloat-abi=softfp -march=armv7-a -mfpu=neon -DNDEBUG -ffast-math -fomit-frame-pointer -O3 -pie -fPIE -DHAVE_NEON=1 -fno-strict-aliasing -Wno-unused-function -shared -c snowboy-detect-swig.cc -o snowboy-detect-swig.o
snowboy-detect-swig.cc: In function 'jint Java_ai_kitt_snowboy_snowboyJNI_SnowboyDetect_1RunDetection_1_1SWIG_10(JNIEnv*, jclass, jlong, jobject, jstring, jboolean)':
snowboy-detect-swig.cc:932:69: error: no matching function for call to 'snowboy::SnowboyDetect::RunDetection(const string&, bool&)'
   result = (int)(arg1)->RunDetection((std::string const &)*arg2,arg3);
```

I get that error many times but in different files.

**Comment by chenguoguo** [comment]
what is your swig version? is it 3.0.10 or above?

**Comment by troyibm** [comment]
yes.. 3.0.12.

```
SWIG Version 3.0.12

Compiled with clang++ [x86_64-apple-darwin16.3.0]

Configured options: +pcre
```

**Comment by chenguoguo** [comment]
I'm on MacOS Sierra 10.12.3

I first cleaned up everything under `swig/Android`, by first do `make clean`, and then `rm -rf OpenBLAS-Android android-ndk-r14b ndk_install/`

I then do `make`, and it compiles for me. My `swig` version is `3.0.10`.

Could you also clean up your `swig/Android` directory, then type `make` and log all the stdout in a file and send it to us? We might be able to see something there.

**Comment by troyibm** [comment]
worked.

**Comment by VibrantVipin** [comment]
Hi
I am getting this error when trying make.

Here are the logs:

Resolving dl.google.com (dl.google.com)... 74.125.204.91, 74.125.204.93, 74.125.204.136, ...
Connecting to dl.google.com (dl.google.com)|74.125.204.91|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /android/repository/android-ndk-r14b-linux-x86_64.zip [following]
--2017-07-24 20:02:46--  https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip
Reusing existing connection to dl.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 840626594 (802M) [application/zip]
Saving to: ‘android-ndk-r14b-linux-x86_64.zip’

100%[=====================================>] 84,06,26,594 2.20MB/s   in 3m 10s 

2017-07-24 20:05:56 (4.23 MB/s) - ‘android-ndk-r14b-linux-x86_64.zip’ saved [840626594/840626594]

HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=1
BUILD_NUM_CPUS=2
## COMMAND: python ./android-ndk-r14b/build/tools/make_standalone_toolchain.py --arch arm --api 14 --stl gnustl --install-dir=/home/vipin/Project/github/snowboy/swig/Android/ndk_install_32bit
Toolchain installed to /home/vipin/Project/github/snowboy/swig/Android/ndk_install_32bit.
Cloning into 'OpenBLAS-Android-ARM32'...
remote: Counting objects: 29166, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 29166 (delta 31), reused 35 (delta 13), pack-reused 29110
Receiving objects: 100% (29166/29166), 20.53 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (22856/22856), done.
Checking connectivity... done.
Branch arm_soft_fp_abi set up to track remote branch arm_soft_fp_abi from origin.
Switched to a new branch 'arm_soft_fp_abi'
HEAD is now at b5c96fc Support ARM SOFTFP ABI for saxpy, sdot, snrm2, sscal, sgemv, sger.
C Compiler (/ndk_install_32bit/bin/arm-linux-androideabi-gcc) is something wrong.
1 at ./c_check line 29.
make[1]: *** [config.h] Error 2
make[1]: Entering directory `/home/vipin/Project/github/snowboy/swig/Android/OpenBLAS-Android-ARM32'
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:925: Makefile.: No such file or directory
make[1]: *** No rule to make target `Makefile.'.  Stop.
make[1]: Leaving directory `/home/vipin/Project/github/snowboy/swig/Android/OpenBLAS-Android-ARM32'
make: [OpenBLAS-Android-ARM32/install/lib/libopenblas.a] Error 1 (ignored)
swig -I../../ -c++ -java -package ai.kitt.snowboy -outdir \
  java/ai/kitt/snowboy/ -o snowboy-detect-swig.cc snowboy-detect-swig.i
/ndk_install_32bit/bin/arm-linux-androideabi-g++ -O3 --sysroot=/ndk_install_32bit/sysroot -std=c++0x -rdynamic -I../../ -Werror -Wall -fsigned-char -fpic -fPIC -mfloat-abi=softfp -march=armv7-a -mfpu=neon -DNDEBUG -ffast-math -fomit-frame-pointer -O3 -pie -fPIE -DHAVE_NEON=1 -fno-strict-aliasing -Wno-unused-function -shared -c snowboy-detect-swig.cc -o snowboy-detect-swig.o
make: /ndk_install_32bit/bin/arm-linux-androideabi-g++: Command not found
make: *** [snowboy-detect-swig.o] Error 127

**Comment by chenguoguo** [comment]
Did you modify anything? See here `C Compiler (/ndk_install_32bit/bin/arm-linux-androideabi-gcc) is something wrong.`, the toolchain path is definitely wrong.

**Comment by VibrantVipin** [comment]
No, I didn't modify anything.
Now, what should I do?

**Comment by chenguoguo** [comment]
Most likely, `$(PWD)` is not working on your system. You can modify Makefile, and change `$(PWD)` to the absolute of your `swig/Android` directory.

**Comment by VibrantVipin** [comment]
Thanks, Now running fine.
Just one question, how can I change this to detect my personal wake word.
I had generated my model from the site now how can I change this code to detect my personal word?
