### ISSUE TITLE
Support for other people?

### ISSUE THREAD

**Issue by nomadic-squirrel** [Kitt-AI/snowboy#19]
So, the FAQ on this page:

Has this statement:
```
* My pmdl model works well for me, but does not work well for others
Models with suffix pmdl are personal models, and they are supposed to only work well for the person who provides the audio samples. If you are look for a model that works well for everyone, please use the universal model (with suffix umdl).
```

Which indicates to me that if I train my pmdl, then my girlfriend won't be able to initiate. I suppose I could pass multiple pmdl files to the `snowboydecoder.HotwordDetector` and use the same callback for each pmdl. But ideally, I'd be able to have each person generate a pmdl then pass that to the script. 

But then, if I have guests over, and I want to use a term different from "snowboy", could I do this? Is there any way through your api to generate an umdl?

**Comment by chenguoguo** [comment]
If you take a look at the example demo2.py, that shows how you can provide two hotword models, and you can follow the same procedure to provide more models. That will increase the computation though.

Regarding using a different term from "snowboy", yes you can provide whatever you want. Your friend and you don't have to use the same word/phrase.

Regarding the universal model, normally we control the training process. We do provide one universal model for "snowboy" (see https://github.com/Kitt-AI/snowboy/blob/master/resources/snowboy.umdl) for your use.

**Comment by chenguoguo** [comment]
Closing this as it looks like the issue has been resolved.

**Comment by nomadic-squirrel** [comment]
I also found that you can recruit others to get a universal model through kitt.ai. Now I just have to find 500 friends :)

**Comment by xuchen** [comment]
make sure you have a good variety across ages and gender so your model is
robust. ;-)

**Comment by duoduo999** [comment]
If I manage to get 1000 recordings uploaded, will I just automatically get a downloadable universal model then? Btw, is there a way of batch uploading audio files for training universal model?

**Comment by xuchen** [comment]
If you manage to get 500 people to record and upload to our library through
the *web interface*, yes, we'll train a universal model for you. However,
we don't provide a batch uploading function for this.

**Comment by donldmcc** [comment]
@xuchen Does it have to be through the "web interface" or can I use the API and ask people to record their voice?
When the universal model is created after 500 samples, can I use the umdl created in a commercial app?

**Comment by xuchen** [comment]
@donldmcc Only through the *web interface*, if you get 500 people we'll train a universal model which you can use for free

**Comment by VisionZQ** [comment]
@xuchen if I manage to get 500 people to record used to train a "hotword" detection, how long you will take to train a model?
