### ISSUE TITLE
Release 1.2.0 on npm

### ISSUE THREAD

**Issue by stianjensen** [Kitt-AI/snowboy#192]
I see 1.2.0 is tagged as a release on GitHub and mentions improved performance for detecting the hotword 'alexa'. Can this version be published on npm? Only 1.1.0 is available there still.

**Comment by chenguoguo** [comment]
That was my bad, I forgot to publish it after setting everything up. Please try it now.

Note that the Node wrapper has not been updated regarding the recently added C++ APIs.
