### ISSUE TITLE
Does snowboy record sound

### ISSUE THREAD

**Issue by dolanmiu** [Kitt-AI/snowboy#197]
long shot but,

Does snowboy record sound by any chance?

Is it possible to record a `.wav` file of what they have said after they said a hotword?

@bogdanabadi

**Comment by xuchen** [comment]
Yes Snowboy comes with VAD that gives you silence signal after talking stops, then you have save that buffer of audio to disk.

http://docs.kitt.ai/snowboy/#how-to-use-snowboy-s-vad-to-detect-voice-and-silence

Please use Issues to report bugs and use the forum to post questions.

**Comment by dolanmiu** [comment]
Could you give me some direction on where to find this buffer? Is it a property of the detector class?

**Comment by chenguoguo** [comment]
It requires some coding, but you can basically use this ringbuffer implementation (if you use Python): https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/snowboydecoder.py#L21

The idea is that you start putting data to your buffer when your hotword is triggered, and stop doing so after silence is detected.

You can also take a look at [Sonus](https://github.com/evancohen/sonus), it's written in Javascript but it has all the functionality to send data to ASR server after hotword detection.

**Comment by Mnark** [comment]
I achieved the same thing in principal, by having snowboy detect the hotword, and that event triggers the microphone to start recording. The 'trick' is that the computer thinks it has two microphones, to do this you need to make sure you connect using pulseaudio (which connects to the actual microphone via ALSA)
