### ISSUE TITLE
Noting that Nvidia TX1 is already supported

### ISSUE THREAD

**Issue by beeedy** [Kitt-AI/snowboy#199]
Just wanted to make note that the pre-packaged binary + python wrapper: 
- Pine 64 with Debian Jessie 8.5 (3.10.102) (Pine64)

works without modification on an Nvidia TX1 running Ubuntu 16.04, it could be beneficial if this was noted somewhere

**Comment by xuchen** [comment]
Thank you! I've updated the README according to your comment.

Any chance to try TX2?

**Comment by beeedy** [comment]
I currently do not have access to a TX2, but I believe both the TX1 and TX2 have the same main CPU architecture with the difference being that the TX2 has an additional co-processor that is Nvidia's custom Denver architecture alone with a bigger GPU.

**Comment by xuchen** [comment]
Got it, thanks for the update!
