### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by flooie** [Kitt-AI/snowboy#2]
make: python-config: Command not found
make: python-config: Command not found
g++  -I../../ -O3 -fPIC -std=c++0x -c snowboy-detect-swig.cc
snowboy-detect-swig.cc:154:21: fatal error: Python.h: No such file or directory
 # include <Python.h>
                     ^
compilation terminated.
Makefile:45: recipe for target 'snowboy-detect-swig.o' failed
make: *** [snowboy-detect-swig.o] Error 1

Any help figuring out what I'm doing wrong ?

**Comment by chenguoguo** [comment]
Looks like you do not have the command python-config. I use that command to locate the python dependencies. Try to install python-devel (perhaps it doesn't exist in old python versions?). Of course if you know where is your python dependency, you can modify the makefile directly.

Example for PYINC on my macbook:
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7

Example for PYLIBS on my macbook:
-L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation

Let me know if this helps.

**Comment by flooie** [comment]
working with a raspberry pi - for the alexa echo - can't seem to find the right install

**Comment by flooie** [comment]
So - one step closer - but 

g++ -I../../ -O3 -fPIC -std=c++0x  -shared snowboy-detect-swig.o \
../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/lib/python2.7/config-arm-linux-gnueabihf -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas -o _snowboydetect.so
../..//lib/ubuntu64/libsnowboy-detect.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:48: recipe for target '_snowboydetect.so' failed
make: *** [_snowboydetect.so] Error 1

getting this error- clearly it thinks I'm trying to run this on ubuntu instead of raspian jessie - Any idea how to fix this?

**Comment by chenguoguo** [comment]
I see you have closed the issue. Did you solve the problem? If yes could you post the problem and the solution as it can be helpful to others. Thanks!

If not, what was your OS?

**Comment by flooie** [comment]
Jessie - Also I just got it working with AlexaPi and its awesome - ill post my code soon over there.

**Comment by flooie** [comment]
I had the hardest time modifying some config files that changed between wheezy and jessie

**Comment by chenguoguo** [comment]
Great!

**Comment by xuchen** [comment]
The reason of this error is that we didn't provide a RPi library. We are working on it. Meanwhile, one can use a pre-compiled version:

https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.0.0.tar.bz2

I'll let know when we have the RPi version ready.

**Comment by xuchen** [comment]
Master branch is updated with added RPi library support if you want to compile your own. A binary version is also added:

https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.0.0.tar.bz2
