### ISSUE TITLE
C support ?

### ISSUE THREAD

**Issue by Andros987** [Kitt-AI/snowboy#20]
Hi, I have take a look on your project, it s working perfectly, but I have some problem to use it in a C application.
Apparently the library is in C at the start but the header file is only for c++ project (in the include folder).

And I have some problem to convert it, have you a C example too ?

**Comment by chenguoguo** [comment]
Hi, the library itself is written in C++. You can create a C wrapper for the class and use it in C programs though, it's pretty straightforward. You can, e.g., follow this post: https://www.teddy.ch/c++_library_in_c/

If you create such a wrapper, it will be great if you can submit a pull request for it to our devel branch. You can probably put it under examples/C/ directory.
