### ISSUE TITLE
Roadblocks to Window support?

### ISSUE THREAD

**Issue by 16alexanders** [Kitt-AI/snowboy#202]
Look, I hate Windows but we have a custom project that is dependent on Windows and I want to run snowboy natively without running a Linux VM in the background. I looked at all the dependencies and they all have Windows support? What specifically prevents Snowboy from running on Windows.

**Comment by xuchen** [comment]
It takes significant effort to support another system that's not used by most of our customers and not used in production. All of our customers so far use Snowboy in Linux/Android/iOS so we simply made a decision not to support Windows (even for development).

**Comment by 16alexanders** [comment]
Thanks
