### ISSUE TITLE
Raspberry PI Segmentation fault error 

### ISSUE THREAD

**Issue by SandTB** [Kitt-AI/snowboy#203]
Hi, I downloaded the pre-compiled python package of snowboy, but there is the `segmentation fault` problem, and i've read that is a problem of pre-compiled package, then i tried to git the project and compile it with swig, but it's impossible, for an other error:

`
/bin/sh: 1: swig: not found
expr: syntax error
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
make: swig: Command not found
Makefile:59: recipe for target 'snowboy-detect-swig.cc' failed
make: *** [snowboy-detect-swig.cc] Error 127
`

I installed swig3.0 package.
Can anyone give me the swig-compiled python package? Thanks in advance.

**Comment by xuchen** [comment]
If you are using an older version of Raspbian, the swig version will be too low. You'll need at least swig 3.0.10. It looks like that you don't have swig on your cmd path. or the swig cmd comes from `swig3.0` instead of `swig`. Either case I suggest that you download the latest http://www.swig.org/ and compile it yourself.

**Comment by SandTB** [comment]
Thanks for the answer, I've just installed swig and compiled snowboy, but the `segmentation fault` error persists. What can i do?
I've upgraded my raspbian.

**Comment by xuchen** [comment]
Can you describe where the seg fault happens and pastes output?

**Comment by SandTB** [comment]
After 12 detected commands, the output is this:

_mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
Listening... Press Ctrl+C to exit
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
Segmentation fault_

**Comment by xuchen** [comment]
I can't reproduce this. Did you make sure that your system still has RAM and disk space when running it?

**Comment by chenguoguo** [comment]
We've never seen errors like this, perhaps try something like: https://stackoverflow.com/questions/27634109/why-mmap-cannot-allocate-memory
