### ISSUE TITLE
Wake Word Detection During Callback

### ISSUE THREAD

**Issue by glennglennglenn** [Kitt-AI/snowboy#208]
I have the demo working to call a custom callback function I made. However, I haven't been able to figure out how to make the hotword detection work while the callback is running. Does anyone know how to do this?

**Comment by xuchen** [comment]
In your callback function, fork another process to run your long-running command and immediately return the callback function. Check out here:

https://docs.python.org/2/library/multiprocessing.html

Please use the forum for questions like this and use the issue tracker for bug reports.
