### ISSUE TITLE
Strange issue with locale.

### ISSUE THREAD

**Issue by TmpName** [Kitt-AI/snowboy#21]
First, big thx for your lib ^^.

But I have a strange bug, I can't understand, compiled on raspberry.
>>snowboy::SnowboyDetect detector(resource_filename, model_filename);
if (setlocale(LC_ALL, "fr_FR") == NULL) setlocale(LC_ALL, "fr_FR.utf8");

Works fine but
>>if (setlocale(LC_ALL, "fr_FR") == NULL) setlocale(LC_ALL, "fr_FR.utf8");
snowboy::SnowboyDetect detector(resource_filename, model_filename);

Give
>>ERROR (ConvertStringToFloat():snowboy-utils.cc:149) ConvertStringToFloat: only part of the string can be converted: 0.1
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (ConvertStringToFloat():snowboy-utils.cc:149) ConvertStringToFloat: only part of the string can be converted: 0.1
[stack trace: ]
./jarvis() [0x4431c]
./jarvis() [0x4495c]
./jarvis() [0x3a7a8]
./jarvis() [0x3ecf8]
./jarvis() [0x3f2d8]
./jarvis() [0x20284]
./jarvis() [0x1930c]
/lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x114) [0xb6a14294]

**Comment by chenguoguo** [comment]
Hi, internally we use std::stof to converts strings to floats, and use string::find_first_of to split strings using certain delimiter. If you change the locale before initialization, that may cause problems.

**Comment by TmpName** [comment]
Ok, thx, good to know ^^.
