### ISSUE TITLE
PS3 eye usb microphone gain level on pi B

### ISSUE THREAD

**Issue by willondubs** [Kitt-AI/snowboy#210]
Hi, thanks for the mention on the ps3 eye webcam. I just got one and it works but the record level is quite low and I was just wondering if you found a way to increase it on raspberry pi using alsa.

**Comment by chenguoguo** [comment]
It seems that the only option is `alsamixer`, have you played with that? It's possible that it cannot control ps3 eye recording volume...

**Comment by willondubs** [comment]
Yes, it returns Invalid Argument, possibly due to the special nature of the ps3 webcam. Even with the low recording level, it works great with snowboy and a few other tools. I also noticed that you provide a setting for audio gain. Does that use pulseaudio?

**Comment by chenguoguo** [comment]
No that is used internally in Snowboy.
