### ISSUE TITLE
Xubuntu 16.04 LTS linking error.

### ISSUE THREAD

**Issue by robin-read** [Kitt-AI/snowboy#22]
So I have Snowboy working nicely on Ubuntu 16.04 LTS, however when I try and run it on Xubtunu 16.04 via one of the demos, I get the error below. I haven't changed anything in your Make file, and installed Swig from source. Is the .a lib tied to 12.04 and 14.04?

`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import snowboydecoder
  File "/home/robin/projects/dyson_mm_demo/third_party/snowboy/examples/Python/snowboydecoder.py", line 11, in <module>
    import snowboydetect
  File "/home/robin/projects/dyson_mm_demo/third_party/snowboy/examples/Python/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/robin/projects/dyson_mm_demo/third_party/snowboy/examples/Python/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /home/robin/projects/dyson_mm_demo/third_party/snowboy/examples/Python/_snowboydetect.so: undefined symbol: _ZNK7snowboy13SnowboyDetect14GetSensitivityB5cxx11Ev
`

**Comment by chenguoguo** [comment]
Did you see any error messages when you do make under swig/Python?

Also, normally can you use libraries compiled on Ubuntu systems on Xubuntu systems? I haven't used Xubuntu myself, but the Snowboy C++ library was compiled for Ubuntu. Could that be the issue?

**Comment by robin-read** [comment]
No compile errors with SWIG, but swapping from g++ 5 to g++ 4.9 did the trick. Seems to be working now. :)

**Comment by chenguoguo** [comment]
OK thanks a lot for the solution. We'll keep this in mind. We haven't played with g++5 yet :-)
