### ISSUE TITLE
Error when building Android wrapper

### ISSUE THREAD

**Issue by sebastianpfluegelmeier** [Kitt-AI/snowboy#225]
when i tried to build the Android wrapper for snowboy i always got this error message:

swig -I../../ -c++ -java -package ai.kitt.snowboy -outdir \
  java/ai/kitt/snowboy/ -o snowboy-detect-swig.cc snowboy-detect-swig.i
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'java.swg'
snowboy-detect-swig.1:9: Error: Unable to find 'arrays_java.i'
snowboy-detect-swig.i:10: Error Unable to find 'std_string.i'
make : *** [snowboy-detect-swig.cc] Error 1

i tried to build it on Ubuntu 14.04 LTS in VMware and on the Linux Subsystem on Windows. The Error message was always the same.

**Comment by chenguoguo** [comment]
According to this:
http://www.swig.org/Release/README

Your swig installation probably went wrong. Please try to re-install swig, and make sure it's version 3.0.10 or above.

**Comment by sebastianpfluegelmeier** [comment]
I installed swig 3.0.12 and now i get this error:

**Comment by chenguoguo** [comment]
This is wired. You can probably try this:
https://stackoverflow.com/questions/11016499/error-jni-h-no-such-file-or-directory

**Comment by sebastianpfluegelmeier** [comment]
i tried it and it didn't help.

**Comment by chenguoguo** [comment]
What if you delete the directory `ndk_install_32bit/`, and run `make` again? Did you see any errors from there?

**Comment by sebastianpfluegelmeier** [comment]
didn't help either on the linux subsystem. but i tried again on Ubuntu on VMware with the correct swig version and it worked there so i'm good now.
