### ISSUE TITLE
Play audio after hotword detection?

### ISSUE THREAD

**Issue by chownsauce** [Kitt-AI/snowboy#228]
Is there a sample somewhere that shows how to play the audio that's detected after the hotword back? I'm testing using the arecord Python demo and am trying to figure out how to capture the rest of the audio up until silence to play it back. Is this possible?

**Comment by chenguoguo** [comment]
There's no concrete example for that. But Snowboy supports detection of silence, see here: http://docs.kitt.ai/snowboy/

So what you can do is, after your hotword is triggered, you buffer your audio until Snowboy thinks it's silence, and then play it back. Note that Snowboy's voice activity detection is not perfect.
