### ISSUE TITLE
Raspberry Pi Package

### ISSUE THREAD

**Issue by Vjp33** [Kitt-AI/snowboy#23]
Hey, i'm new to developing with python, and am having trouble installing package with provided binary. When i uncompress the Raspberry Pi binary provided on the site I don't see a setup.py to use to install the package. Am I just supposed to run the script through the folder? I usually just install packages through pip so please excuse me if this a very simple question.

**Comment by chenguoguo** [comment]
Hi, you don't have to install the package, so yes you can run demo.py directly. But you will have to set up your audio and install PyAudio first. Please follow our instructions on our documentation page: https://snowboy.kitt.ai/docs

**Comment by Vjp33** [comment]
Ok, that makes sense. I was able to get the audio running by following the tutorial. Thanks again for the quick response, and also for the great project.
