### ISSUE TITLE
buffer does not contain full wake word sound

### ISSUE THREAD

**Issue by ppisljar** [Kitt-AI/snowboy#230]
in node.js microphone example i can see this:

```
detector.on('hotword', function (index, hotword, buffer) { // Buffer arguments contains sound that triggered the event, for example, it could be written to a wav stream 
  console.log('hotword', index, hotword);
});
```

i was expecting buffer to contain full audio that triggered my hotword (so for example me saying 'hey google', however that seems not to be the case. I tried playing it out:

```
detector.on('hotword', function (index, hotword, buffer) { // Buffer arguments contains sound that triggered the event, for example, it could be written to a wav stream 
  speaker.write(buffer);
  console.log('hotword', index, hotword);
});
```

but seems it contains just the last chunk that was matched ?

actually what would be super useful here is the number of ms elapsed since the start of the audio that at the end triggered this hotword. This way i can pipe the microphone (next to piping it to snowboy) to a circular buffer. when the hotword triggers i can then know exactly what part of my buffer do i need to take.

The use case i am looking into is additional hotword verification on the cloud. (so instead of just sending what happened after the hotword to for example google assistant, i want to send the hotword as well, then cancel request to the assistant if the analyzed text does not start with 'hey google'

**Comment by chenguoguo** [comment]
Correct, for now it only buffers audio after the hotword triggers.

You suggestion is actually is on our TODO list. Since the two-phrase verification is now getting famous, we certainly would like to support that.

**Comment by ppisljar** [comment]
thanks for the fast response. i guess this issue can be closed (adding the buffer param description to the docs would be awesome! ;) )

**Comment by chenguoguo** [comment]
I just updated the comments regarding the buffer. Closing this. Thanks a lot for pointing it out!

**Comment by MexXxo** [comment]
Hi, I'm currently looking how to implement two-phrase verification. 
@chenguoguo is it worth to wait until retrieving the audio with the hotword is part of snowboy?
