### ISSUE TITLE
How to set `NumChannels` ?

### ISSUE THREAD

**Issue by Oliv4945** [Kitt-AI/snowboy#233]
Dear,

I am trying to use a Respeaker mic array which record in stereo (two channels) from Python. 
It is not the same issue than #118 (Matric Creator mic) as Respeaker mic array returns only one arecord endpoint.
So my question might be obvious but I am not able to figure it: I saw `detector.NumChannels()`, should I set NumChannels to 2, and how ?

**Comment by chenguoguo** [comment]
No you cannot set it. Snowboy only takes 1 channel for now. You can probably just send one of your channels to Snowboy.

**Comment by Oliv4945** [comment]
Ok thank you, I will deal with it but it might be nice to update documentation :-)

BTW, thank you for this project ! :+1:
