### ISSUE TITLE
HI!I recommend you to add this to the Doc.For anaconda users.

### ISSUE THREAD

**Issue by nofacer** [Kitt-AI/snowboy#242]
For some anaconda users , the command "python3-config --ldflags "may return "-lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation". As you can see, compared with common python , the path lacks something. So there will be an error when do the "make" operation. 
This can be solved by manually change the makefile PYLIB part like this : 
`PYLIBS := -L/Users/YOURNAME/anaconda3/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation `
Just add the lib path by yourself

**Comment by xuchen** [comment]
Great! I just added a comment in `swig/Python3/Makefile`. Thanks!
