### ISSUE TITLE
libsnowboy-detect.a: error adding symbols: File in wrong format - Ubuntu(arm64)

### ISSUE THREAD

**Issue by nunoki** [Kitt-AI/snowboy#244]
Hello.

Thanks for your solution.

I am integrating AVS into arm64 ubuntu 16.04 and using a specially made board without using raspberry pi.

Used the branch below.
https://github.com/rickybrent/alexa-avs-sample-app

However, I am encountering the following error.
I used ubuntu amd64 to run snowboy trigger normally in labtop. Is this not guaranteed to work on arm64?

========== Installing Companion Service ==========
========== Preparing External dependencies for Wake Word Agent ==========
mkdir: cannot create directory ‘/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/ext/include’: File exists
mkdir: cannot create directory ‘/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/ext/lib’: File exists
mkdir: cannot create directory ‘/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/ext/resources’: File exists
mkdir: cannot create directory ‘/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/tst/ext’: File exists
========== Compiling Wake Word Agent ==========
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src
Scanning dependencies of target wakeWordAgent
[ 21%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
[ 21%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
[ 21%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 28%] Linking CXX executable wakeWordAgent
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
../ext/lib/libsnowboy-detect.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:408: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/tst
Scanning dependencies of target wakeWordAgentTest
[  5%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o
[ 16%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
[ 16%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o
[ 22%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp.o
[ 27%] Linking CXX executable wakeWordAgentTest
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
../ext/lib/libsnowboy-detect.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgentTest.dir/build.make:512: recipe for target 'wakeWordAgentTest' failed
make[2]: *** [wakeWordAgentTest] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Thanks.

**Comment by nunoki** [comment]
fixed.

ubuntu@localhost:~/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai/snowboy/examples/C++$ vi demo.mk

[before]
SNOWBOYDETECTLIBFILE := $(TOPDIR)/lib/ubuntu64/libsnowboy-detect.a
[after]
SNOWBOYDETECTLIBFILE := $(TOPDIR)/lib/aarch64-ubuntu1604/libsnowboy-detect.a

**Comment by LinTechxyz** [comment]
I ran into the same issue when I used "make" to get the file "_snowboydetect.so"

../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/lib/python3.6/config-3.6m-aarch64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lm -ldl -lf77blas -lcblas -llapack -latlas -o _snowboydetect.so
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
../..//lib/ubuntu64/libsnowboy-detect.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:73: recipe for target '_snowboydetect.so' failed
make: *** [_snowboydetect.so] Error 1
 
How to solve this problem?

**Comment by Edohvin** [comment]
@LinTechxyz Were you able to solve it?
