### ISSUE TITLE
[aarch64-ubuntu1604] libwiringPi.so: undefined reference to `shm_open'

### ISSUE THREAD

**Issue by nunoki** [Kitt-AI/snowboy#245]
I am facing the following error in ubuntu 16.04 aarch64.
Plz help me.

========== Compiling Wake Word Agent ==========
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src
Scanning dependencies of target wakeWordAgent
[ 14%] Building CXX object CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o
[ 14%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
[ 21%] Building CXX object CMakeFiles/wakeWordAgent.dir/PortAudioWrapper.cpp.o
[ 28%] Linking CXX executable wakeWordAgent
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libwiringPi.so: undefined reference to `shm_open'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:408: recipe for target 'wakeWordAgent' failed
make[2]: *** [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/tst
Scanning dependencies of target wakeWordAgentTest
[  5%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/testKittAi.cpp.o
[ 16%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp.o
[ 16%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp.o
[ 22%] Building CXX object CMakeFiles/wakeWordAgentTest.dir/home/ubuntu/alexa-avs-sample-app/samples/wakeWordAgent/src/PortAudioWrapper.cpp.o
[ 27%] Linking CXX executable wakeWordAgentTest
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libwiringPi.so: undefined reference to `shm_open'
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgentTest.dir/build.make:512: recipe for target 'wakeWordAgentTest' failed
make[2]: *** [wakeWordAgentTest] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgentTest.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgentTest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chenguoguo** [comment]
If you are using the Alexa sample app, it's designed for raspberry pi, so it has libraries that are used on Pis, e.g., `libwiringPi.so`

**Comment by nunoki** [comment]
Thanks for update.

I want to use wakeworldagent on aarch64 ubuntu board other than raspberry PI. 
Can you guide me on how to ignore this?

**Comment by chenguoguo** [comment]
That part of the code is on Alexa sample app, so you may have to check with them at: https://github.com/alexa/alexa-avs-sample-app

**Comment by nunoki** [comment]
Dear Chenguoguo,

I fixed this issue today.
I used "-lrt" option. 

[CMakeLists.txt]
#target_link_libraries( wakeWordAgentTest ${CMAKE_THREAD_LIBS_INIT} )
target_link_libraries( wakeWordAgentTest ${CMAKE_THREAD_LIBS_INIT} -lrt)

**Comment by chenguoguo** [comment]
OK. Thanks for the update.
