### ISSUE TITLE
Error in make command

### ISSUE THREAD

**Issue by VibrantVipin** [Kitt-AI/snowboy#247]
Hi 
I am compiling this project on my Ubuntu14.04 running on VirtualBox. I have installed swig3.0.12 version and also installed gcc and g++.
When giving make command i am getting following error:

vipin@vipin-VirtualBox:~/Project/github/snowboy/swig/Android$ sudo make
[sudo] password for vipin: 
--2017-07-24 20:02:45--  https://dl.google.com/android/repository//android-ndk-r14b-linux-x86_64.zip
Resolving dl.google.com (dl.google.com)... 74.125.204.91, 74.125.204.93, 74.125.204.136, ...
Resolving dl.google.com (dl.google.com)... 74.125.204.91, 74.125.204.93, 74.125.204.136, ...
Connecting to dl.google.com (dl.google.com)|74.125.204.91|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /android/repository/android-ndk-r14b-linux-x86_64.zip [following]
--2017-07-24 20:02:46--  https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip
Reusing existing connection to dl.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 840626594 (802M) [application/zip]
Saving to: ‘android-ndk-r14b-linux-x86_64.zip’

100%[=====================================>] 84,06,26,594 2.20MB/s   in 3m 10s 

2017-07-24 20:05:56 (4.23 MB/s) - ‘android-ndk-r14b-linux-x86_64.zip’ saved [840626594/840626594]

HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=1
BUILD_NUM_CPUS=2
## COMMAND: python ./android-ndk-r14b/build/tools/make_standalone_toolchain.py --arch arm --api 14 --stl gnustl --install-dir=/home/vipin/Project/github/snowboy/swig/Android/ndk_install_32bit
Toolchain installed to /home/vipin/Project/github/snowboy/swig/Android/ndk_install_32bit.
Cloning into 'OpenBLAS-Android-ARM32'...
remote: Counting objects: 29166, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 29166 (delta 31), reused 35 (delta 13), pack-reused 29110
Receiving objects: 100% (29166/29166), 20.53 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (22856/22856), done.
Checking connectivity... done.
Branch arm_soft_fp_abi set up to track remote branch arm_soft_fp_abi from origin.
Switched to a new branch 'arm_soft_fp_abi'
HEAD is now at b5c96fc Support ARM SOFTFP ABI for saxpy, sdot, snrm2, sscal, sgemv, sger.
C Compiler (/ndk_install_32bit/bin/arm-linux-androideabi-gcc) is something wrong.
1 at ./c_check line 29.
make[1]: *** [config.h] Error 2
make[1]: Entering directory `/home/vipin/Project/github/snowboy/swig/Android/OpenBLAS-Android-ARM32'
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:925: Makefile.: No such file or directory
make[1]: *** No rule to make target `Makefile.'.  Stop.
make[1]: Leaving directory `/home/vipin/Project/github/snowboy/swig/Android/OpenBLAS-Android-ARM32'
make: [OpenBLAS-Android-ARM32/install/lib/libopenblas.a] Error 1 (ignored)
swig -I../../ -c++ -java -package ai.kitt.snowboy -outdir \
  java/ai/kitt/snowboy/ -o snowboy-detect-swig.cc snowboy-detect-swig.i
/ndk_install_32bit/bin/arm-linux-androideabi-g++ -O3 --sysroot=/ndk_install_32bit/sysroot -std=c++0x -rdynamic -I../../ -Werror -Wall -fsigned-char -fpic -fPIC -mfloat-abi=softfp -march=armv7-a -mfpu=neon -DNDEBUG -ffast-math -fomit-frame-pointer -O3 -pie -fPIE -DHAVE_NEON=1 -fno-strict-aliasing -Wno-unused-function -shared -c snowboy-detect-swig.cc -o snowboy-detect-swig.o
make: /ndk_install_32bit/bin/arm-linux-androideabi-g++: Command not found
make: *** [snowboy-detect-swig.o] Error 127

**Comment by VibrantVipin** [comment]
Hi 
Resolved the issue. My $(PWD) is not working on my system. Modified Makefile, and change $(PWD) to the absolute of your swig/Android directory.

Thanks Guoguo Chen

**Comment by chenguoguo** [comment]
Oh you posted on our forum as well :-)

I did remember answering this question, and was wondering why I didn't see my answer here lol
