### ISSUE TITLE
Installing snowboy issues ! 

### ISSUE THREAD

**Issue by Seeyko** [Kitt-AI/snowboy#252]
Hello !

I try to install snowboy today in order to use it in python 3. But i can't figure out how to get it...
Here all of what i have on my computer (Ubuntu 16.04) :
- Python 3.6
- SWIG Version 3.0.12
i have run the following command from your website :
sudo apt-get install swig3.0 python-pyaudio python3-pyaudio sox
pip install pyaudio

Then install the `atlas` matrix computing library:

sudo apt-get install libatlas-base-dev

But here i don't know what to do next... you tell us to cd swig/Python but i didn't have those directories in my pc...

Then i try to do "pip install snowboy" but here the error i get :

https://pastebin.com/KtJpLwAt

I really want to use snowboy in my project because it's really good and it's work offline !

Thanks for your help and the big work on snowboy !

**Comment by xuchen** [comment]
Maybe follow the full docs here:

http://docs.kitt.ai/snowboy/

In a nutshell, if you want to use Snowboy with Python, you should first enter `swig/Python`, and `make` there, then go to `examples/Python` to try the demos.

**Comment by Seeyko** [comment]
I follow the docs but not use to GNU/linux system...

I don't understand what to do with swig/Python... 

I download pre-packaged Snowboy binaries and his Python wrappers for ubuntu 16.04 but then i don't know what to do with this files... Normally i use pip to install librairies for python but this don't work with snowboy :/ 

i try to do python demo.py snowboy.umdl but it's doesn't work too...

**Comment by xuchen** [comment]
Could you paste your error messages?

**Comment by Seeyko** [comment]
this is the error that i get :

tom@tom-MS-7A68:~/Bureau/snowboy/swig/Python$ make
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
g++ -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7  -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x  -shared snowboy-detect-swig.o \
	../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpthread -ldl  -lutil -lm  -lpython2.7 -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas -o _snowboydetect.so
/usr/bin/ld : ne peut trouver -lf77blas
/usr/bin/ld : ne peut trouver -lcblas
/usr/bin/ld : ne peut trouver -llapack_atlas
/usr/bin/ld : ne peut trouver -latlas
collect2: error: ld returned 1 exit status
make: *** [_snowboydetect.so] Erreur 1

**Comment by xuchen** [comment]
`libatlas-base-dev` wasn't installed properly. can you double check?

**Comment by Seeyko** [comment]
so know i get this error on ubuntu 14.04... : 
python demo.py snowboy.umdl ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot lock down 82274202 byte memory area (Cannot allocate memory)
Listening... Press Ctrl+C to exit
^C

The ^C at the end is when i press Ctrl +C, nothing append, i cannot close the terminal or the demo, and the word detection doesn't work at all...

I don't understand why the programm want  82274202 byte, it's seems alot no ?
and for the first line it's seems that it's my audio who don't work, i have a bird UM1 microphone plug in usb and it's works perfectly  when i do rec temp.wav.
And my headphone are plug in my pc screen because i have broke the output jack of my actual pc... But it's work great, the sounds came from my screen and when i plug my headphones, the sound came from my headphone.

I don't have any idea what i can do here :/

**Comment by Seeyko** [comment]
i don't know why i have jack2d on my pc who "control" sound device or i don't know what bu if stop jack-control and redo python demo.py snowboy.umdl 
i got this error : 

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

and then i do jack-control start and i got the first error that i have past "(Cannot lock down 822... byte memory area..)"

So it's seems that jack control completely messed up with pyAudio and my pc if i understand...

**Comment by Seeyko** [comment]
Hey,

So i install ubuntu 14.04 on an old pc that i have and i got the demo.py work but with the same error of the jack server, but here it's work i cannot close the programm with Ctrl + C but the hotword detection work so i'm going to learn further and try to do nice things with these ! 
Thanks for the help, bye ! 

#Closed

**Comment by Adity-dev** [comment]
I am getting the following error, installing on Windows 10 64bit python-3 Anaconda Package


PS C:\Users\adity\Desktop\AI_files\snowboy\snowboy-master> python setup.py build
running build
Compiling snowboy...
make: python3-config: Command not found
make: python3-config: Command not found
g++  -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
snowboy-detect-swig.cc:176:21: fatal error: Python.h: No such file or directory

                     ^
compilation terminated.
make: *** [Makefile:70: snowboy-detect-swig.o] Error 1
error: can't copy 'swig\Python3\_snowboydetect.so': doesn't exist or not a regular file


help me

**Comment by chenguoguo** [comment]
We don't support Windows...
