### ISSUE TITLE
undefined symbol : cblas_snrm2

### ISSUE THREAD

**Issue by Mnib** [Kitt-AI/snowboy#255]
Hello, I'm trying to use snowboy with the kalliope project. However, I have the following error : 
_snowboydetect.so: undefined symbol: cblas_snrm2

When I ldd : 
linux-vdso.so.1 (0x00007ffff89f8000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f0f2a6be000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0f2a4a1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0f2a19d000)
	libcblas.so.3 => /usr/lib/x86_64-linux-gnu/libcblas.so.3 (0x00007f0f29f40000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0f29bbe000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0f299a5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0f29606000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0f293ec000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0f291e8000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0f28fe5000)
	/lib64/ld-linux-x86-64.so.2 (0x00005605e9237000)
	libf2c.so.2 => /usr/lib/x86_64-linux-gnu/libf2c.so.2 (0x00007f0f28dc8000)
undefined symbol: cblas_snrm2	(./_snowboydetect.so)
undefined symbol: cblas_sdot	(./_snowboydetect.so)
undefined symbol: cblas_sgemm	(./_snowboydetect.so)
undefined symbol: cblas_sgemv	(./_snowboydetect.so)
undefined symbol: cblas_sscal	(./_snowboydetect.so)
undefined symbol: cblas_sger	(./_snowboydetect.so)
undefined symbol: cblas_saxpy	(./_snowboydetect.so)

I installed libatlas-base-dev, which seemed to be the issue for a number of users...

I really don't know what is happening here.
I'm on Debian 9 x86_64,

Thank you in advance

Bastien

**Comment by chenguoguo** [comment]
Did you install atlas?

**Comment by mabeltron** [comment]
I have this problem with Ubuntu 17.04. Fairly certain I have installed all dependencies (although a list would be very useful) and it occurs with both the 14.04 binary and the Python3 wrapper generated by swig. My guess is that those symbols aren't available in recent releases of Ubuntu and Debian.

**Comment by chenguoguo** [comment]
Could you give the absolute path to your atlas libraries? And what libraries you have under that path?

**Comment by mabeltron** [comment]
The libraries are installed in /usr/lib/atlas-base with a symlink to /usr/lib:

```
  4482364      0 lrwxrwxrwx   1 root     root           15 Aug  8  2016 /usr/lib/atlas-base/libatlas.so.3 -> libatlas.so.3.0
  4482409      0 lrwxrwxrwx   1 root     root           13 Aug  8  2016 /usr/lib/atlas-base/libatlas.so -> libatlas.so.3
  4482352   3680 -rw-r--r--   1 root     root      3766952 Aug  8  2016 /usr/lib/atlas-base/libatlas.so.3.0
  4482400   7480 -rw-r--r--   1 root     root      7659050 Aug  8  2016 /usr/lib/atlas-base/libatlas.a
  2896125      4 drwxr-xr-x   2 root     root         4096 Nov 12 03:06 /usr/lib/libatlas-test
  2892631      0 lrwxrwxrwx   1 root     root           24 Aug  8  2016 /usr/lib/libatlas.so.3 -> atlas-base/libatlas.so.3
  2892853      0 lrwxrwxrwx   1 root     root           22 Aug  8  2016 /usr/lib/libatlas.so -> atlas-base/libatlas.so
  2892851      0 lrwxrwxrwx   1 root     root           21 Aug  8  2016 /usr/lib/libatlas.a -> atlas-base/libatlas.a
`
The contents of /usr/lib/atlas-base are:

`drwxr-xr-x 2 root root    4096 Nov 11 20:21 atlas
-rw-r--r-- 1 root root 7659050 Aug  8  2016 libatlas.a
lrwxrwxrwx 1 root root      13 Aug  8  2016 libatlas.so -> libatlas.so.3
lrwxrwxrwx 1 root root      15 Aug  8  2016 libatlas.so.3 -> libatlas.so.3.0
-rw-r--r-- 1 root root 3766952 Aug  8  2016 libatlas.so.3.0
-rw-r--r-- 1 root root  470708 Aug  8  2016 libcblas.a
lrwxrwxrwx 1 root root      13 Aug  8  2016 libcblas.so -> libcblas.so.3
lrwxrwxrwx 1 root root      15 Aug  8  2016 libcblas.so.3 -> libcblas.so.3.0
-rw-r--r-- 1 root root  137760 Aug  8  2016 libcblas.so.3.0
-rw-r--r-- 1 root root  539144 Aug  8  2016 libf77blas.a
lrwxrwxrwx 1 root root      15 Aug  8  2016 libf77blas.so -> libf77blas.so.3
lrwxrwxrwx 1 root root      17 Aug  8  2016 libf77blas.so.3 -> libf77blas.so.3.0
-rw-r--r-- 1 root root  134688 Aug  8  2016 libf77blas.so.3.0
-rw-r--r-- 1 root root 1069700 Aug  8  2016 liblapack_atlas.a
lrwxrwxrwx 1 root root      20 Aug  8  2016 liblapack_atlas.so -> liblapack_atlas.so.3
lrwxrwxrwx 1 root root      22 Aug  8  2016 liblapack_atlas.so.3 -> liblapack_atlas.so.3.0
-rw-r--r-- 1 root root  381272 Aug  8  2016 liblapack_atlas.so.3.0
`

**Comment by chenguoguo** [comment]
What is you change this line: https://github.com/Kitt-AI/snowboy/blob/master/swig/Python/Makefile#L43

from 
`LDLIBS := -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas`
to
`LDLIBS := -lm -ldl /usr/lib/atlas-base/libf77blas.a /usr/lib/atlas-base/libcblas.a /usr/lib/atlas-base/liblapack_atlas.a /usr/lib/atlas-base/libatlas.a`

Please check those libraries, I'm sure functions like `cblas_snrm2` are defined in those libraries.

**Comment by mabeltron** [comment]
That worked, although you end up with a static binary which is bigger than with dynamic linking. It would suggest that something in the compilation process has trouble following symlinked libraries (and that was something I wasn't even aware happened) so I will investigate a bit.

**Comment by chenguoguo** [comment]
Most likely the atlas installation process went wrong somehow, and your shared library was not correctly added to the path.

You can compile with the shared library too, giving that you correctly set up the path.

**Comment by mabeltron** [comment]
Standard installation using apt as far as I can see but I'll have a look at that as well.
