### ISSUE TITLE
IOError: [Errno Invalid input device (no default output device)] -9996

### ISSUE THREAD

**Issue by devilmind** [Kitt-AI/snowboy#257]
Hello everyone,
I'm trying to configure snowboy on my rpi3 to replace the "OK Google" hotword.
After configuration I'm running before the google assistant and soon after snowboy command.

I obtain this issue:

```
Traceback (most recent call last):
  File "/home/pi/snowboy/wakeword.py", line 26, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/snowboy/snowboydecoder.py", line 116, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid input device (no default output device)] -9996
```

if I launch it without launch google assistant first, snowboy is running fine and the hotword is detected fine.

Can you help me to fix this pls?

**Comment by devilmind** [comment]
Fixed changing the audio configuration

**Comment by adidoes** [comment]
Changing the audio configuration how? I get this error too.

**Comment by TomWerner** [comment]
For future searchers, I found https://github.com/shivasiddharth/GassistPi/blob/a47a02231aa23af9d53a004bbec1f474ca18fec2/audio-drivers/USB-MIC-HDMI/scripts/asound.conf to be almost exactly what I wanted. I just needed to change the hw numbers.

**Comment by chenguoguo** [comment]
Great! @TomWerner 

Or follow here: http://docs.kitt.ai/snowboy/#set-up-audio
