### ISSUE TITLE
Can't get past "Test the model" stage on the website

### ISSUE THREAD

**Issue by brummieb** [Kitt-AI/snowboy#260]
I have a Raspberry Pi with a Matrix creator, and I've successfully got snowboy working with the standard snowboy.udml file. I now want to create my own wakeword, so I've recorded it three times, obtained those files from the Pi, and uploaded them (from my PC) to the New Hotword feature on the website.

I'm now at the "Test the model" step, but I don't seem to be able to proceed. If I click "Run the test" nothing happens. Is it waiting for me to say the wakeword before I'm allowed to save and download the file? If so, that's not going to work - as I'm doing this from my PC not the Pi (so even if I had a mic on the PC it wouldn't be the same mic as the Pi).

Have I misunderstood how to use this interface?

**Comment by chenguoguo** [comment]
Yes you have to "pass" the test before you can download the model.

It should work even if you have this microphone mismatch. Mismatched microphone will have worse performance but it doesn't mean that it won't work. You can increase the sensitivity at the test stage if it doesn't work well.

The other thing is that when you upload the audio files to the website, make sure the audio files are in the right format: single channel, 16 bit signed integer, 16000k sampling rate.

**Comment by brummieb** [comment]
Many thanks. I don't have a mic for the PC so that's a show stopper. However, I've used the REST API directly from the Pi to upload files and download a model and that's working well.
