### ISSUE TITLE
能不能搞个中文文档？照顾下中国同胞？

### ISSUE THREAD

**Issue by yanwuguangjun** [Kitt-AI/snowboy#261]
能不能搞个中文文档？照顾下中国同胞？中国内部本来信息就堵塞，你们还没英文文档，中国开发这学习成本增加，ai研发进度也自然慢了。

**Comment by chenguoguo** [comment]
好的，会加入计划，多谢提醒。

**Comment by chenguoguo** [comment]
加入了中文文档，欢迎提交Pull Request更新：

https://github.com/Kitt-AI/snowboy/blob/master/README_ZH_CN.md
