### ISSUE TITLE
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Andy1314Chen** [Kitt-AI/snowboy#262]
Raspberry pi3.
just follow the docs, but i got the error.

**Comment by Andy1314Chen** [comment]
I downloaded the pre-packaged Snowboy binaries and their Python wrappers from [https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.1.1.tar.bz2](https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.1.1.tar.bz2) (for Raspberry Pi with Raspbian 8.0, all versions (1/2/3/Zero)). I run the demo.py with Python2, it's OK. However , with the Python3 , I got the Error.

> Import Error: dynamic module does not define init function (PyInit__snowboydetect)

So, I google it , but i failed. They all talked about 'swig version', 'make',etc.

**Comment by chenguoguo** [comment]
First of all, for libf77blas.so.3, you have to install ATLAS, something like `sudo apt-get install libatlas-base-dev`

Then, for Python3, you cannot use the pre-compiled version. Please use our github repository and use `https://github.com/Kitt-AI/snowboy/tree/master/swig/Python3` and `https://github.com/Kitt-AI/snowboy/tree/master/examples/Python3`.

**Comment by Flowdeeps** [comment]
Andy's comment totally fixed my issue. With the older v1 AIY Pi kit and the image from 2017 you have to specify python2 and not python as it appears that python3 is the system default.

**Comment by tall-josh** [comment]
Thanks @chenguoguo,
I just got TF1.8 with Python3.5 on a fresh install of Raspbian9.0. Thankfully, all I needed was the `libatlas-base-dev`.

So.
```
sudo apt-get install python3-pip python3-dev
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.8.0/tensorflow-1.8.0-cp35-none-linux_armv7l.whl
sudo pip3 install /tensorflow-1.8.0-cp35-none-linux_armv7l.whl
sudo apt-get install libatlas-base-dev
```

**Comment by jshep321** [comment]
> 
> 
> Thanks @chenguoguo,
> I just got TF1.8 with Python3.5 on a fresh install of Raspbian9.0. Thankfully, all I needed was the `libatlas-base-dev`.
> 
> So.
> 
> ```
> sudo apt-get install python3-pip python3-dev
> wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.8.0/tensorflow-1.8.0-cp35-none-linux_armv7l.whl
> sudo pip3 install /tensorflow-1.8.0-cp35-none-linux_armv7l.whl
> sudo apt-get install libatlas-base-dev
> ```

for us copy/pasters:  need the ./ instead of just / in line 3:
sudo apt-get install python3-pip python3-dev
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.8.0/tensorflow-1.8.0-cp35-none-linux_armv7l.whl
sudo pip3 install ./tensorflow-1.8.0-cp35-none-linux_armv7l.whl
sudo apt-get install libatlas-base-dev

**Comment by clonbg** [comment]
sudo apt-get install libatlas-base-dev

Thanks¡¡¡¡

**Comment by krizmo1992** [comment]
I just used the following and it fixed the issue. 
sudo ln -s /usr/lib/libf77blas.so.3 /usr/lib/libf77blas.so.3gf

**Comment by fabianmendes** [comment]
> I just used the following and it fixed the issue.
> sudo ln -s /usr/lib/libf77blas.so.3 /usr/lib/libf77blas.so.3gf

Just this one helped me. Thanks
