### ISSUE TITLE
AVS build error

### ISSUE THREAD

**Issue by nunokid** [Kitt-AI/snowboy#269]
I want to run AVS on aarch64 linux board.
https://github.com/alexa/avs-device-sdk

My cmake command is below.

#cmake $SDK_SRC -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/sources/snowboy/lib/aarch64-ubuntu1604/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/ubuntu/sources/snowboy/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$LOCAL_BUILD/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=$LOCAL_BUILD/include -DCMAKE_PREFIX_PATH=$LOCAL_BUILD -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD

#sudo make

I met below error.

[ 68%] Linking CXX executable KittAiKeyWordDetectorTest
 ../src/libKITTAI.so: undefined reference to  snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' ../src/libKITTAI.so: undefined reference to snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)'
 collect2: error: ld returned 1 exit status
 KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/build.make:102: recipe for target 'KWD/KittAi/test/KittAiKeyWordDetectorTest' failed
 make[2]: *** [KWD/KittAi/test/KittAiKeyWordDetectorTest] Error 1
 CMakeFiles/Makefile2:4045: recipe for target 'KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all' failed
 make[1]: *** [KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all] Error 2
 Makefile:138: recipe for target 'all' failed
 make: *** [all] Error 2

**Comment by nunokid** [comment]
I have resolved this issue by changing the default gcc version.

$ sudo apt-get install gcc-4.8

$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60
 $ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 60

Thanks All.

**Comment by sam-blinkdigital** [comment]
@nunokid I have tried your solution but still not able to make it work.

`[ 93%] Linking CXX executable SampleApp
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:355: recipe for target 'SampleApp/src/SampleApp' failed
make[3]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:6645: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
CMakeFiles/Makefile2:6657: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:1746: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2
`
I am doing this on following system
 - Raspbian Stretch

**Comment by cogmeta** [comment]
Anybody found for a fix for this?

**Comment by chenguoguo** [comment]
@cogmeta could you try this library https://github.com/Kitt-AI/snowboy/tree/master/lib/ubuntu64 and Snowboy demo alone on your system and see if that works?

**Comment by cogmeta** [comment]
I added  -D_GLIBCXX_USE_CXX11_ABI=0 -pg to CXXFLAG. That fixed it

**Comment by chenguoguo** [comment]
Great! It's interesting though, because if `-D_GLIBCXX_USE_CXX11_ABI=0 -pg` works, then using g++ 4.9 or below should already have worked...

**Comment by cogmeta** [comment]
Adding -D_GLIBCXX_USE_CXX11_ABI=0 (or hanging gcc version) is not longer a fix as it is affecting other libraries in our project (GRPC and protobuf). Is there a permanent fix to this issue? Please.

**Comment by chenguoguo** [comment]
Adding a wrapper should do the job: https://github.com/Kitt-AI/snowboy/issues/99

We will consider upgrading to 5.x.x for the next release.
