### ISSUE TITLE
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by nunokid** [Kitt-AI/snowboy#272]
I did snowboy python demo(demo.py).
Trigger works fine but with the "ding" sound, the following message is generated.
The detect "ding" sound is intermittently heard.

INFO:snowboy:Keyword 1 detected at time: 2017-09-06 05:20:59
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
INFO:snowboy:Keyword 1 detected at time: 2017-09-06 05:21:08
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred

**Comment by chenguoguo** [comment]
ALSA usually spits out wired warning/error messages. I don't really know how to get rid of all those.

**Comment by nunokid** [comment]
Thanks
