### ISSUE TITLE
Clarify licensing - add LICENSE file and header in source files

### ISSUE THREAD

**Issue by arjenlentz** [Kitt-AI/snowboy#289]
The README.md is currently ambiguous in terms of licensing.
It notes "Apache licensed!" but that's not reflected in the source files which merely contain a copyright.
Elsewhere in README.md there are specific requirements regarding commercial and non-commercial use.

I think it's important to clarify the licensing, so people know where they're at.
Apache license (mentioned in the README.md) sounds like a fine idea.
Of course it's up to the original author to decide, but since the code is up on GitHub I think the key is to make it clear what the license is.
thanks

**Comment by chenguoguo** [comment]
For all the example code and the wrapper code, those are all under Apache license.

For Snowboy models, you'll have to get a commercial license if you want to use then commercially.

**Comment by arjenlentz** [comment]
It is common practice to select a LICENSE in Github, so that it's clear to people what the licensing situation is - and to identify the applicable license text at the top of each source file.

**Comment by BillWSY** [comment]
We have a ROS (ros.org) package for snowboy, but without a clear LICENSE I can't open-source it. It will be great if you can follow the standards and declare your license.

**Comment by chenguoguo** [comment]
What license are you targeting for ROS? @BillWSY

**Comment by BillWSY** [comment]
We prefer BSD, but Apache also works.

The problem is, we will be redistributing your common.res, libsnowboy-detect.a, snowboy-detect.h, snowboy.umdl, and we can't do so unless you have a clear statement showing that we can redistribute them (e.g. section 4 in Apache license 2.0).

**Comment by chenguoguo** [comment]
OK I created a license (Apache 2.0) that governs the source code, the libraries, the resource files and the snowboy.umdl model file provided in this repository.

All other model files are subject to their own licenses.

**Comment by BillWSY** [comment]
Thanks.

**Comment by syl22-00** [comment]
I don't think your licensing terms do make sense as they are. Your `LICENSE` file and your online docs (http://docs.kitt.ai/snowboy/) claim that "Snowboy is Apached licensed" but you do not provide the source code of it, only pre-built binaries.
Also your home page states that the library is free for non-commercial use only, which contradicts the Apache license.
I guess you could just make things clear that the swig wrappers and the code samples are under Apache license, and provide clearer EULA for your binaries.
