### ISSUE TITLE
No SENSITIVITY at line 28 in KittAiSnowboyWakeWordEngine.cpp

### ISSUE THREAD

**Issue by xilopaint** [Kitt-AI/snowboy#297]
I don't understand the instructions on README. I can't see SENSITIVITY at line 28 and APPLY_FRONTEND is not at line 30, but 29.

What am I missing?

![screen shot 2017-10-20 at 21 17 37](https://user-images.githubusercontent.com/11052366/31846008-6e734bb6-b5dc-11e7-9bed-a1c66267b24f.png)

**Comment by chenguoguo** [comment]
They have updated the code. You can add one more line after line 107:
https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp#L107

`m_detector->SetSensitivity(YOUR_SENSITIVITY);`

**Comment by alvihabib** [comment]
Just remember to declare `YOUR_SENSITIVITY` as a `std::string` after line 27, or else it will complain that float or double can't be converted to a string when you run `make`.
