### ISSUE TITLE
Error when starting any app?

### ISSUE THREAD

**Issue by tomgie** [Kitt-AI/snowboy#30]
I get this error on Ubuntu 14.04 any time I try to start any python program.

http://pastebin.com/ZRaf2Guc

**Comment by xuchen** [comment]
Does it work for you with `rec tmp.wav` and `play tmp.wav`? those are simple ways to determine whether ALSA is set up properly

**Comment by chenguoguo** [comment]
Any updates @tomgie ? Please also let us know if you figured it out by yourself. Your solution might be helpful to others.

**Comment by tomgie** [comment]
I just figured out if you ignore this error it works fine. But still should look into it.
