### ISSUE TITLE
eorror: snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>.......

### ISSUE THREAD

**Issue by rustihammer** [Kitt-AI/snowboy#305]
Dear KITTAI team,

I'm trying to cross-build avs-device-sdk(https://github.com/alexa/avs-device-sdk) , however I'm having the below issue at linking the libKITTAI.so for SampleApp.  I saw in issues list someone sets _GLIBCXX_USE_CXX11_ABI 0 to solve the issue.  I tried the same but it doesn't solve the issue.  Do you have a recommendation how to solve this issue?

The Yocto Linux BSP for this platform doesn't allow to download compiler to 4.8

evkit: i.MX6ULL
Yocto Linux
gcc 5.3

my arm toolchain g++ version
```
$ imx6ull_yocto/build-imx6ull-x11/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ --version
arm-poky-linux-gnueabi-g++ (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

cmake configuration flags:
```
cmake -DCMAKE_TOOLCHAIN_FILE=~/toolchain.cmake $SDK_SRC -DSENSORY_KEY_WORD_DETECTOR=OFF -DKITTAI_KEY_WORD_DETECTOR=ON \
    -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$LOCAL_BUILD_ARM/lib/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$LOCAL_BUILD_ARM/include \
    -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=$LOCAL_BUILD_ARM -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$LOCAL_BUILD_ARM/lib/libportaudio.a \
    -DPORTAUDIO_INCLUDE_DIR=$LOCAL_BUILD_ARM/include -DCMAKE_PREFIX_PATH=$LOCAL_BUILD_ARM -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD_ARM \
    -DCMAKE_BUILD_TYPE=DEBUG -Wno-dev -DACSDK_EXCLUDE_TEST_FROM_ALL=ON -D_GLIBCXX_USE_CXX11_ABI=0
```

compilation error:
```
$ make
[ 37%] Built target AVSCommon
[ 44%] Built target ACL
[ 44%] Built target AuthDelegate
[ 46%] Built target ExampleAuthDelegateClient
[ 51%] Built target ADSL
[ 53%] Built target AFML
[ 55%] Built target SQLiteStorage
[ 57%] Built target CertifiedSender
[ 57%] Built target ContextManager
[ 60%] Built target PlaylistParser
[ 66%] Built target MediaPlayer
[ 68%] Built target KWD
[ 68%] Built target KITTAI
[ 71%] Built target AIP
[ 77%] Built target Alerts
[ 77%] Built target AudioPlayer
[ 80%] Built target PlaybackController
[ 80%] Built target SpeakerManager
[ 82%] Built target SpeechSynthesizer
[ 84%] Built target Settings
[ 86%] Built target AVSSystem
[ 88%] Built target TemplateRuntime
[ 91%] Built target DefaultClient
[ 93%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/main.cpp.o
[ 93%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o
[ 93%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/InteractionManager.cpp.o
[ 95%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/UserInputManager.cpp.o
[ 95%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/ConsolePrinter.cpp.o
[ 95%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/GuiRenderer.cpp.o
[ 97%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/UIManager.cpp.o
[ 97%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/KeywordObserver.cpp.o
[ 97%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/ConnectionObserver.cpp.o
[100%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/SampleApplication.cpp.o
[100%] Linking CXX executable SampleApp
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:353: recipe for target 'SampleApp/src/SampleApp' failed
make[2]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:6140: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
Do you have a library for gcc 5?

**Comment by chesterkuo** [comment]
Hi @chenguoguo 

I got similar issue on x86_64 platform, have item (1) didn't have , and the library i download seems for x86_64 also.


[ 97%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/SampleApplication.cpp.o
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Linking CXX executable SampleApp
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:353: recipe for target 'SampleApp/src/SampleApp' failed
make[3]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:6450: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
CMakeFiles/Makefile2:6462: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:1707: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2

chester@chester-nuc1:/sda/avs-device-kitt-ai-build$ cat ../build-avs-kitt-ai-git.sh
cmake /sda/avs-device-git/avs-device-sdk -D_GLIBCXX_USE_CXX11_ABI=0 -DCMAKE_BUILD_TYPE=RELEASE -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/sda/KTTI-AI-lib/ubuntu64/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/sda/KTTI-AI-lib -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/usr/local/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/usr/local/include -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=/usr/local/lib -DCURL_LIBRARY=/usr/local/lib/libcurl.so -DCURL_INCLUDE_DIR=/usr/local/include/ -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_INSTALL_PREFIX=/usr/local




chester@chester-nuc1:/sda/avs-device-kitt-ai-build$ uname -a
Linux chester-nuc1 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
chester@chester-nuc1:/sda/avs-device-kitt-ai-build$


chester@chester-nuc1:/sda/avs-device-kitt-ai-build$ objdump -a /sda/KTTI-AI-lib/ubuntu64/libsnowboy-detect.a
In archive /sda/KTTI-AI-lib/ubuntu64/libsnowboy-detect.a:

audio-lib.o:     file format elf64-x86-64
rw-rw-r-- 1000/1000  11448 Mar 25 07:59 2017 audio-lib.o


wave-audio.o:     file format elf64-x86-64
rw-rw-r-- 1000/1000  32840 Mar 25 07:59 2017 wave-audio.o


gain-control-stream.o:     file format elf64-x86-64
rw-rw-r-- 1000/1000  15336 Mar 25 07:59 2017 gain-control-stream.o


vqe-stream.o:     file format elf64-x86-64
rw-rw-r-- 1000/1000    943 Mar 25 07:59 2017 vqe-stream.o


afe-stream.o:     file format elf64-x86-64
rw-rw-r-- 1000/1000    943 Mar 25 07:59 2017 afe-stream.o

**Comment by chesterkuo** [comment]
BTW, here is library i download.

https://github.com/Kitt-AI/snowboy/blob/master/lib/ubuntu64/libsnowboy-detect.a

**Comment by chenguoguo** [comment]
@chesterkuo you can probably try g++ 4.x

**Comment by chesterkuo** [comment]
The default of Ubuntu 16.04 have gcc-5.4 here , it mean the snowboy library not support this version here ?

**Comment by chenguoguo** [comment]
Snowboy supports it. There are a lot of ways to work around this, e.g., https://github.com/Kitt-AI/snowboy/issues/99
