### ISSUE TITLE
Snowboy and pyaudio, [Errno -9998] Invalid number of channels. (Python3)

### ISSUE THREAD

**Issue by MartLugt** [Kitt-AI/snowboy#308]
Hello there!

I've been trying to use snowboy for a smart assistant. The snowboy detection works flawlessly, however, pyaudio gives an error when I try to record in the callback. 

```
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1469
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2778
```

First these errors come up, and after that the Errno -9998 error comes up. I have already terminated the detector in the callback:

```
def record():
    detector.terminate()

    speech_to_text.record(rate = 44100, device_index = 1)
 
detector = sb.HotwordDetector(model, sensitivity=0.4)
print("Listening...")

detector.start(detected_callback=record, sleep_time=0.03)

detector.terminate()
```

This only happens when device index is the same as the default device, which snowboy uses, so I suspect it has something to do with this.

I have also tested using snowboydecoder_arecord.py.

Thank you!

**Comment by chenguoguo** [comment]
I looked it up `[Pyaudio] Error: invalid number of channels -9998`

Looks like you have an issue with the number of channels? Have you tried to initialize PyAudio as Snowboy does?

**Comment by MartLugt** [comment]
I have just tried that. The error remains, even when using the same arguments.

I have found out however, that when I use a different audio device in snowboy than in the record function it works flawlessly.
