### ISSUE TITLE
Question about multimodel detect

### ISSUE THREAD

**Issue by boshkash1151** [Kitt-AI/snowboy#310]
I am trying to add multiple models using the following code

     class bla:

            def populate_actions(self,actions):
                  self.actions = actions
                  for i in range(0,len(self.actions)):
                  self.models.append(self.actions[i].get_model())
                  self.commands_callbacks.append(lambda: self.actions[i].action_hotword_detected_callback())**

and then starting the models using the following:

       def start_hotword_detected_callback(self):
 
              sensitivity=[0.5]*len(self.models)
              self.commands_detector = snowboydecoder.HotwordDetector(self.models, sensitivity=sensitivity)
              self.commands_detector.start(detected_callback=self.commands_callbacks,sleep_time=0.03)

the problem is that all hotwords only call the first hotword callback 
while if  Iused the following to specify the models and call backs it works

       class bla:

              def populate_actions(self,actions):
                     self.actions = actions
                     for i in range(0,len(self.actions)):
                            self.models.append(self.actions[i].get_model())
                            self.commands_callbacks=[]
                     self.commands_callbacks.append(lambda:self.actions[0].action_hotword_detected_callback())
                     self.commands_callbacks.append(lambda:self.actions[1].action_hotword_detected_callback())

what i am doing wrong

**Comment by chenguoguo** [comment]
Were you following this demo?

From your code I couldn't tell if your callback functions are the same or not.

**Comment by boshkash1151** [comment]
Yes I followed the demo and it works and also the other type of calling the method works.

All what I have different than the demo is that the callbacks are object methods

**Comment by chenguoguo** [comment]
This is really a Python programing issue. Perhaps you could look more into Python grammars?

**Comment by boshkash1151** [comment]
@chenguoguo ,

OK i will try to search online
thanks
