### ISSUE TITLE
[Question] Remove "Recording" logs with Node

### ISSUE THREAD

**Issue by WoodySlum** [Kitt-AI/snowboy#314]
Hi,

I would like to remove the "Recording 8192 bytes" log  when using the node.js lib.
It seems to be caused by `node-record-lpcm16` library which has a `verbose` setting.

How can I turn off those logs ?

**Comment by evancohen** [comment]
When you create the audio stream just set the verbose flag to false.

```javascript
const mic = record.start({
  threshold: 0,
  verbose: false
});
```

**Comment by WoodySlum** [comment]
Got it :)
