### ISSUE TITLE
sudden loop sending 'sound' events thru detector, node implementation

### ISSUE THREAD

**Issue by sdetweil** [Kitt-AI/snowboy#315]
Using the github smart-mirror project, after approx 18 hours 43-49 minutes, Snowboy 1.2.0 (node) starts sending constant stream of 'sound detected' events. and never recovers.  repeatable for me.. 
I have three logs, and the elapsed time from initial start is 18:43, 18:49 and 18:43  (hours:minutes)

each time there is no one awake, so only ambient noise at the time 

all occurrences have been  over a day change (tuesday night to wed morning for example)

sonus package debug code
  detector.on('silence', () => {writelog('module detector silence');sonus.emit('silence')})
  detector.on('sound', () => {writelog('module detector sound');sonus.emit('sound')})
  detector.on('error', () => {writelog('module detector error');sonus.emit('error','')})

from the debug log 

11/22/2017 2:41:33 AM module detector silence
11/22/2017 2:41:33 AM module detector silence
11/22/2017 2:41:33 AM module detector silence
11/22/2017 2:41:33 AM module detector silence
11/22/2017 2:41:33 AM module detector silence
11/22/2017 2:41:33 AM module detector silence
11/22/2017 2:41:33 AM module detector silence
11/22/2017 2:41:33 AM module detector sound  <----- stuck from here on 
11/22/2017 2:41:34 AM module detector sound
11/22/2017 2:41:34 AM module detector sound
11/22/2017 2:41:34 AM module detector sound
11/22/2017 2:41:34 AM module detector sound
11/22/2017 2:41:34 AM module detector sound
11/22/2017 2:41:34 AM module detector sound
11/22/2017 2:41:34 AM module detector sound

never recovers

**Comment by chenguoguo** [comment]
@evancohen Evan have you ever noticed this?

**Comment by sdetweil** [comment]
yes, i am working with evan and there is at least one issue open https://github.com/evancohen/smart-mirror/issues/670.. and in the sonus module too https://github.com/evancohen/sonus/issues/68

this issue for snowboy is really a coordinating issue..  as I can reproduce it every day, how can I capture failure info?

**Comment by evancohen** [comment]
@chenguoguo I've been on vacation so I haven't had the chance to dig into this. I'm trying to work out what the root cause is (node-record-lpcm16, snowboy, or sonus itself). 

@sdetweil have you tried running the node snowboy detector standalone? That would help me narrow down the search.

**Comment by sdetweil** [comment]
How do I do that? Snowboy node detector.

**Comment by evancohen** [comment]
```
npm install snowboy
```
Run the [microphone example](https://github.com/Kitt-AI/snowboy/blob/master/examples/Node/microphone.js). You may want to add the same logging data points that you're using with sonus too.

**Comment by sdetweil** [comment]
got it.. test running now..  

one observation.. with the lpcm in verbose mode we get a recording message every few seconds.. same cadence as the sound/silence callbacks

log from test mic example running
11/27/2017 6:47:40 AM sound
11/27/2017 6:47:41 AM sound
11/27/2017 6:47:41 AM sound
11/27/2017 6:47:41 AM silence
11/27/2017 6:47:41 AM silence
11/27/2017 6:47:41 AM sound
11/27/2017 6:47:41 AM sound
11/27/2017 6:47:42 AM sound
11/27/2017 6:47:42 AM sound
11/27/2017 6:47:42 AM sound
11/27/2017 6:47:42 AM sound
11/27/2017 6:47:42 AM sound
11/27/2017 6:47:42 AM sound
11/27/2017 6:47:43 AM sound
11/27/2017 6:47:43 AM silence
11/27/2017 6:47:43 AM silence
11/27/2017 6:47:43 AM silence

**Comment by evancohen** [comment]
Yup, this is expected - each of these represents a "chunk" of audio data (one for it being recorded by lpcm and one processed by snowboy). Very curious to see if snowboy has the same issue (my suspicion is that it does). If that is the case, the next step would be to go one more step down the stack and try to run lpcm by itself to see if that hangs at the same time.

**Comment by sdetweil** [comment]
snowboy test did not fail.   after 24 hours still does hotword detection

**Comment by evancohen** [comment]
Well that's good news! I should have specified using arecord. You might have to tweak the device name, but your mic should look something like:
```javascript
const mic = record.start({
  threshold: 0,
  verbose: true,
  recordProgram: 'arecord',
  device: 'plughw:1,0'
});
```

**Comment by sdetweil** [comment]
ok, using arecord we have the same hang..  at 18:38 elapsed.    11/29 08:48am to 11/30 03:26 am.

**Comment by evancohen** [comment]
Thanks for running that again! This is great progress :)

The good news here is that theoretically we can get a really consistent reproduction in a shot amount of time by specifying a super small file size using `--max-file-time`.

I'll have time to dig into this tonight.

**Comment by sdetweil** [comment]
I tried that. But the parms don't work

--max-file-time 10 
Fails at 35 Ms and the sample stops.
--max-file-time=10
Runs but doesn't stop as expected. 

I modified the mode-lpcm module to set the parms, as I didn't see a way to pass that thru

**Comment by sdetweil** [comment]
evan, any luck reproducing this?

**Comment by evancohen** [comment]
I had a little bit of time to start looking into it. It seems like the root issue is something fishy happening when using `arecord` in [node-record-lpcm16](https://github.com/gillesdemey/node-record-lpcm16). Maybe @gillesdemey has seen this before?

**Comment by sdetweil** [comment]
thx..  looking a the arecord source, i think the problem is that the write() to stdout fails at the 2gb mark with errno EFBIG (file too big)  and the spawned arecord process should end (I will start a test to confirm). 

but.. it appears arecord loses the errno in this case 
			if (xwrite(fd, audiobuf, c) != c) {  // if returned(EFBIG!=c)
				perror(name); // name="-"
				in_aborting = 1;
				break;
			}

it correctly restarts a new 'file' in the stdout stream if the max_file_time is set.. 
i don't think node_lpcm reports errors from stderr. there is an open issue [https://github.com/gillesdemey/node-record-lpcm16/issues/19]
i think node_lpcm16 reports 'end' when arecord ends (quietly), but snowbody doesn't look for this error.

**Comment by sdetweil** [comment]
hm.. arecord still executing (ps -ef) but reco is dead at 18 hours 

now i am just doing arecord piped to a file to see if I can capture the source problem.

**Comment by sdetweil** [comment]
ok, arecord has a problem..  at about 2gig data suddenly start getting this in the data collected, there are 143,000 of these at the end of the file.  ( placed a newline at the front of RIFF to see what this is 
```
RIFFd  WAVEfmt      €>   }    data@  
RIFFd  WAVEfmt      €>   }    data@  
RIFFd  WAVEfmt      €>   }    data@  
RIFFd  WAVEfmt      €>   }    data@ 
```
over and over.. that is a new wave file.

i understand the bug.. where do I report issues with arecord? i see the alsa project, but can't figure out how to register. 

the aplay.c capture routine bug is that the inner loop is controlled by the amount of data left to record. but it is set (and reset) from the total count of bytes allowed, and the count is set ONCE, but then decremented til the 'file size' is reached, and then the remaining data is reset to that.. but its 0... so, we don't record any more data, start a new wave output, then don't record any data, then start a new wave file, rinse and repeat. 

i think in the short term (maybe forever) smart-mirror will have to stop/start reco after 12 or so hours, to avoid the limit.

**Comment by evancohen** [comment]
Woohoo, nice job figuring that out! I think you have to file bugs for ALSA through their mailing list. Please CC me so I can stay up to date on the thread (DM me on Discord if you don't have my contact info).

http://alsa-project.org/main/index.php/Bug_Tracking

**Comment by sdetweil** [comment]
not a snowboy issue.. closing
