### ISSUE TITLE
How to run snowboy example C in ARM64 platform?

### ISSUE THREAD

**Issue by nosqlcoco** [Kitt-AI/snowboy#320]
Hi,
I want to `/snowboy/example/C` code run in ARM64 platform.
installed aarch64-linux-gnu-gcc and set env path.
I  replace `$(CXX) ` to `aarch64-linux-gnu-gcc` in `/snowboy/example/C/Makefile` file
execute `make` cmd, get error:
```
ksq@ksq-thinkpad-t430:~/workspace/ml/snowboy/examples/C$ make
aarch64-linux-gnu-gcc  -fPIC -msse -msse2 -I../../ -Wall -Iportaudio/install/include -O3   -c -o demo.o demo.c
aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-msse2’
<builtin>: recipe for target 'demo.o' failed
make: *** [demo.o] Error 1
```  
the reason has been showed that aarch64-linux-gnu-gcc` have no `-msse` and `-msse2` options, 
how to cross compile /snowboy/example/C code for running ARM64 platform?

**Comment by chenguoguo** [comment]
Hi, we don't have a library for ARM64 yet.

**Comment by nosqlcoco** [comment]
how about `ARM64 (aarch64, Ubuntu 16.04)` in this project README introduction?

**Comment by nosqlcoco** [comment]
is snowboy not support Amlogic platform(ARM64)?

**Comment by chenguoguo** [comment]
`aarch64, Ubuntu 16.04` is not for ARM64.

Snowboy works for ARM64. But the libraries published on the github page are meant to cover the main stream devices. So we don't provide a library for ARM64 on this github page.
