### ISSUE TITLE
setup.py not working

### ISSUE THREAD

**Issue by reaganfoxley** [Kitt-AI/snowboy#321]
Hello, 

I am new to github and somewhat new to installing things on my raspberry pi. I have tried to install snowboy for a while now, and still am unable to. 

First, I did 
`git  clone https://github.com/Kitt-AI/snowboy`

When I run "setup.py" by double clicking it, which opens it in the python3 IDLE, I encounter multiple errors. 

I believe I installed swig correctly, although that may be an issue. What else can I do to get this working?

**Comment by chenguoguo** [comment]
Please follow the examples here `https://github.com/Kitt-AI/snowboy/tree/master/examples`

**Comment by reaganfoxley** [comment]
Thank you for your response!

On attempting to run "demo.py" I get the system error:
Systemerror: Parent module '' not loaded, cannot perform relative import

I'm not sure what's wrong here. Do I need to specify the directory with something like:
`from .home.pi.snowboy.examples.python3 import snowboydecoder`

Thanks again for the help!

**Comment by chenguoguo** [comment]
Did you compile it under the `swig` directory?

**Comment by reaganfoxley** [comment]
Hi Guoguo,

I have the `swig` directory inside my `snowboy` directory. So within `snowboy` I have `swig` and `examples` in addition to other folders. I have been running the example "demo.py", which is not inside the `swig` folder. 

Do I need to start over to get my files in the correct directory? Would entering the swig directory and doing `git clone https://github.com/Kitt-AI/snowboy` work to have everything in the correct location?

Thanks again
