### ISSUE TITLE
Error installing Snowboy on windows10 64-bit Python-3 Anaconda package

### ISSUE THREAD

**Issue by Adity-dev** [Kitt-AI/snowboy#322]
Getting the following error 

PS C:\Users\adity\Desktop\AI_files\snowboy\snowboy-master> python setup.py build
running build
Compiling snowboy...
make: python3-config: Command not found
make: python3-config: Command not found
g++  -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
snowboy-detect-swig.cc:176:21: fatal error: Python.h: No such file or directory

                     ^
compilation terminated.
make: *** [Makefile:70: snowboy-detect-swig.o] Error 1
error: can't copy 'swig\Python3\_snowboydetect.so': doesn't exist or not a regular file

plz help guys

**Comment by chenguoguo** [comment]
Unfortunately Snowboy doesn't work on Windows yet.

**Comment by Adity-dev** [comment]
Thanks for your reply
