### ISSUE TITLE
why windows not supported?

### ISSUE THREAD

**Issue by sunjunlishi** [Kitt-AI/snowboy#325]
为什么windows 不能够得到支持？也是很大的用户群体呀

**Comment by chenguoguo** [comment]
Mostly developers don't use Windows in their final system, especially on computation limited devices, so we don't have a immediate plan to support Windows.

**Comment by sunjunlishi** [comment]
只有测试原型机，windows有很多开发者，且windows开发方便

**Comment by Baael** [comment]
@chenguoguo you will be suprised how many use windows as development machines.

**Comment by Llorx** [comment]
10 downvotes to @chenguoguo comment. Not surprising.

**Comment by Lost-Lisa** [comment]
> 10 downvotes to @chenguoguo comment. Not surprising. This is not a software made for development, but for final users. Kinda weird that they don't support Windows.
> 
> EDIT: Found this: https://github.com/Picovoice/Porcupine

this is pain in the ass porcupine is just a crap. it takes whole lot to setup and its huge 
plus now they have set license of 30 days how are u supposed to re-write files if it is deployed in package. 
u cannot train your own  keyword u have to make request and bla bla ass

**Comment by Elijahwb** [comment]
You guys are so weird! Anyways you have forced us to try other ways of doing it.

**Comment by CrackerHax** [comment]
2022 and the devs still don't care if their code is used in consumer software.

**Comment by Llorx** [comment]
The project is abandoned as the project is now closed. Las commit was years ago.

Maybe because they don't allowed Windows xD

**Comment by realwumbl3** [comment]
sadd (in trumps voice)

**Comment by realwumbl3** [comment]
sad (in trump's voice)
