### ISSUE TITLE
How to update sensitivity of my trained model?

### ISSUE THREAD

**Issue by caldecy** [Kitt-AI/snowboy#329]
Hi, I am new to this Raspberry Pi platform and would greatly appreciate if someone can teach me exactly on how to update and change the sensitivity setting of the default as well as my own personal wakeword model? 

Currently, I want to change the wakeword from "Alexa" to my own model but after replacing the file path in the KittAiSnowboyWakeWordEngine.cpp -> Model file ="../ext/resources/mymodel.pmdl";   and running the _make_ command to recompile, I cannot wake the assistant up anymore. 

Did I miss a step in setting the new model?

**Comment by chenguoguo** [comment]
Here:
```
https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp#L29
```
Change `APPLY_FRONTEND` to `false`

Here:
```
https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp#L108
```
Add one more line `m_detector->SetSensitivity(YOUR_SENSITIVITY);` where `YOUR_SENSITIVITY` is your sensitivity.

**Comment by caldecy** [comment]
Thank you for your help! I'll try it and let you know if the problem is resolved! :)

**Comment by caldecy** [comment]
When I added the line for sensitivity update and ran the _make_ command, I encountered this error message: 

`/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp: In member function ‘void AlexaWakeWord::KittAiSnowboyWakeWordEngine::initDetector()’:
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:110:33: error: no matching function for call to ‘snowboy::SnowboyDetect::SetSensitivity(double)’
   m_detector->SetSensitivity(0.5);
                                 ^
In file included from /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:18:0,
                 from /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:14:
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/../ext/include/snowboy-detect.h:98:8: note: candidate: void snowboy::SnowboyDetect::SetSensitivity(const string&)
   void SetSensitivity(const std::string& sensitivity_str);
        ^~~~~~~~~~~~~~
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/../ext/include/snowboy-detect.h:98:8: note:   no known conversion for argument 1 from ‘double’ to ‘const string& {aka const std::basic_string<char>&}’
CMakeFiles/wakeWordAgent.dir/build.make:302: recipe for target 'CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspi_chu:~/alexa-avs-sample-app/samples/wakeWordAgent/src $ make
Scanning dependencies of target wakeWordAgent
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp: In member function ‘void AlexaWakeWord::KittAiSnowboyWakeWordEngine::initDetector()’:
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:110:30: error: ‘YOUR_SENSITIVITY’ was not declared in this scope
   m_detector->SetSensitivity(YOUR_SENSITIVITY);
                              ^~~~~~~~~~~~~~~~
CMakeFiles/wakeWordAgent.dir/build.make:302: recipe for target 'CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspi_chu:~/alexa-avs-sample-app/samples/wakeWordAgent/src $ make
Scanning dependencies of target wakeWordAgent
[  6%] Building CXX object CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp: In member function ‘void AlexaWakeWord::KittAiSnowboyWakeWordEngine::initDetector()’:
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:110:33: error: no matching function for call to ‘snowboy::SnowboyDetect::SetSensitivity(double)’
   m_detector->SetSensitivity(0.6);
                                 ^
In file included from /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:18:0,
                 from /home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.cpp:14:
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/../ext/include/snowboy-detect.h:98:8: note: candidate: void snowboy::SnowboyDetect::SetSensitivity(const string&)
   void SetSensitivity(const std::string& sensitivity_str);
        ^~~~~~~~~~~~~~
/home/pi/alexa-avs-sample-app/samples/wakeWordAgent/src/../ext/include/snowboy-detect.h:98:8: note:   no known conversion for argument 1 from ‘double’ to ‘const string& {aka const std::basic_string<char>&}’
CMakeFiles/wakeWordAgent.dir/build.make:302: recipe for target 'CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/KittAiSnowboyWakeWordEngine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by chenguoguo** [comment]
Make sure your `YOUR_SENSITIVITY` is a C++ string, not a float value. Try `m_detector->SetSensitivity("0.6")`

**Comment by caldecy** [comment]
Thanks for the advice! Now I manage to update the sensitivity of the wake word, hopefully all will be good!
