### ISSUE TITLE
树莓派 3B+上安装运行snowboy失败

### ISSUE THREAD

**Issue by cc1990** [Kitt-AI/snowboy#334]
你好：
    我想在树莓派上安装运行snowboy，使用的一个USB的麦克风作为音频输入设备，然后按照[snowboy官网上的文档](http://docs.kitt.ai/snowboy/#running-on-raspberry-pi)步骤来搭建相应环境，在执行 aplay -l  和  arecord -l 命令得到的结果和你的是一样的，然后创建了一个~/.asoundrc文件，写入你提供的值。安装portaudio、python-audio、sox(14.4.2版本) 以及 pyaudio 之后重启树莓派，在执行rec test.wav的时候还是报错：
`pi@raspberrypi:~$ rec test.wav
rec FAIL sox: Sorry, there is no default audio device configured`
    我试着运行snowboy 的 demo文件：
`sudo python demo.py snowboy.pmdl`
报的错误是：
`IOError: [Errno -9997] Invalid sample rate`

然后我在这里翻看了相关的问答，发现你在其他问题下推荐另外一种方法，执行demo_arecord.py（我在使用arecord命令是可以成功录音的），在这篇[问答里](https://github.com/Kitt-AI/snowboy/issues/295)，发现有位朋友运行成功了，但是我使用sudo python和使用python执行demo_arecord.py 的时候也还是报以下错误：
`Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data/python/snowboy_bak/snowboydecoder_arecord.py", line 99, in record_proc
    wav = wave.open(process.stdout, 'rb')
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python2.7/chunk.py", line 63, in __init__
    raise EOFError
EOFError`

请问有没有其他方法能解决问题的，谢谢

**Comment by chenguoguo** [comment]
Yes according to https://github.com/Kitt-AI/snowboy/issues/295 you will have to run it as a normal user. Is it necessary that you have to run it with sudo?

**Comment by cc1990** [comment]
无论是  “sudo python demo_arecord.py snowboy.pmdl”  执行，还是使用默认用户pi 执行 “python demo_arecord.py snowboy.pmdl”  都是报一样的错误。

**Comment by chenguoguo** [comment]
Not exactly sure what went wrong. Do you have other microphones by hand? If yes could you give that a shot? The error `IOError: [Errno -9997] Invalid sample rate` indicates that the required 16k sampling rate was not supported.

**Comment by cc1990** [comment]
好的，谢谢，那我换一个可以支持16K采样率的麦克风

**Comment by cnhnlin** [comment]
您好, 我實測情形是:
當我先執行了另一支google assistant hotword程式後,再執行snowboy程式時,就會出現錯誤"IOError: [Errno -9997] Invalid sample rate " (看似是二支程式"同時執行"才會有出現IOError-不知為什麼會這樣?)
想請問 不知透過調整snowboy程式碼的手段,是否可達到避免錯誤(沖突)出現呢? 該由什麼地方著手呢?謝謝!

**Comment by chenguoguo** [comment]
@cnhnlin so if you only use Snowboy, it works correct?

See here: https://github.com/Kitt-AI/snowboy/issues/123

**Comment by cnhnlin** [comment]
Yes, it's works correct !! ( if only use Snowboy)



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=cnhn.lin@gmail.com&idSignature=22>
<#>

B.R

**Comment by cc1990** [comment]
你好，使用snowboy是否一定要使用支持16K采样率的麦克风，是否支持更大一点的采样率，比如48000？

**Comment by chenguoguo** [comment]
It does not. @cc1990

**Comment by cc1990** [comment]
好的，谢谢 @chenguoguo

**Comment by fengmm521** [comment]
我这里在rpi3 B+上安装了ubuntu18的64位系统，系统镜像用的是这个
https://github.com/chainsx/ubuntu64-rpi
麦克风使用rec 可以正常录音，播放也没有问题，但在swig/Python和swig/Python3下运行make时，编译后链接的时候snowboy的报错了。好像是.a的库和处理器不兼容的错。有没有人遇到

**Comment by cnhnlin** [comment]
Yes, I think it does
B.R

‌
