### ISSUE TITLE
Module not found: Error: Can't resolve 'aws-sdk'

### ISSUE THREAD

**Issue by henrikra** [Kitt-AI/snowboy#335]
I am getting this error when I am trying to compile my project with Webpack which is using snowboy as dependency:
```
Module not found: Error: Can't resolve 'aws-sdk' in '/projects/MagicMirror/modules/my-project/node_modules/node-pre-gyp/lib'
```

Here is my webpack config:
```
{
    target: "node",
    entry: "./src/main/index.ts",
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "main.js",
    },

    resolve: {
        extensions: [".ts", ".js"],
    },

    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: ["awesome-typescript-loader"],
            }
        ],
    },
}
```

I have narrowed down the problem when I am calling
```js
import { Models } from "snowboy";
const models = new Models(); // this line causes the error
```

I would highly appreciate if someone can help me with this :)

**Comment by evancohen** [comment]
My guess is that this is an issue with Webpack not packaging the `aws-sdk` properly.  
You might want to try this:
https://stackoverflow.com/questions/31584310/how-to-use-webpack-import-aws-sdk

**Comment by henrikra** [comment]
Yeah I have tried those already with no luck 😢  Should I do repo which will reproduce this problem? Would that help you?

**Comment by evancohen** [comment]
Yeah, that'd be great help!

**Comment by henrikra** [comment]
What I ended up doing was adding all `node_modules` to `externals`. This way webpack don't have to parse dependencies. So it will leave `require`s of node_modules as is. 

Do you think this is good approach for node apps? :)

**Comment by evancohen** [comment]
Glad you got that figured out - I don't have a ton of Webpack experience within Electron so I can't comment on the validity of the approach, but if it works... it works ;)

**Comment by henrikra** [comment]
Case closed!

**Comment by amuchaware** [comment]
Error: Can't resolve 'util' in 'C:\Users\amol\Angular\node_modules\aws-sdk\lib'
