### ISSUE TITLE
Swig command not found

### ISSUE THREAD

**Issue by paulmunns** [Kitt-AI/snowboy#338]
Hello,

I've been trying to setup snowboy but i keep getting errors.

I first used this website to install snowboy: http://www.userk.co.uk/hotword-spotting-with-snowboy-kitt.ai-python/.
I have installed swig in the folder /programs/libraries/swig
I have installed the snowboy under /programs/snowboy

But it gave me this error:
pi@raspberrypi:~/programs/snowboy/swig/Python $ make
/bin/sh: 1: swig: not found
expr: syntax error
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
make: swig: Command not found
Makefile:63: recipe for target 'snowboy-detect-swig.cc' failed
make: *** [snowboy-detect-swig.cc] Error 127

So i decided to use the next command line to install snowboy: 
pi@raspberrypi:~ $ npm install --save snowboy

But here i get the same error:
pi@raspberrypi:~/node_modules/snowboy/swig/Python3 $ make
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
make: swig: Command not found
Makefile:48: recipe for target 'snowboy-detect-swig.cc' failed
make: *** [snowboy-detect-swig.cc] Error 127
 
This time its not in the folder Python but in the folder Python3. 
The location of the folder is different. Its in /node_modules instead of /programs.

Can someone please help me with this? I've been struggling with this the last 3 days.

Regards,
Paul

**Comment by paulmunns** [comment]
I finally fixed it. I deleted swig with all the files. Then i reinstalled swig by apt-get install swig3.0.
I changed this in the Makefile --> SWIG := swig3.0. 
Now i can finally run it.

**Comment by AsadDUET** [comment]
where is the make file ?

**Comment by NoahCardoza** [comment]
Just in case this is helpful to anyone, I was having the same problem, and I had to fix `PYTHON_EXTRA_LDFLAGS`.

It was set to `PYTHON_EXTRA_LDFLAGS='-u _PyMac_Error Python.framework/Versions/2.7/Python'`, `Python.framework/Versions/2.7/Python` being an incomplete path.

After running `PYTHON_EXTRA_LDFLAGS='-u _PyMac_Error /Library/Frameworks/Python.framework/Versions/2.7/Python' ./configure` it work!
