### ISSUE TITLE
Setting up Input device

### ISSUE THREAD

**Issue by transmit-ter** [Kitt-AI/snowboy#343]
Hi, how can i select my Input audio device if i use 2 USB microphones for audio input. Any help would be deeply appreciated.

My Environment
Environment name and version: Raspberry Pi 3, node.js v6.11.4
Operating System and version: Raspbian

**Comment by chenguoguo** [comment]
You have to play with PyAudio or PortAudio to select your audio device. You may or may not succeed though... See here:

https://stackoverflow.com/questions/36894315/how-to-select-a-specific-input-device-with-pyaudio

**Comment by transmit-ter** [comment]
Thanks for help!
By the way, can i run 2 file on 2 separated terminal window, like:
Python  demoA.py  my1stmodel.pmdl  and  Python demoB.py  my2ndmodel.pmdl?

**Comment by chenguoguo** [comment]
PyAudio may not be able to grab the microphones.

If you just want to run two models, you can also try demo2.py, which allows you to use two models.

**Comment by transmit-ter** [comment]
I mean, i would like to run in parallel python processes in separated terminal window. Both of them use Snowboy for keyword recognition.
In 1st terminal window: Python Afile.py 1stmodel.pmdl
In 2nd terminal window: Python Bfile.py 2ndmodel.pmdl
Can i use the same mic in the same time for multiple processes?

**Comment by transmit-ter** [comment]
Ok let me try, thank you for supporting me
