### ISSUE TITLE
How to end the detector loop?

### ISSUE THREAD

**Issue by saket404** [Kitt-AI/snowboy#361]
How do i end the detector loop after it detects a hot word? So i am calling the wake_word() function in another python file but i just want it to detect a hotword a single time and break out.

**Comment by chenguoguo** [comment]
https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/demo4.py

**Comment by saket404** [comment]
Hello I have tested the demo but i think you misunderstood my question sir. I meant like when it detects the wake word i want it to break the loop. The demo jumps to google recognition and after it does the recognition it still goes back to the wake word loop. I want to break out of that wake word loop. The detector.start() 

Thanks
Saket

**Comment by chenguoguo** [comment]
You can simply use the break statement in Python instead of using the callback function.

**Comment by saket404** [comment]
What do you mean how do i edit the detector.start() code? Sorry i am new to this haha.
