### ISSUE TITLE
mac os x assertion error

### ISSUE THREAD

**Issue by Techblogogy** [Kitt-AI/snowboy#37]
Hello everyone, I'm having a little problem, whenever I'm trying to use snowboyy I get this error

||PaMacCore (AUHAL)|| Error on line 2466: err='-10863', msg=Audio Unit: cannot do in current context
Assertion failed: (!err), function AudioIOProc, file src/hostapi/coreaudio/pa_mac_core.c, line 2467

can somebody help me with that?

**Comment by Techblogogy** [comment]
sorry i've found the issue, everything is fine

**Comment by ekampf** [comment]
@Techblogogy facing the same error...  what was your issue?

**Comment by Dearmener** [comment]
> sorry i've found the issue, everything is fine

Could you tell how to fix it ?i hava met the same question when i use snowboy

**Comment by Kevin369** [comment]
||PaMacCore (AUHAL)|| Error on line 2490: err='-10863', msg=Audio Unit: cannot do in current context


i hava met the same question when i use snowboy, when i init a pyaudio to record vocie ,it will have the question. but i dont use the snowboy,it is have no error.
