### ISSUE TITLE
/api/v1/train requires more parameters than it is documented 

### ISSUE THREAD

**Issue by xuezhma** [Kitt-AI/snowboy#373]
According to docs at http://docs.kitt.ai/snowboy/#api-v1-train`/api/v1/train`,

`/api/v1/train` only requires `voice_samples`, `token`, and `name`.
`age_group` and others are not required. 
However, API responses tell me to includes these parameters.

### To reproduce:

Use `snowboy/examples/REST_API/training_service.sh`, remove
```
AGE_GROUP="20_29"
GENDER="M"
MICROPHONE="??" # e.g., PS3 Eye
```

Will write a file like this:

```
{"age_group":["This field may not be blank."],"gender":["This field may not be blank."],"microphone":["This field may not be blank."]}
``` 

My questions are can I train a pmdl with only `voice_samples`, `token`, and `name`?
If I have to provide the other fields when I have no way of knowing such information of the audios, what would be a good set of default values to put there?

**Comment by chenguoguo** [comment]
Try something like

```
cat <<EOF >data.json
{
    "name": "$NAME",
    "language": "$LANGUAGE",
    "token": "$TOKEN",
    "voice_samples": [
        {"wave": "$WAV1"},
        {"wave": "$WAV2"},
        {"wave": "$WAV3"}
    ]
}
EOF
```

in the bash script.

**Comment by xuezhma** [comment]
good catch. thx
