### ISSUE TITLE
AVS build with snowboy lib appear error

### ISSUE THREAD

**Issue by jie714** [Kitt-AI/snowboy#389]
Hi, 
I try use NDK r14b to build AVS with libsnowboy-detect-android.so, but it appear below error:
platform:

[ 65%] Linking CXX executable KittAiKeyWordDetectorTest
../src/libKITTAI.so: error: undefined reference to 'snowboy::SnowboyDetect::SetSensitivity(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
../src/libKITTAI.so: error: undefined reference to 'snowboy::SnowboyDetect::SnowboyDetect(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
clang38++: error: linker command failed with exit code 1 (use -v to see invocation)
KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/build.make:102: recipe for target 'KWD/KittAi/test/KittAiKeyWordDetectorTest' failed
make[2]: *** [KWD/KittAi/test/KittAiKeyWordDetectorTest] Error 1

Any idea about this issue?
Thanks.

Jack Ho

**Comment by jackeyu** [comment]
I meet the same issue. Did you already fix it?  or have anybody know how to fix it?

**Comment by chenguoguo** [comment]
See here: https://github.com/Kitt-AI/snowboy/issues/388

We will prepare a PR for it.

**Comment by mmabluesky** [comment]
Hi  ，@chenguoguo 
On the Android platform, I try use NDK r16 to build AVS with libsnowboy-detect-android.soy. ，I tried all the ways to fail.  Have you solved this problem?

**Comment by mmabluesky** [comment]
@jie714 
Have you solved this problem?

**Comment by mmabluesky** [comment]
Currently, I use sensory instead of snowboy
