### ISSUE TITLE
How to work on Android platform, I encountered a build error following your sop.

### ISSUE THREAD

**Issue by WksKing** [Kitt-AI/snowboy#39]
thanks for your excellent product.

Build environment:
- Ubuntu14.04  64 bits
- swig-3.0.7
- android-ndk-r11c

$PATH:

> king@wks:~/Downloads/snowboy-master/swig/Android$ $PATH
bash: /home/king/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/king/AndroidDevelop/android-studio-sdk/android-sdk-linux/platform-tools:/home/king/AndroidDevelop/android-studio-sdk/android-sdk-linux/tools:/home/king/AndroidDevelop/swig_tool/bin:/home/king/AndroidDevelop/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin: No such file or directory
king@wks:~/Downloads/snowboy-master/swig/Android$ 

----------------------------------------------------------------------------------------------------------------------------------

I follow your step to build Android library by below:

> cd swig/Android
 # Make sure you set up the NDKROOT variable in Makefile before you run.
 # We have only tested with NDK version r11c.
 make

but I got an error like this:

> OpenBLAS-0.2.18/version.h
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
make[1]: Entering directory `/home/king/Downloads/snowboy-master/swig/Android/OpenBLAS-Android'
make[2]: Entering directory `/home/king/Downloads/snowboy-master/swig/Android/OpenBLAS-Android/interface'
arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon  -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o
arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon  -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=sswap -DASMFNAME=sswap_ -DNAME=sswap_ -DCNAME=sswap -DCHAR_NAME=\"sswap_\" -DCHAR_CNAME=\"sswap\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c swap.c -o sswap.o
arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon  -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=scopy -DASMFNAME=scopy_ -DNAME=scopy_ -DCNAME=scopy -DCHAR_NAME=\"scopy_\" -DCHAR_CNAME=\"scopy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c copy.c -o scopy.o
arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=neon  -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME=sscal -DASMFNAME=sscal_ -DNAME=sscal_ -DCNAME=sscal -DCHAR_NAME=\"sscal_\" -DCHAR_CNAME=\"sscal\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c scal.c -o sscal.o
copy.c:39:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make[2]: *** [scopy.o] Error 1
make[2]: *** Waiting for unfinished jobs....
axpy.c:39:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make[2]: *** [saxpy.o] Error 1
scal.c:39:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
swap.c:39:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make[2]: *** [sscal.o] Error 1
make[2]: *** [sswap.o] Error 1
make[2]: Leaving directory `/home/king/Downloads/snowboy-master/swig/Android/OpenBLAS-Android/interface'
make[1]: *** [libs] Error 1
make[1]: Leaving directory `/home/king/Downloads/snowboy-master/swig/Android/OpenBLAS-Android'
make: [OpenBLAS-Android/install/lib/libopenblas.a] Error 1 (ignored)
arm-linux-androideabi-g++ -O3 --sysroot=/home/king/AndroidDevelop/android-ndk-r11c//platforms/android-17/arch-arm -shared -std=c++0x -rdynamic -I../../ -Wl,--fix-cortex-a8 -Wl,--no-warn-mismatch -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wno-sign-compare -Wa,--noexecstack -Wformat -Werror=format-security -fno-rtti -ffunction-sections -funwind-tables -fstack-protector-strong -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -fno-strict-aliasing -mthumb -no-canonical-prefixes -march=armv7-a -mfpu=vfpv3-d16 -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -DANDROID -c snowboy-detect-swig.cc -o snowboy-detect-swig.o
snowboy-detect-swig.cc:848:18: fatal error: string: No such file or directory
 #include <string>
                  ^
compilation terminated.
make: *** [snowboy-detect-swig.o] Error 1

> 

Could you provide a step in details about how to do it on Android platform, because I have no idea how  to get information about snowboy, I have searched on internet, but no helps get. 

In addition, could you provide the compiled android library and upload to this github project?

appreciate for your reply.

**Comment by chenguoguo** [comment]
Please try to use the following command to generate the toolchain

```
android-ndk-r11c/build/tools/make-standalone-toolchain.sh --platform=android-17 --install-dir=PATH_TO_INSTALL_YOUR_ANDROI_TOOLCHAIN/arm --stl=libc++
```

You then add `PATH_TO_INSTALL_YOUR_ANDROI_TOOLCHAIN/arm` to your path and make use you use binaries from `PATH_TO_INSTALL_YOUR_ANDROI_TOOLCHAIN/arm` instead of `$NDKROOT`. We only use `$NDKROOT` to load libraries.

Please let me know if this helps.

**Comment by WksKing** [comment]
@chenguoguo,  Thank you very much for prompt reply, you suggestion has fixed my issue:

solution as below:
> 1. android-ndk-r11c/build/tools/make-standalone-toolchain.sh --platform=android-17 --install-dir=PATH_TO_INSTALL_YOUR_ANDROI_TOOLCHAIN/arm --stl=libc++
2. Add android_toochain binary path to $PATH, 
export PATH=$PATH:/home/king/AndroidDevelop/swig_tool/bin:/home/king/AndroidDevelop/android_toolchain/arm/bin

**Comment by chenguoguo** [comment]
Great, I'll add this to the instructions.
