### ISSUE TITLE
How to set a timer for the detection loop?

### ISSUE THREAD

**Issue by saket404** [Kitt-AI/snowboy#400]
Is there a way i could terminate the loop if no hot word is detected for a period of time? 

Thanks

**Comment by jin3lee** [comment]
not sure which language your working on but there is a stopRecording() method in RecordingThread class in the android example that stops the loop.

**Comment by saket404** [comment]
I am using on python @jin3lee

**Comment by jin3lee** [comment]
I don't work with the python example, but I see that in the **snowboythreaded.py** file there is a method **terminate(self)** (on line 74), maybe that can help you?
