### ISSUE TITLE
Problem with integrating Snowboy to my own app

### ISSUE THREAD

**Issue by lovish888** [Kitt-AI/snowboy#401]
Hello, 
I am able to run the SnowboyAlexaDemo under examples/Android pretty well but having issues integrating it into my own project. 
I have copied snowboyJNI, SNowboyDetect and libsnowboy-detect-android.so (under jniLibs/armeabi-v7a) to my new project.
I am facing the following error on running the project : 

` java.lang.UnsatisfiedLinkError: No implementation found for long com.aptener.autorider.VoiceAssistant.snowboyJNI.new_SnowboyDetect(java.lang.String, java.lang.String) (tried Java_com_aptener_autorider_VoiceAssistant_snowboyJNI_new_1SnowboyDetect and Java_com_aptener_autorider_VoiceAssistant_snowboyJNI_new_1SnowboyDetect__Ljava_lang_String_2Ljava_lang_String_2)
                                                                           at com.aptener.autorider.VoiceAssistant.snowboyJNI.new_SnowboyDetect(Native Method)
                                                                           at com.aptener.autorider.VoiceAssistant.SnowboyDetect.<init>(SnowboyDetect.java:0)
                                                                           at com.aptener.autorider.VoiceAssistant.audio.RecordingThread.<init>(RecordingThread.java:34)`

I think its something related to the soft links but I am not sure how to solve this issue. Please help.

**Comment by chowdary60** [comment]
hello @lovish888 

when run the make command, and import the snowboyALexaDemo, did you get the Snowboy.java class? 

in SnowboyJNI.java file showing all the error, that means do i need to write the SnowBoy.java file?
i am new JNI development and if you have Snowboy.java ,can you post?

**Comment by chenguoguo** [comment]
@chowdary60 You don't have to write your own Java class, it will be generated.

For @lovish888 's error, it was possible that you copied the soft linked file instead of the original file.
