### ISSUE TITLE
undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

### ISSUE THREAD

**Issue by cogmeta** [Kitt-AI/snowboy#405]
We fixed this issue in past by changing gcc versions and/or adding -D_GLIBCXX_USE_CXX11_ABI=0 to CPPFLAGS but that is no longer an option as it is affecting other libraries (grpc, protofbuf) in our project. Is there a permanent fix for this please? Thanks.

**Comment by goldegard** [comment]
I went through the exact same issue, in my case using the wrapper suggested in #99 helped in the segregation of the old ABI usage.

**Comment by cogmeta** [comment]
@goldegard thank you. The wrapper is life saver. Thanks.

**Comment by Ehsanta83** [comment]
@cogmeta could you please tell me, how should I use this wrapper?
