### ISSUE TITLE
Requirements for AVS Cloud-Based Wake Word Verification

### ISSUE THREAD

**Issue by linshixiong** [Kitt-AI/snowboy#407]
I am using snowboy as alexa's wake word engine，how do I accurately get the start and end index sample of the wake word in the audio buffer，startIndexInSamples and endIndexInSamples are the parameters needed by avs。

https://developer.amazon.com/docs/alexa-voice-service/streaming-requirements-for-cloud-based-wake-word-verification.html#indices

**Comment by chenguoguo** [comment]
We will submit a PR to their repository soon for this.
