### ISSUE TITLE
Is there a way (a script) to train my own models off-line?

### ISSUE THREAD

**Issue by E3V3A** [Kitt-AI/snowboy#408]
I'm looking for a way to manually train new hotwords `*.pmdl` and add users to make them into `*.umdl` files. But I cannot find any scripts available to do so. Perhaps I'm just searching for the wrong thing?

So how can I feed new training data to my models without using the kitt.ai snowboy site?

**Comment by chenguoguo** [comment]
Unfortunately, to get the universal model, you either have to use the website, or use our paid service.

**Comment by E3V3A** [comment]
Ok, too bad, but thank you.
It would have been fantastic to at least be able to make the pmdl files off line...

**Comment by esp13** [comment]
> @E3V3A You can train your pmdl models offline. Check the README for RESTful APIs.

Are you sure? In the read-me section I see :
> Endpoint: https://snowboy.kitt.ai/api/v1/train/

If you don't need the web-interface you need the web connection to this address, it's away of being able to generate pmdl alone offline. I am missing something?
