### ISSUE TITLE
Make error - make: *** [_snowboydetect.so] Error 1

### ISSUE THREAD

**Issue by Corkskru** [Kitt-AI/snowboy#42]
" g++ -I../../ -O3 -fPIC -std=c++0x  -shared snowboy-detect-swig.o \
	../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/local/lib/python2.7/config -lpthread -ldl -lutil -lm -lpython2.7 -Xlinker -export-dynamic -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas -o _snowboydetect.so
/usr/bin/ld: /usr/local/lib/python2.7/config/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/python2.7/config/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [_snowboydetect.so] Error 1 "

I am following the exact steps provided in the git documentation. I navigate to "swig/Python" and compile ( make ). I get the above make error. Any solutions for this??

**Comment by chenguoguo** [comment]
what was your platform? os?

I briefly searched and it might related to python installation. Did you compile Python by yourself or did you use the standard python? see here: https://github.com/gmarcais/Jellyfish/issues/45

**Comment by Corkskru** [comment]
Hi,
Ubuntu 14.04 -- trying to compile and run the Python wrapper. I compiled Python 2.7.5 by myself.
the files are in /usr/local/lib. However, 'which python' returns /usr/local/bin. Are the compiled and default(pre-installed) pythons in conflict with each other?

**Comment by chenguoguo** [comment]
I think so. In the makefile we used `shell python-config --cflags` and `shell python-config --ldflags` to determine the python dependencies. You may want to replace them with what you are actually using. Also, it might be easier if you install and use your Python in a virtual environment (you have to set this up correctly though). Please let us know if this helps.

**Comment by Corkskru** [comment]
Thanks a lot! It was indeed a conflict -- 'sys.path' displayed that it was using the compiled version of python. I removed/uninstalled the extra python files and now its working wonders!! 
Great SDK though! :)

**Comment by chenguoguo** [comment]
OK thanks, closing since it's resolved.
