### ISSUE TITLE
More than 3 samples for personal models for a single speaker

### ISSUE THREAD

**Issue by tadly** [Kitt-AI/snowboy#423]
Right now (to my knowledge, correct me if I'm wrong) it is not possible to create a personal model with more than 3 samples (be it through the webinterface or the API).

For the project I'm working it would be nice to have personal models which consist of more than 3 samples to improve activation for a single speaker in case of:
 * Different microphones / Different microphone arrays
 * Different rooms
 * Background noise (like music) where heavy noise cancellation/beamforming is performed
 * ...

Are there planes to support this in the future?

**Comment by chenguoguo** [comment]
Unfortunately we don't have a plan to support that.

**Comment by tadly** [comment]
Well that's really super sad.

Care to share the reason for this?
I mean it's (obviously) not a technical limitation. :)

**Comment by chenguoguo** [comment]
It won't work much better with that algorithm even if you have more samples. Also we don't have much resource to support that.

**Comment by cs301cs301** [comment]
maybe the SoPaRe project is what you search for?! you can start training sessions, from different locations, and then create the dictionary.
http://www.bishoph.org
https://github.com/bishoph/sopare

**Comment by tadly** [comment]
Sorry for the delay.

@chenguoguo 
>It won't work much better with that algorithm
That's quite interesting. Thanks for the info.

@cs301cs301 Thanks for that. First time I heard about this project. Will certainly have a look.

As this is a wont-fix, I'll go ahead and just close the issue.
Everyone who stumbles across this issue, feel free to add any viable information :)
