### ISSUE TITLE
ImportError: dynamic module does not define init function (init_snowboydetect)

### ISSUE THREAD

**Issue by NicoLivesey** [Kitt-AI/snowboy#424]
Hi everyone,
Since I restarted my terminal I only get this Traceback even after the compiling on swig/Python3. Did someone already encountered this ?

> Traceback (most recent call last):
>   File "demo.py", line 1, in <module>
>     import snowboydecoder
>   File "/home/pi/snowboy/examples/Python3/snowboydecoder.py", line 10, in <module>
>     snowboydetect = imp.load_source('snowboydetect', curpath+'/snowboydetect.py')
>   File "/home/pi/snowboy/examples/Python3/snowboydetect.py", line 21, in <module>
>     _snowboydetect = swig_import_helper()
>   File "/home/pi/snowboy/examples/Python3/snowboydetect.py", line 20, in swig_import_helper
>     return importlib.import_module('_snowboydetect')
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: dynamic module does not define init function (init_snowboydetect)

It does not seem to be like the Pyinit_snowdetect error because everything seem to be fine on the swig part.
Thank you for your amazing work by the way ! :)

**Comment by kutchbhi** [comment]
Pi zero raspbian jessie, python 3, virtualenv, Compiled snowboydecoder.so , similar error.

(env) pi@raspberrypi:~/code/snowboy/examples/Python3 $ ./demo.py resources/alexa/alexa_02092017.umdl
Traceback (most recent call last):
  File "./demo.py", line 3, in <module>
    import snowboydecoder
  File "/home/pi/code/snowboy/examples/Python3/snowboydecoder.py", line 3, in <module>
    import snowboydetect
ImportError: dynamic module does not define init function (PyInit_snowboydetect)

**Comment by chenguoguo** [comment]
Could you try to run this under Python3 virtual environment? Make sure you also compile swig/Python3 under Python3 virtual environment.
