### ISSUE TITLE
Use Snowboy with Qt

### ISSUE THREAD

**Issue by MiChanth** [Kitt-AI/snowboy#429]
Hi,
 i'm working on a project with snowboy and pocketsphinx. I try to use snowboy with qt but I have some errors. First I add the library and I add the support of C++11. I also add the .h to my project. 

```
unix:!macx: LIBS += -L$$PWD/../../snowboy-master/lib/ubuntu64/ -lsnowboy-detect
INCLUDEPATH += $$PWD/../../snowboy-master/lib/ubuntu64
DEPENDPATH += $$PWD/../../snowboy-master/lib/ubuntu64
unix:!macx: PRE_TARGETDEPS += $$PWD/../../snowboy-master/lib/ubuntu64/libsnowboy-detect.a

CONFIG += c++11
```

I also define `#define _GLIBCXX_USE_CXX11_ABI 0` to stay with basic std::string

Then I just use the code in the example : 

```
    std::string resource_filename = "resources/common.res";
    std::string model_filename = "resources/models/snowboy.umdl";
    std::string sensitivity_str = "0.5";
    snowboy::SnowboyDetect detector(resource_filename,model_filename);
```
and I have the following error : 
matrix-wrapper.cc:-1: error: undefined reference to `cblas_sscal'
matrix-wrapper.cc:-1: error: undefined reference to `cblas_saxpy'
matrix-wrapper.cc:-1: error: undefined reference to `cblas_saxpy'
matrix-wrapper.cc:-1: error: undefined reference to `cblas_sgemm'
matrix-wrapper.cc:-1: error: undefined reference to `cblas_sger'
matrix-wrapper.cc:-1: error: undefined reference to `cblas_sscal'
vector-wrapper.cc:-1: error: undefined reference to `cblas_sdot'
vector-wrapper.cc:-1: error: undefined reference to `cblas_sdot'
vector-wrapper.cc:-1: error: undefined reference to `cblas_sgemv'
vector-wrapper.cc:-1: error: undefined reference to `cblas_snrm2'
vector-wrapper.cc:-1: error: undefined reference to `cblas_saxpy'
vector-wrapper.cc:-1: error: undefined reference to `cblas_sscal'
vector-wrapper.cc:-1: error: undefined reference to `cblas_sdot'
vector-wrapper.cc:-1: error: undefined reference to `cblas_sdot'

Where can I find matrix-wrapper.cc and vector-wrapper.cc ? Thanks for your help

**Comment by chenguoguo** [comment]
Did you add the cblas library? E.g., install ATLAS or OpenBLAS.

**Comment by MiChanth** [comment]
Thanks it solve my problem. The solution was so obvious. Thanks a lot for your help
