### ISSUE TITLE
Using cron to start a python file that is wakeword enabled. 

### ISSUE THREAD

**Issue by Beaverboy** [Kitt-AI/snowboy#43]
Im trying to start a python script upon raspberry pi start. 
I have edited my root crontab file  ( sudo crontab -e) 
Ive asked cron to start the python script as well as the .pmdl file.
my crontab looks like 
@ reboot /location_of_file/pythonscript.py Hotword.pmdl
the python script is starting, but but the startup error file for the script says that the .pmdl file is not found. 

Am I going about this the right way? is there a special way i have to get snowboy started upon startup? or should it just work the same way it does using the command line. 

Do i need to write a supplemental  script to run the python file, and open the PMDL file at the same time?

**Comment by chenguoguo** [comment]
This doesn't seem to be directly related Snowboy... You could try to give the full path of your pmdl file.

**Comment by Beaverboy** [comment]
I feel silly, that was it. Thanks ;O)

**Comment by SwannSchilling** [comment]
I am also struggling to autostart my snowboy...
My crontab looks like this, what did I do wrong?

@reboot sudo python /home/pi/rpi-arm-raspbian-8.0-1.1.1/trigger.py /home/pi/rpi-arm-raspbian-8.0-1.1.1/Kate.pmdl &

**Comment by chenguoguo** [comment]
@SwannSchilling seems OK to me. might relate to your system. let me know if you figure it out.

**Comment by SwannSchilling** [comment]
Yes it works now, was not Snowboy related...Thanks for paying attention!! 👍

**Comment by chenguoguo** [comment]
@SwannSchilling could you let us know what was the issue and how did you fix it? might be helpful to others.

**Comment by SwannSchilling** [comment]
@reboot sudo python /home/pi/rpi-arm-raspbian-8.0-1.1.1/trigger.py /home/pi/rpi-arm-raspbian-8.0-1.1.1/Kate.pmdl &

Works just fine, it was another service which was not starting correctly. So I misinterpreted it and thought that Snowboy does not start up correctly!!
