### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by EranIDar** [Kitt-AI/snowboy#435]
Hello,

I'm actually developing an assistant with a raspberry Pi and a matrix creator. Given that I'm having a lot of issues with Pyaudio, just as @duoduo999 on this [#issue118](https://github.com/Kitt-AI/snowboy/issues/118). I'm trying to use snowboydecoder_arecord.py to solve my problem.

I've modified demo.py in order to import snowboydecoder_arecord : 

`
import **snowboydecoder_arecord**
import sys
import signal

interrupted = False

def signal_handler(signal, frame):
    global interrupted
    interrupted = True

def interrupt_callback():
    global interrupted
    return interrupted

if len(sys.argv) == 1:
    print("Error: need to specify model name")
    print("Usage: python demo.py your.model")
    sys.exit(-1)

model = sys.argv[1]

signal.signal(signal.SIGINT, signal_handler)

detector = **snowboydecoder_arecord**.HotwordDetector(model, sensitivity=0.5)
print('Listening... Press Ctrl+C to exit')

detector.start(detected_callback=**snowboydecoder_arecord**.play_audio_file,
               interrupt_check=interrupt_callback,
               sleep_time=0.03)

detector.terminate()
`

But when I'm launching it, I get this error : 

`Listening... Press Ctrl+C to exit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/Documents/rpi-arm-raspbian-8.0-1.1.1/snowboydecoder_arecord.py", line 113, in record_proc
    wav = wave.open(process.stdout, 'rb')
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python2.7/chunk.py", line 63, in __init__
    raise EOFError
EOFError
`

If anybody has any idea of how to solve this ...

Thank you !

**Comment by randlea2** [comment]
Hi,

I was having the same issue I fixed it by adding os.system("killall arecord") on below line 90 in snowboydecoder_arecord.py. I believe chunks coming in from a different arecord process are causing the error.

```
    def record_proc(self):
        os.system("killall arecord")
        CHUNK = 1024
        RECORD_RATE = 16000
```
