### ISSUE TITLE
Problem with Node example

### ISSUE THREAD

**Issue by SimonJOURDAN** [Kitt-AI/snowboy#438]
Hello,
I have a problem concerning the microphone file in the Node example:
when I start the microphone.js file, i receive the following issue:
```
Error: Cannot find module '../../'
```
If anybody has idea concerning this...
Thank you

**Comment by SimonJOURDAN** [comment]
Thanks a lot for your reply.
Please excuse me, I'm only a beginner, but I've got another problem:
when running:
```
npm install
./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build
```
I receive the following message:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install "node_modules/node-pre-gyp/bin/node-pre-gyp" as it is not a 
         directory and is not a file with a name ending in .tgz, .tar.gz or .tar
```
I don't know what to do...

**Comment by SimonJOURDAN** [comment]
It worked perfectly
But then I have an other problem
when I run ```node file.js``` or ```nodemon microphone.js```, i get that error:
```
*** Error in `/home/user/.nvm/versions/node/v8.11.1/bin/node': munmap_chunk(): invalid pointer: 0x00007ffd4d7ce430 ***
```
I checked and the bug seems to occur with that line : line 64 in index.js (snowboy/lib/node/index.js)
```
this.nativeInstance = new SnowboyDetectNative(options.resource, options.models.modelString);
```

**Comment by evancohen** [comment]
@SimonJOURDAN if you're just looking to use snowboy in Node (and don't have any express reason to build it) then you can just `npm install snowboy` in your node app and `include('snowboy')` (instead of `include('../../'`) like any other npm package. Hope this helps :)
