### ISSUE TITLE
GPIO relay On-Off script based on two models.

### ISSUE THREAD

**Issue by jaydev1997** [Kitt-AI/snowboy#44]
i need GPIO relay On-Off script based on two models. same as demo2.py but the script should be work as follows.

1) when model 1 detects it plays ding sound and turn on relay 17.
2) when model 2 detects it plays dong sound and turn off relay 17.

if anyone can make script like this i would really appreciate. Thanks in Advance..

**Comment by xuchen** [comment]
This is really not a snowboy issue but related to Raspberry Pi. Did you have a look at the example we gave about GPIO:

http://docs.kitt.ai/snowboy/#blink-an-led-light

**Comment by jaydev1997** [comment]
I did but as i mentioned  i want on-off script i.e. if model 1 detected it should be turn on gpio pin x and if model 2 detected it should turn off the relay pin.

**Comment by xuchen** [comment]
something like this?

```
pin_x = Light(17)

callbacks = [pin_x.set_on, pin_x.set_off]
print('Listening... Press Ctrl+C to exit')

# main loop
# make sure you have the same numbers of callbacks and models
detector.start(detected_callback=callbacks,
               interrupt_check=interrupt_callback,
               sleep_time=0.03)
```

**Comment by jaydev1997** [comment]
@xuchen  Thank you Very much.. I really appreciate your work...

**Comment by jaydev1997** [comment]
Another script request ...can you please tell me execute custom bash script which works exactly like this. 
(i'm making home automation project ( school project)). i want to add functionality like if i say "update" it should execute linux command like "sudo apt-get update"

**Comment by xuchen** [comment]
check out:

https://docs.python.org/2/library/subprocess.html

**Comment by jaydev1997** [comment]
I'm sorry, i'm new to python can you describe where to implement this subprocess call.. ?

**Comment by xuchen** [comment]
you gotta first spend time to learn python then handling snowboy is just a piece of cake. how about starting from here: https://docs.python.org/2.7/tutorial/index.html

**Comment by jaydev1997** [comment]
well i don't have much time.. submission is near.. can you please tell me the how to implement it.. i tried it but got an error. check logs here--> http://goo.gl/3ud1pb

**Comment by xuchen** [comment]
from beginning: `import subprocess`

**Comment by jaydev1997** [comment]
Got an error command specified in subprocess executes at script runtime see log here.. http://goo.gl/KeKL7X

**Comment by xuchen** [comment]
you should wrap your callback in a lambda function:

```
callbacks = [lambda: subprocess.check_call(["ls", "-l"])]
```

**Comment by jaydev1997** [comment]
so everything in subprocess " "  will execute right... also a other python scripts?

**Comment by xuchen** [comment]
yes; i'm going offline now, good luck!
