### ISSUE TITLE
Quick help on compiling a supported swig version!

### ISSUE THREAD

**Issue by meischdaddy30** [Kitt-AI/snowboy#453]
I'm new to all of this coding stuff, I'm trying to install snowboy and I'm stuck on this step:

Compile a supported swig version (3.0.10 or above)

```
wget http://downloads.sourceforge.net/swig/swig-3.0.10.tar.gz
sudo apt-get install libpcre3 libpcre3-dev
./configure --prefix=/usr                  \
        --without-clisp                    \
        --without-maximum-compile-warnings &&
make
make install &&
install -v -m755 -d /usr/share/doc/swig-3.0.10 &&
cp -v -R Doc/* /usr/share/doc/swig-3.0.10
```

could someone let me know how I can execute this entire thing?  I got the "wget http://downloads.sourceforge.net/swig/swig-3.0.10.tar.gz" and "sudo apt-get install libpcre3 libpcre3-dev".  But I don't know how to do the rest :(.  

Thank you in advance!

**Comment by Sean-Amor** [comment]
Did anyone figure this out, I too am confused on this step.
