### ISSUE TITLE
The web site is down.

### ISSUE THREAD

**Issue by alexyak** [Kitt-AI/snowboy#46]
When's your web site is coming back online? I need to generate new voice commands.

**Comment by xuchen** [comment]
we are working on improving the performance and expecting to bring it back by EOW!

**Comment by xuchen** [comment]
the website is up now with much improved speed

**Comment by alexyak** [comment]
When I try to record the hotword, it always stays on a first step recording. There's no way to move to the next step.

**Comment by chenguoguo** [comment]
What was your browser? We only support Firefox and Chrome at this point.

When you said "first step recording" did you mean that you were not able to
click on the "Test the model" button? Were you able to play the recorded
audio back to you and if yes did they sound good?

**Comment by alexyak** [comment]
Sorry, my mike was disabled for some reason. It's working now.
