### ISSUE TITLE
Plz help, i'm newbee...Can't make swig/Python3

### ISSUE THREAD

**Issue by TrongSang0208** [Kitt-AI/snowboy#462]
(venv) pi@raspberrypi:~/SpeechTest $ cd snowboy/swig/Python3
(venv) pi@raspberrypi:~/SpeechTest/snowboy/swig/Python3 $ sudo make
swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
g++ -I/usr/include/python3.5m -I/usr/include/python3.5m  -Wno-unused-result -Wsign-comp           are -g -fdebug-prefix-map=/build/python3.5-RUbMX3/python3.5-3.5.3=. -fstack-protector-s           trong -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototyp           es -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not            for C++
g++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x  -shared snowboy-detect-sw           ig.o \
../..//lib/rpi/libsnowboy-detect.a -L/usr/lib/python3.5/config-3.5m-arm-linux-gnueabihf            -L/usr/lib -lpython3.5m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -           Wl,-Bsymbolic-functions -lm -ldl -lf77blas -lcblas -llapack -latlas -o _snowboydetect.s           o
/usr/bin/ld: cannot find -lf77blas
/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
Makefile:73: recipe for target '_snowboydetect.so' failed
make: *** [_snowboydetect.so] Error 1

**Comment by TmpName** [comment]
/usr/bin/ld: cannot find -latlas > have you installed atlas lib ?

**Comment by TrongSang0208** [comment]
Thanks Everyone, i had fix error

**Comment by hongquan** [comment]
@TrongSang0208 Please close this issue after you have found the fix.
