### ISSUE TITLE
Please Help!  MMM-Assistant Jarvis.umdl

### ISSUE THREAD

**Issue by meischdaddy30** [Kitt-AI/snowboy#463]
I just got my MMM-Assistant fully working with snowboy.umdl and the last step I would like to do is change my hotword to jarvis instead of snowboy.  I attempted designating my path to the jarvis.umdl with the removed license but I'm still getting this 

`/home/pi/.pm2/logs/MagicMirror-error-0.log last 15 lines:
0|MagicMir | (process:8496): Gtk-WARNING **: Locale not supported by C library. 

0|MagicMir | 	Using the fallback 'C' locale.
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | ERROR (CheckLicense():universal-detect-stream.cc:1391) Your license for Snowboy has been expired. Please contact KITT.AI at snowboy@kitt.ai
0|MagicMir | terminate called after throwing an instance of 'std::runtime_error'
0|MagicMir |   what():  ERROR (CheckLicense():universal-detect-stream.cc:1391) Your license for Snowboy has been expired. Please contact KITT.AI at snowboy@kitt.ai
0|MagicMir | 
0|MagicMir | [stack trace: ]
0|MagicMir | Backtrace has not been implemented yet.
0|MagicMir | 
0|MagicMir | 
0|MagicMir | (process:8621): Gtk-WARNING **: Locale not supported by C library.
0|MagicMir | 	Using the fallback 'C' locale.
`

Can somebody please help me out?

**Comment by pallaviMN** [comment]
@meischdaddy30 , i too faced this issue in iOS build, any solution for that?
