### ISSUE TITLE
PLEASE HELP URGENT - doesn't compile 

### ISSUE THREAD

**Issue by devshaaran** [Kitt-AI/snowboy#467]
`$ sudo make`

      g++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x  -shared snowboy-detect-swig.o 
      \../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu - 
      L/usr/local/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -lm -ldl -lf77blas -lcblas - 
      llapack -latlas -o _snowboydetect.so
      /usr/bin/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(abstract.o): 
      relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a    
      shared object; recompile with -fPIC
      /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a: error adding symbols: Bad 
      value
      collect2: error: ld returned 1 exit status
      Makefile:73: recipe for target '_snowboydetect.so' failed
      make: *** [_snowboydetect.so] Error 1

Tried everything but in vain, it complied `sucessfully for python2` but when I import snowboydecoder I get this error

Able to import snowboy 

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import snowboy
>>> quit()

not able to import snowbowdecoder

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import snowboydecoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named snowboydecoder
>>> quit()

system Specs :

Ubuntu Gnome 16.04
Python 3.6.4

**Comment by hongquan** [comment]
Any reason why do you compile with "sudo"?

Why "import snowboydecoder". This module simply doesn't exist.

**Comment by devshaaran** [comment]
snowboydecoder exists right ? its used in the example files.. 

`snowboy > examples > Python3|Python > example.py`

I don't use `sudo` since I am in my venv and using sudo makes it installed to the system interpreter

**Comment by hongquan** [comment]
> I don't use sudo since ...

Then what is this?

![image](https://user-images.githubusercontent.com/314607/42569883-42e13730-853c-11e8-8160-cd6d492c4d6e.png)

> snowboydecoder exists right

These are the modules installed by `snowboy`:

https://github.com/Kitt-AI/snowboy/blob/3f5f9441e5dc7b0cfcd422fd361aa98902037061/setup.py#L50

**Comment by devshaaran** [comment]
oh , sorry got it fixed ! thanks
