### ISSUE TITLE
Unable to make on openSUSE

### ISSUE THREAD

**Issue by cbcoutinho** [Kitt-AI/snowboy#48]
I'm unable to make the python wrapper on my opensuse machine.

Specifically, I run into an error with 3 libraries (f77blas, lapack_atlas, and atlas):

```
>>> make
g++ -I../../ -O3 -fPIC -std=c++0x -L/usr/lib64/ -shared snowboy-detect-swig.o \
../..//lib/ubuntu64/libsnowboy-detect.a -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas -o _snowboydetect.so
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -lf77blas
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -llapack_atlas
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
make: *** [Makefile:51: _snowboydetect.so] Error 1
```

One thing I did was add '-L/usr/lib64' as an additional flag in the hopes of finding these libraries, and that did work for cblas, but unfortunately that doesn't seem to have worked for the remaining 3.

Does anyone have an idea of what the issue may be? Do I need to compile blas, lapack and atlas on my own!? I would rather not...

**Comment by chenguoguo** [comment]
Hi, you'll likely have to install Atlas, probably using some pre-compiled packages. However, we have only compiled Snowboy for Ubuntu 14.04 (64 bit), OS X, Raspbian based on Debian Jessie 8.0, so I'm not sure if it will work on your openSUSE machine at all... if you give it a shot, please let us know.
