### ISSUE TITLE
No module snowboydecoder

### ISSUE THREAD

**Issue by yukysky** [Kitt-AI/snowboy#482]
i've been doing :
`python demo.py ~/snowboy/resources/model.pmdl
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
ImportError: No module named snowboydecoder`

I tried to do what other posts said, nothing worked and still the same issues.
I'm currently working with a raspberry pi 3 on the latest raspbian.
Cordially Yuky

**Comment by tutaf** [comment]
Hi. Please give a bit more info: what version of python are you using, you used a precompiled wraper for raspberry or built it yourself, are all required libraries installed, possible you can add something? Some days ago I did it on my pi 3b+, it is possible and not so difficult.
