### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by MathiasDesch** [Kitt-AI/snowboy#51]
Just to let you know that the documentation on the website is not up to date concerning the demo code.

It is showing 
`detector.start(detected_callback=snowboydecoder.ding_callback,
               interrupt_check=interrupt_callback,
               sleep_time=0.03)`

Where it changed to 
`snowboydecoder.play_audio_file`

Great tool !

**Comment by chenguoguo** [comment]
Thanks! Fixed, will appear in the next deployment!
