### ISSUE TITLE
unexpected kwargs

### ISSUE THREAD

**Issue by jhludwig** [Kitt-AI/snowboy#53]
when i try to run interactively as suggested, i get this error:

```>>> detector = snowboydecoder.HotwordDetector("resources/snowboy.umdl", sensitivity=0.5, audio_gain=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snowboydecoder.py", line 91, in __init__
    resource_filename=resource, model_str=model_str)
TypeError: __init__() got an unexpected keyword argument 'model_str'```

it looks to me like snowboydecoder is sending in kwargs, but snowboydetect expects args?

**Comment by chenguoguo** [comment]
Did you use Swig to compile the Python library? This might help: https://github.com/Kitt-AI/snowboy/issues/17

**Comment by jhludwig** [comment]
yes i did.  I just repeated the swig build process to be sure.  isn't the problem the mismatch between kwargs and args?  the call in snowboydecoder is:  
```
self.detector = snowboydetect.SnowboyDetect(resource_filename=resource, model_str=model_str)
```

but snowboydetect is expecting args:  
```
def __init__(self, *args):
```

**Comment by jhludwig** [comment]
ps i just edited snowboydecoder to use args instead of kwargs and it seems to work much better.  i believe that is the problem.

**Comment by chenguoguo** [comment]
OK snowboydetect.py is generated by swig and usually it does the kwargs to args conversion when it calls the C++ library. But it's good to know that it's working.

**Comment by jhludwig** [comment]
well it is failing later on, so it is possible that fixing the mismatch in arg conventions just allowed the problem to manifest later on.  i am not swig-conversant, i am not quite sure how to fix the swig issue

**Comment by chenguoguo** [comment]
what is your os? please also try `which swig` to make sure your swig version is above 3.0. Sometimes people have default swig installed.

**Comment by jhludwig** [comment]
debian jessie.  the swig version does not seem to be the issue.

the swig version from the debian repos is:  

```john@caseless:/demo/snowboy/examples/Python$ swig -version

SWIG Version 2.0.12```

swig 3.0 is separately installed as `swig3.0`.  i modified the makefile to use swig3.0 but the generated snowboydetect still is expecting args, not kwargs.

**Comment by chenguoguo** [comment]
yes the generated snowboydetect will be expecting args but swig should be able to handle internally.

It's very wired that using swig3.0 still does not help. What about trying the pre-compiled version from here: https://snowboy.kitt.ai/docs

**Comment by jhludwig** [comment]
the pre-compiled version has a different function signature for the __init__ routine:

```
def __init__(self, resource_filename, model_str):
```
vs the `*args` version that i am seeing above.  this does work better, i am having now some sound card issues but your lib seems to work.

**Comment by chenguoguo** [comment]
OK I misread my swig file. Yes the init function should expect the kwargs function signature. I'm not sure what happened with your swig conversion, but at least you can use the pre-compiled version.
