### ISSUE TITLE
NodeJS Module fails to initialize: undefined symbol: cblas_sdot

### ISSUE THREAD

**Issue by arilotter** [Kitt-AI/snowboy#54]
Hi, I can't get the current version of snowboy (as published on npm) working. Running `examples/node/microphone.js` crashes with `node: symbol lookup error:  .../node_modules/snowboy/lib/node/binding/Release/node-v48-linux-x64/snowboy.node: undefined symbol: cblas_sdot`

I've made sure I have libatlas-base-dev installed, but I thought I wouldn't need it because of the precompiled binaries.

Also, manually compiling by running `node-pre-gyp --build-from-source` doesn't resolve the issue.

I can reproduce this with the following example on Ubuntu 16.04.
```js
const record = require('node-record-lpcm16');
const snowboy = require('snowboy');

const models = new snowboy.Models();
models.add({
  file: 'resources/snowboy.umdl',
  hotwords: 'snowboy'
});

const detector = new snowboy.Detector({
  resource: 'resources/common.res',
  models
});
record.start().pipe(detector);
```

**Comment by chenguoguo** [comment]
I just started playing with this module. @nekuz0r and @evancohen might have a better clue.

**Comment by nekuz0r** [comment]
@arilotter I am looking into it.

**Comment by arilotter** [comment]
@nekuz0r if you need help reproducing or anything, I can reliably cause the issue to happen!

**Comment by nekuz0r** [comment]
@arilotter I can reproduce, but i cannot figure out why the cblas library is not linked.
`ldd` on `snowboy.node` will show the cblas library is not linked, which is not the case on osx.
also `nm` on `snowboy.node` will also reveal the symbol are not statically linked.
So clearly there is an issue at link time, still investigating when i have time to.

**Comment by MexXxo** [comment]
Has the same issue, I fixed it with installing these packages:

> sudo apt-get install libatlas-base-dev libatlas3gf-base

now it's working like a charm, again thanks to @evancohen and @nekuz0r !
