### ISSUE TITLE
Precompiled URL Access Denied

### ISSUE THREAD

**Issue by lmEshoo** [Kitt-AI/snowboy#56]
https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.1.0.tar.bz2

I get access denied

**Comment by chenguoguo** [comment]
Fixed.

**Comment by s-ramirez** [comment]
I'm currently getting this same error on:

https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.1.0/Release/snowboy-v1.1.0-node-v51-linux-arm.tar.gz

**Comment by chenguoguo** [comment]
@s-ramirez Hi, we only compiled Snowboy for Node 4, 5 and 6, most likely you have a higher version. For the future release, we will try to support the new node versions.
