### ISSUE TITLE
Installing SnowBoy

### ISSUE THREAD

**Issue by eliotabrams** [Kitt-AI/snowboy#570]
Could someone explain how to install SnowBoy for use with Python 3.7 on macOS Mojave?

Do I need to download a directory, edit a makefile, and build from scratch? If so, from where and how? I've tried to make the swig/Python3 file from the github, but get the error:
```
(base) Eliot-Abramss-Laptop:Python3 eliotabrams$ make
clang++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0  -bundle -flat_namespace -undefined suppress snowboy-detect-swig.o \
	../..//lib/osx/libsnowboy-detect.a -L/anaconda3/lib/python3.7/config-3.7m-darwin -lpython3.7m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation -lm -ldl -framework Accelerate -o _snowboydetect.so
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [_snowboydetect.so] Error 1
```

I can pip install or use the pre-built binary, but then I get the error
```
ImportError: dynamic module does not define module export function (PyInit__snowboydetect)
```

Thanks for any and all help!

**Comment by eliotabrams** [comment]
Got it. Needed to update the path in the makefile

**Comment by Sean-Amor** [comment]
How did you install snowboy, I'm not sure what to do with the ZIP file. I was able to install pyaudio, python 3, sox, and successfully ran the rec test, but I can't get any further. Also if you explain how to install snowboy, how do I run a code, and once it runs will it always looks listen if the device is booted? any help is greatly appreciated I'd love to learn how to install on Mac as well as a raspberry pi.

**Comment by c-box** [comment]
> Got it. Needed to update the path in the makefile

I met the same problem, could you please describe your solution?
