### ISSUE TITLE
compiled _snowboydetect.so: ImportError: dynamic module does not define module export function

### ISSUE THREAD

**Issue by jbrepogmailcom** [Kitt-AI/snowboy#597]
Hello, I have compiled Python _snowboydetect.so for Orange Pi Zero Armbian Stretch. Then I placed the compiled .so file in the demo.py folder.

I get this error:

(env) pi@orangepizero:~/snowboy1$ python demo.py resources/snowboy.umdl
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
  File "/home/pi/snowboy1/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/snowboy1/snowboydetect.py", line 15, in <module>
    import _snowboydetect
ImportError: dynamic module does not define module export function (PyInit__snowboydetect)

**Comment by SrDayne** [comment]
Hi. I had the same error. Try to run with python3:
python3 demo.py resources/snowboy.umdl

**Comment by jbrepogmailcom** [comment]
I got it working by using not demo.py, but the script listed in installation guide.
