### ISSUE TITLE
Java library

### ISSUE THREAD

**Issue by XXLTomate** [Kitt-AI/snowboy#62]
A swig java library would simplify the workflow for java projects.

**Comment by chenguoguo** [comment]
Please follow the discussion forum here: https://groups.google.com/a/kitt.ai/forum/#!topic/snowboy-discussion/2tgenslIm6w

People are working on it, but it's not working properly yet.

**Comment by chenguoguo** [comment]
I added the Java wrapper since people have interest in this. Please checkout the `swig/Java` and `examples/Java` in the `devel` branch.

Please give it a try; if it works for you I'll merge it to master. @XXLTomate

**Comment by chenguoguo** [comment]
Slatroz has tested the Java binding, so I'll close this and merge it to master.
