### ISSUE TITLE
Certificate of https://snowboy.kitt.ai/ is outdated

### ISSUE THREAD

**Issue by Sispheor** [Kitt-AI/snowboy#624]
Since first December 2019.

**Comment by PovilasKulevicius** [comment]
Are you able to create a hotword?

**Comment by Sispheor** [comment]
I haven't tried.

**Comment by chenguoguo** [comment]
Will fix it today.

**Comment by nhpunch** [comment]
@chenguoguo 

When will it be fixed?
........plz

**Comment by johanneskropf** [comment]
Any news on this? Would be great to be able to use the script again. I cant make it work on the the website either right now. The last step always fails.

**Comment by junhee-cavuai** [comment]
Create hotword does not work.
When will it be fixed?
........plz..

**Comment by thomaslocher** [comment]
I don't know if the outdated certificate is the problem but creating hotwords does not work for me either:
- When recording, the wiggly line appears in the circle but I can never record a second sample.
- When uploading my own wave files, I can test the model but it never accepts it, regardless of sensitivity.

**Comment by chenguoguo** [comment]
It's been fixed now. Sorry for the delay guys...
