### ISSUE TITLE
Website broken/does not work for creating new wake words right now

### ISSUE THREAD

**Issue by johanneskropf** [Kitt-AI/snowboy#627]
I don't know if this is connected to or a separate issue to the ssl one. 
But I'm experiencing the same on my end as described by @thomaslocher here:
I don't know if the outdated certificate is the problem but creating hotwords does not work for me either:
- When recording, the wiggly line appears in the circle but I can never record a second sample.
- When uploading my own WAV files, I can test the model but it never accepts it, regardless of sensitivity.

_Originally posted by @thomaslocher in https://github.com/Kitt-AI/snowboy/issues/624#issuecomment-562474945_

**Comment by chenguoguo** [comment]
Yes it's connected to the ssl issue. It has been fixed now. Sorry about that.
