### ISSUE TITLE
IOError: [Errno Invalid sample rate] -9997 SOLVED

### ISSUE THREAD

**Issue by ignitefoundation** [Kitt-AI/snowboy#65]
Hi,
I have read all the issues on this, but it still does not work for me, I am using a Raspberry Pi 2 and have tested 4 microphones, but only 1 works with Snowboy - the PS3 EYE.

A list of all the microphones I used as follows -

1. - Samson UB1
2. - Logitech QuickCam Orbit 
3. - Cheap USB microphone off Amazon

All microphones above work and record with no errors using REC temp.wav within the comand line, and also work within a python script using PyAudio open using 16000. I have updated the ~/.asoundrc with -

pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

Have you got a new version out yet not on github if so please leave a link for testing ;-)

Thanks in advance

**Comment by chenguoguo** [comment]
Hmm that's very wired; so you were able to use a python script with PyAudio sampling at 16000, but when you tested Snowboy it gave `IOError: [Errno Invalid sample rate] -9997`? Snowboy uses PyAudio in the script and if PyAudio works it should work. Could you paste your python script using PyAudio?

**Comment by ignitefoundation** [comment]
Hi,
The following code is only a part of it but it should show how I use PyAudio -

```
def Loop(self):
       self.detector.terminate()
        self._audio = pyaudio.PyAudio()
        RATE = 16000
        CHUNK = 1024
        LISTEN_TIME = 10
        didDetect = False
        frames = []
        THRESHOLD = self.AmbientLevel(1.8)
        print THRESHOLD
        lastN = [THRESHOLD * 1.2 for i in range(30)]
        print "Ready................."
        subprocess.call(['aplay', '-D', 'hw:0,0', 'media/start.wav'], shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stream = self._audio.open(format=pyaudio.paInt16,channels=1,rate=RATE,input=True,frames_per_buffer=CHUNK)
        for i in range(0, RATE / CHUNK * LISTEN_TIME):
            data = stream.read(CHUNK)
            frames.append(data)
            average = sum(lastN) / float(len(lastN))
            volumelevel = self.getVolumeLevel(data)
            lastN.pop(0)
            lastN.append(volumelevel)
            if average < THRESHOLD:
                didDetect = True
                break
        if didDetect:
            with tempfile.SpooledTemporaryFile(mode='w+b') as f:
                wav_fp = wave.open(f, 'wb')
                wav_fp.setnchannels(1)
                wav_fp.setsampwidth(pyaudio.get_sample_size(pyaudio.paInt16))
                wav_fp.setframerate(RATE)
                wav_fp.writeframes(''.join(frames))
                wav_fp.close()
                f.seek(0)
                stream.stop_stream()
                stream.close()
                try:
                    print "heard"
                    subprocess.call(['aplay', '-D', 'hw:0,0', 'media/stop.wav'], shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                except:
                    print "Not Heard"
        stream.stop_stream()
        stream.close()
        self.Loop()
```

**Comment by chenguoguo** [comment]
So it seems to me that the noticeable difference is the callback function. In Snowboy we used the callback function to record audio, see the following part in the Snowboy [script](https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/snowboydecoder.py):

```
        self.stream_in = self.audio.open(
            input=True, output=False,
            format=self.audio.get_format_from_width(
                self.detector.BitsPerSample() / 8),
            channels=self.detector.NumChannels(),
            rate=self.detector.SampleRate(),
            frames_per_buffer=2048,
            stream_callback=audio_callback)
```

Could you please play with the PyAudio initialization part in our script and see if you can figure out the issue? It has been working for us so it's a bit difficult for us to do the debugging on our side. It issue is PyAudio related. If you can figure it out, that's gonna be a HUGE help to us!

**Comment by ignitefoundation** [comment]
Hi,
I have played with this setting and nothing changes, I add in suggestions from other posts around the net and changed the existing settings, I copied my self.audio.open in there but still had the same errors.

I am using 2016-09-23-raspbian-jessie-lite image with all things updated. I will try another Raspbian image to see what happens

**Comment by chenguoguo** [comment]
OK thanks a lot @ignitefoundation ! So what really bugs me is that PyAudio works with your script but does not work with the Snowboy script, and the error message clearly comes from PyAudio. So it's more likely to be a PyAudio setting issue. Perhaps by carefully adapting the Snowboy script to your working script, we will make it work eventually, and this may solve the issue that has been around for a while.

**Comment by ignitefoundation** [comment]
Just doing the testing with other images, I will report back soon ;-)

**Comment by ignitefoundation** [comment]
Got it and you would not believe what it was. There is nothing wrong with your script, it is how we are running the python script.

Just don't put sudo in front of the command -

Wrong -
sudo python demo.py resources/alexa.umdl

Right -
 python demo.py resources/alexa.umdl

Hope this helps everyone ;-)

**Comment by chenguoguo** [comment]
OMG I can't imagine that was the issue, thanks a million @ignitefoundation !!!

Regarding the script change, I was hoping the new script will work with Python3 (if you compile the Python bindings using swig/Python/Makefile with Python3), but I've only tested this on my side, and seems like no one is really using it.

Closing the issue, thanks!
