### ISSUE TITLE
Training personal wake word after platform shutdown

### ISSUE THREAD

**Issue by mathquis** [Kitt-AI/snowboy#650]
Hi.

Since Kitt.ai will be shutting down their platform at the end of the year, maybe some kind of tool could be published to allow the creation of personal wake words like the API does but locally.

This will let users continue to use Snowboy after the shutdown.

Thanks.

**Comment by vovodroid** [comment]
Bump the issue @chenguoguo 

Joining the question

**Comment by 17702513221** [comment]
me too

**Comment by xu-sheng-jie** [comment]
现在唤醒词怎么修改？
