### ISSUE TITLE
Create a custom wakeword?

### ISSUE THREAD

**Issue by sffranke** [Kitt-AI/snowboy#658]
Hi all, 
Anybody is able to create a custom wakeword at https://snowboy.kitt.ai/dashboard?
My microphone works but its impossible to record my voice, was trying Firefox, Chrome under Linux and even Windows without success. I am logged in using my Github account.

TIA, Steffen

**Comment by ChanJun-Park** [comment]
I have experienced same issue. I also tested chrome, firefox in ububtu and windows but it didn't work. 

Please check this issue.

**Comment by Dalkei** [comment]
I've been able to record without issue, but there's not really any point anymore, considering that Kitt.ai is shutting down this year.

**Comment by sffranke** [comment]
Works nicely now, thank you.
Anybody can confirm that Kitt.ai is shutting down this year? I can't find any information about it.

**Comment by ChanJun-Park** [comment]
> Works nicely now, thank you.
> Anybody can confirm that Kitt.ai is shutting down this year? I can't find any information about it.

You can check the information about shutting down at this repository's README.md file
