### ISSUE TITLE
Library Import Issues on armv7l

### ISSUE THREAD

**Issue by jhoelzl** [Kitt-AI/snowboy#66]
Hello,

i want to run the demo script on armv7l.

So, on my Ubuntu 14.04 i go to the snowboy repository folder `lib/android/armv7a` https://github.com/Kitt-AI/snowboy/tree/master/lib/android/armv7a and run: 

`gcc-4.8 -m32 -shared -o _snowboydetect.so libsnowboy-detect.a`

The i copied the file `_snowboydetect.so` to armv7l.

When i run `demo.py` on armv7l, i always get this message:

> Traceback (most recent call last):
>   File "demo.py", line 1, in <module>
>     import snowboydecoder
>   File "/root/snowboy/snowboydecoder.py", line 5, in <module>
>     import snowboydetect
>   File "/root/snowboy/snowboydetect.py", line 28, in <module>
>     _snowboydetect = swig_import_helper()
>   File "/root/snowboy/snowboydetect.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_snowboydetect', fp, pathname, description)
> ImportError: /root/snowboy/_snowboydetect.so: cannot open shared object file: No such file or director

However, the file `/root/snowboy/_snowboydetect.so` is existent, executable and has file permissions `775`.

When i run 

`gcc-4.8 -shared -o _snowboydetect.so libsnowboy-detect.a`

(without `-m32)` , of course, i get this error:

> Traceback (most recent call last):
>   File "demo.py", line 1, in <module>
>     import snowboydecoder
>   File "/root/snowboy/snowboydecoder.py", line 5, in <module>
>     import snowboydetect
>   File "/root/snowboy/snowboydetect.py", line 28, in <module>
>     _snowboydetect = swig_import_helper()
>   File "/root/snowboy/snowboydetect.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_snowboydetect', fp, pathname, description)
> ImportError: /root/snowboy/_snowboydetect.so: wrong ELF class: ELFCLASS64

But here, it seems that the file `/root/snowboy/_snowboydetect.so` was imported at least.

Any suggestions?
Regards, Josef

**Comment by chenguoguo** [comment]
That doesn't seem the right way to do. The android version of library was prepared for Android. You should probably try the Raspberry Pi version, but that was compiled on Raspbian. You may also try the pre-compiled library for Ubuntu.

Also, to generate _snowboydetect.so, you have to use script under swig/Python. Please follow the github README page.

**Comment by jhoelzl** [comment]
Hello @chenguoguo, thanks for feedback!

I also tried the Raspery Pi version, but the error remains the same.

When i run:

```
cd swig/Python
make
```
on Ubuntu 14.04, of course, the generated file `_snowboydetect.so` works on Ubuntu 14.04, but not on armv7l:
> ImportError: /root/snowboy/_snowboydetect.so: wrong ELF class: ELFCLASS64

How should i modify the makefile in order to get a working module for armv7l?

**Comment by chenguoguo** [comment]
I'm afraid we don't have a solution for now. 

The Raspberry Pi library was compiled on arm processors but with Raspbian (Debian 8).

The Ubuntu library was compiled on x86_64 processors with Ubuntu 14.04.

In your case, you probably have arm processor with some other OS (what's your OS?) which we don't support.

**Comment by jhoelzl** [comment]
`cat /etc/*-release` returns:

> ID=elito
> NAME=ELiTo
> VERSION=0.93.20160525T142730
> VERSION_ID=0.93.20160525T142730
> PRETTY_NAME=ELiTo 0.93.20160525T142730

**Comment by chenguoguo** [comment]
I believe we don't support that, sorry...
