### ISSUE TITLE
Cannot obtain token while training a new hotword model

### ISSUE THREAD

**Issue by linuscyl** [Kitt-AI/snowboy#685]
Hello, as the shutdown of Snowboy website, I cannot login and obtain the token as instructed.  
However, the RESTful API that train a hotword model requires a token as params.
Hence, no more new pmdl can be generated.  Thank you.

**Comment by michaelbeljaars** [comment]
Same issue here. I am not even sure if the API is still available. I don't see how we can train new models without this functionality.

**Comment by michaelbeljaars** [comment]
see  #679

**Comment by linuscyl** [comment]
Thanks @michaelbeljaars !  It works!  I can generate a custom pmdl file now.
