### ISSUE TITLE
add snowboy lib to PyPI with a setup.py

### ISSUE THREAD

**Issue by Sispheor** [Kitt-AI/snowboy#73]
Currently, when you release a new version of Snowboy we have to get binaries file, and the python wrapper you provide and push all that stuff in our project. 
It could be very useful to have a python lib with a setup.py installation and push everything on a pip repo.

**Comment by chenguoguo** [comment]
Thanks for the suggestion, we'll keep that on our list. In the meanwhile, if you plan to take that responsibility and work on that, you are more than welcome to send us a pull request. Folks have worked on that route for the Node module, see here: https://github.com/Kitt-AI/snowboy/pull/52

**Comment by xuchen** [comment]
I researched about it with pip install but gave up. The problem was to differentiate different architects: we have to provide binaries for RPi, Linux, Mac but not Windows. You are very welcome to give it a try!

**Comment by Sispheor** [comment]
Ok I'll take a look into this.

**Comment by renekliment** [comment]
@Sispheor Hello. Any progress on this? This would make our lives easier over at @alexa-pi and probably to many other people :)

**Comment by chenguoguo** [comment]
It was addressed by https://github.com/Kitt-AI/snowboy/tree/master/examples/Python3, thanks to @leosampaio . I'm closing this.

**Comment by Sispheor** [comment]
Great job!
I don't see the package on [Python Pip](https://pypi.python.org/pypi?%3Aaction=search&term=snowboy&submit=search) yet. Do you plan to push it?

**Comment by chenguoguo** [comment]
I'll try to see what needs to be done to publish it. For now you can use

```
python setup.py build
python setup.py install
```

**Comment by Sispheor** [comment]
I used this page to do it for myself.
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by renekliment** [comment]
Or you can use `pip install git+https://github.com/Kitt-AI/snowboy` in the meantime.

**Comment by Sispheor** [comment]
Yes, but actually I want to add snowboy to the setup.py of my program as
dependency.

**Comment by Sispheor** [comment]
Thank you very much! I'll give a try.
