### ISSUE TITLE
Typo in error message from API when wav is too short

### ISSUE THREAD

**Issue by alexylem** [Kitt-AI/snowboy#74]
There is a typo in the error message when the wav is too short
Using enpoint: `https://snowboy.kitt.ai/api/v1/train/`
```json
{"voice_samples":[{"wave":["Hotowrd is too short"]},{"wave":["Hotowrd is too short"]},{"wave":["Hotowrd is too short"]}]}
```
`Hotowrd` ➡️  `Hotword`

**Comment by chenguoguo** [comment]
Thanks! Fixed in the code, will be out in the next deployment.
