### ISSUE TITLE
Train API responds UniversalHotword with this name already exists

### ISSUE THREAD

**Issue by alexylem** [Kitt-AI/snowboy#75]
Hello,

I'm using the train API to train a personal model for hotword "jarvis".
`https://snowboy.kitt.ai/api/v1/train/`

``` json
{
    "name": "jarvis",
    "language": "fr",
    "microphone": "Default",
    "token": "XXX",
    "voice_samples": [
        {"wave": ...
```

The API responds

``` json
{"universal_hotword":{"name":["UniversalHotword with this name already exists."]}}
```

Although it only has 126/500 samples.
![image](https://cloud.githubusercontent.com/assets/11017174/19412764/04210236-931d-11e6-8ad9-05721048a365.png)

And even if it is a universal model, why not returning it 😄 
Many thanks for your help,

**Comment by chenguoguo** [comment]
Ah that piece of message is a little bit misleading; it actually means we already have a record of the universal hotword (so that in the future we can create it), and it doesn't mean that we've already trained the universal hotword model

**Comment by alexylem** [comment]
Thanks for your answer. Would it be possible in that situation to get from the API the actual `.pmdl` file for that hotword? This error seems to be blocking.

**Comment by chenguoguo** [comment]
how did you submit the samples? I just had a try with the hotword `snowboy` (which is also in the library) using https://github.com/Kitt-AI/snowboy/blob/master/examples/REST_API/training_service.sh and it worked.

**Comment by alexylem** [comment]
I don't use your script as-is, it's integrated in the core of Jarvis program.
But I follow the same principle (curl + json data including based64 wavs).
Here is [the script](https://github.com/alexylem/jarvis/blob/master/stt_engines/snowboy/main.sh#L87).
Apart from Gender and Age-Group (non-required) I have all the information in the JSON.
Just tested to train `snowboy` and I have the same result:
```bash
$> head -n 4 /tmp/data.json
{
    "name": "snowboy",
    "language": "fr",
    "microphone": "Default",
    [...]

$> curl "https://snowboy.kitt.ai/api/v1/train/" \
        --progress-bar \
        --header "Content-Type: application/json" \
        --data   @/tmp/data.json \
        --write-out "%{http_code}" \
        --output /tmp/model.pmdl

$> cat /tmp/model.pmdl
{"universal_hotword":{"name":["UniversalHotword with this name already exists."]}}
```
I have no issue training other models. The received models, for any other hotword than `jarvis` & `snowboy`, just work fine.

**Comment by alexylem** [comment]
Just used your script, I have the same result:
```bash
$> ./training_service.sh 1.wav 2.wav 3.wav jarvis
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2379k  100    82  100 2379k      2  80971  0:00:41  0:00:30  0:00:11 41899
$> cat jarvis 
{"universal_hotword":{"name":["UniversalHotword with this name already exists."]}}
```

**Comment by chenguoguo** [comment]
This does seem to be a bug when you use a language other than English. We'll try to fix. Thanks.

**Comment by alexylem** [comment]
Forcing the language to `en` in my app (works fine) until this is fixed. Thanks!

**Comment by chenguoguo** [comment]
This should be fixed now! Closing the issue.

**Comment by alexylem** [comment]
Tested and working, thanks!

**Comment by chenguoguo** [comment]
@alexylem there's a bug in the new code so I had to roll back to the old version. You may still see your reported bug. We'll deploy again tomorrow.

**Comment by chenguoguo** [comment]
Closing as the issue has been resolved.
