### ISSUE TITLE
Uses 50% CPU on my raspberry pi 1

### ISSUE THREAD

**Issue by williewh** [Kitt-AI/snowboy#76]
Hi, any tips on improving the CPU usage of snowboy? I'm running it with a single pdml. Starting snowboy with python2 helps it some but it still hovers around 48% to 55% CPU Usage. I have a Wolfson audio card.

**Comment by chenguoguo** [comment]
That is surprising. What is the size of your pmdl model? Have you tried USB microphones?

**Comment by williewh** [comment]
The pmdl model is 10 bytes. I realized that the 50% CPU happens in a noisy environment. In a quiet room, CPU Usage is 25%. I will try a USB mic and report results.

**Comment by xuchen** [comment]
This looks normal to me given a weak CPU of RPi 1.

**Comment by williewh** [comment]
Okay, that's good enough for me. Thank you. Closing.

**Comment by chenguoguo** [comment]
A 25% CPU usage in quiet environment indicates high computation even without detection. Two things to check:

1. Are you using Amazon's Alexa sample application? If yes, then `ApplyFrontend(true)` is called, and the 25% CPU usage will make sense.

2. At least try a different USB microphone. I've experienced things like different audio capturing settings contributes to e.g. 10% of the CPU usage.

**Comment by williewh** [comment]
Along with the 50% CPU, I was getting a lot of false-positives for one word, computer. I'll experiment with the gain settings and other configs. I certainly haven't given up on snowboy, I think it's the best. However, if I want to run snowboy, a node script and mopidy simultaneously, I know I'll need speedier hardware.

**Comment by chenguoguo** [comment]
Yes, also the sensitivity, that controls the tradeoff between detection rate and false alarms.

**Comment by Smanar** [comment]
For information I m using a Raspberry B+, used with c++, 10ko pdml.
All the application with snowboy take around 4% to 10% CPU Usage. But generally it's under 6%.

**Comment by chenguoguo** [comment]
That is surprising. What is the size of your pmdl model? Have you tried USB
microphones?

Guoguo

**Comment by chenguoguo** [comment]
even 25% seems way too high. are you sure it's 10 bytes not 10 kilo bytes?
