### ISSUE TITLE
make fails - Ubuntu 16.10 amd64

### ISSUE THREAD

**Issue by ds3ctor** [Kitt-AI/snowboy#77]
Any suggestions?

/usr/bin/ld: ../ext/lib/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 40)
../ext/lib/libsnowboy-detect.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/wakeWordAgent.dir/build.make:409: recipe for target 'wakeWordAgent' failed
make[2]: **\* [wakeWordAgent] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: **\* [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by chenguoguo** [comment]
The library we provided to the Alexa sample application was compiled for Raspberry Pi with Raspbian (a Debian variant), so likely it won't work on your Ubuntu 16.10 with amd64 CPU.

**Comment by ds3ctor** [comment]
Thanks for the quick response. Will Ubuntu amd64 be supported in the future? Or are there any workarounds?

**Comment by chenguoguo** [comment]
First, you have to make sure that our Ubuntu library works on your platform. Checkout our repository and check the demos.

Second, if our library works on your platform, you can modify `https://github.com/alexa/alexa-avs-sample-app/blob/master/automated_install.sh` to use our Ubuntu libraries instead of Raspberry Pi libraries. You'll have to understand that installation script.

Finally, with a caveat, that our Ubuntu library doesn't come with a frontend audio processing module, so the performance will be worse for the default hotword Alexa. You can try to create a personal hotword on our website.

**Comment by ds3ctor** [comment]
Ok. I will give it a go, and update within the next day or so. Thanks!

**Comment by ds3ctor** [comment]
Hi guys, I'm not having any luck with this whatsoever. Is it possible to build a library for Ubtuntu 16.10 amd64? I would be more than happy to help test it, and report back.

**Comment by irthomasthomas** [comment]
I managed to get snowboy working on Ubuntu 14.04 but I haven't tried wiring it to Alexa yet. Did you get snowboy to build at all?

**Comment by chenguoguo** [comment]
Closing this since it's been there for a while and we are not getting responses. Please re-open if the issue has not been resolved, and you are still interested in finding out the solution.

**Comment by rickybrent** [comment]
I ran into the same issue -- I was able to get it working it with the information here (thank you!) and on this other ticket:
https://github.com/Kitt-AI/snowboy/issues/81

For Alexa, you'll also need to remove Sensory, as it does not check the OS variable and will keep trying to use a library for the arm architecture. (I made a fork I'll probably never update again here if anyone is interested: https://github.com/rickybrent/alexa-avs-sample-app)

**Comment by chenguoguo** [comment]
Awesome! Thanks a lot for the info @rickybrent!

**Comment by r0tekatze** [comment]
@rickybrent  Do you mean to say you got Kitt.AI wired into Alexa on Ubuntu? Would you mind sharing how? I built from your branch but I'm not really sure what to do from there, other than try the same method as for the Pi, which doesn't work.

**Comment by LinTechxyz** [comment]
I ran into the same issue when I used "make" to get the file "_snowboydetect.so"

../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/lib/python3.6/config-3.6m-aarch64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lm -ldl -lf77blas -lcblas -llapack -latlas -o _snowboydetect.so
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
../..//lib/ubuntu64/libsnowboy-detect.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:73: recipe for target '_snowboydetect.so' failed
make: *** [_snowboydetect.so] Error 1
 
How to solve this problem?
