### ISSUE TITLE
RPi "Invalid Sample Rate"

### ISSUE THREAD

**Issue by sciencedude100** [Kitt-AI/snowboy#8]
I am working on getting snowboy to invoke a python script to activate the listening on Amazon's [Alexa For Raspberry Pi](https://github.com/amzn/alexa-avs-raspberry-pi). I am stuck at this error: [Error Given](http://pastebin.com/tG8ASReN)

**Comment by xuchen** [comment]
Did you follow the RPi setup here:

https://snowboy.kitt.ai/docs/#running-on-raspberry-pi

It looks like an ALSA config problem. If you run `rec t.wav`, do you get an error?

**Comment by sciencedude100** [comment]
the recording went fine. when played back, I could hear everything I said. could it be the download source (from the site's tutorial)? I cloned the git repo and so far, so good

**Comment by sciencedude100** [comment]
Well! Just be sure to compile from the github source, not the package from the kitt.ai tutorial.

**Comment by xuchen** [comment]
Ah! The tutorial docs is a bit outdated: it points to an old download link:

https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.0.0.tar.bz2

But we've upgraded to 1.0.1:

https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/rpi-arm-raspbian-8.0-1.0.1.tar.bz2

So maybe that was the problem...
