### ISSUE TITLE
Missing SnowboyDetect and SetSensitivity in Ubuntu 64 library

### ISSUE THREAD

**Issue by BillWSY** [Kitt-AI/snowboy#81]
```
bazel-out/local-fastbuild/bin/codelab/snowboy/_objs/demo/codelab/snowboy/demo.pic.o: In function `main':
demo.cc:(.text+0x257): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
demo.cc:(.text+0x26d): undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Target //codelab/snowboy:demo failed to build
```

**Comment by chenguoguo** [comment]
I guess you are using g++ 5.x. You might want to add -D_GLIBCXX_USE_CXX11_ABI=0 to your CXXFLAGS. I pushed a fix to the `devel` branch for the c++ demo.

Let me know if it works.

**Comment by BillWSY** [comment]
I end up with adding ```#define _GLIBCXX_USE_CXX11_ABI 0``` in my cc. Thank you.

**Comment by vkoloss** [comment]
same applies to gcc 4.9. thanks!

**Comment by zane-01** [comment]
I am using the avs-device-sdk example from Github. Which file do I add the line #define _GLIBCXX_USE_CXX11_ABI 0 ?

**Comment by chenguoguo** [comment]
I'm not too familiar with CMake but most likely you will have to update the Kitt section of this file: https://github.com/alexa/avs-device-sdk/blob/master/build/cmake/KeywordDetector.cmake

You can probably get a quick answer from their repo as they are more familiar with their CMake structure.
