### ISSUE TITLE
Open source License

### ISSUE THREAD

**Issue by BillWSY** [Kitt-AI/snowboy#82]
Would you mind applying an open source license to ```snowboy/examples/C++/demo.cc``` and the rest of this repo? Otherwise, we will not be able to use it in our research project.

**Comment by chenguoguo** [comment]
You can cite our README page.

The demo.cc file itself is Apache licensed. The Snowboy library is provided subject to https://github.com/Kitt-AI/snowboy#pricing-for-snowboy-models
