### ISSUE TITLE
What's wroing with my makefile?  

### ISSUE THREAD

**Issue by Young910512** [Kitt-AI/snowboy#84]
[OpenBLAS-Android/install/lib/libopenblas.a] Error 127 (ignored)
arm-linux-androideabi-g++ -O3 --sysroot=/platforms/android-17/arch-arm -shared -std=c++0x -rdynamic -I../../ -Wl,--fix-cortex-a8 -Wl,--no-warn-mismatch -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wno-sign-compare -Wa,--noexecstack -Wformat -Werror=format-security -fno-rtti -ffunction-sections -funwind-tables -fstack-protector-strong -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -fno-strict-aliasing -mthumb -no-canonical-prefixes -march=armv7-a -mfpu=vfpv3-d16 -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -DANDROID -c snowboy-detect-swig.cc -o snowboy-detect-swig.o
snowboy-detect-swig.cc:159:17: fatal error: jni.h: No such file or directory
 #include <jni.h>

**Comment by chenguoguo** [comment]
You have to set `NDKROOT`

Also, please pay attention to this comment at the top of the file

```
# When you extract Android toolchain from Android NDK, make sure you supply
# --stl=libc++ option. This Makefile is optimized for armv7-a architecture.
```

**Comment by Young910512** [comment]
Thank you for your answer, but How I can user  --stl=libc++?

**Comment by Young910512** [comment]
Thank you for your answer, and how can I use --stl=libc++ option?

**Comment by chenguoguo** [comment]
See here:
https://developer.android.com/ndk/guides/standalone_toolchain.html

**Comment by briandbl** [comment]
Hi chengGuoGuo,

Now I got the following error when I compiled the snowboy on Android platform using swig


In file included from ../snowboy.cc:14:0:
../include/snowboy-detect.h:121:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   std::unique_ptr<WaveHeader> wave_header_;
        ^
../include/snowboy-detect.h:122:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   std::unique_ptr<PipelineDetect> detect_pipeline_;

Do you know the reason?    

thanks

**Comment by chenguoguo** [comment]
@briandbl could you show me the command how you extract the Android toolchain from Android NDK?

**Comment by briandbl** [comment]
I use the following the command to create the customized toolchains. 
I use the following command format. Is it ok?

./make-standalone-.py  --arch arm   --stl=libc++  --install-dir=./snowboy_toolchain

**Comment by chenguoguo** [comment]
Maybe try to set the platform as well? Here is my command

```
android-ndk-r11c/build/tools/make-standalone-toolchain.sh --platform=android-17 --install-dir=/home/vagrant/Tools/android-toolchain/arm --stl=libc++
```

Then you have to make sure you set the following correctly:

```
1. Make sure you set `NDKROOT`, which should point to the downloaded `android-ndk-r11c`

2. Make sure you set the binaries correctly, i.e., `arm-linux-androideabi-g++` and `arm-linux-androideabi-strip` in the Makefile should come from your installed toolchain
```

Let me know if this helps.

**Comment by briandbl** [comment]
I  follow your method. the following is my makefile and the error log. It can't find lc++_static library

================================================================================= 
Makefile 

# Please specify your NDK root directory here.
NDKROOT :=/home/brian/android-ndk-r11c
APILEVEL := 17

SNOWBOYDETECTSWIGITF = snowboy-detect-swig.i
SNOWBOYDETECTSWIGOBJ = snowboy-detect-swig.o
SNOWBOYDETECTSWIGCC = snowboy-detect-swig.cc
SNOWBOYDETECTJAVAPKG = ai.kitt.snowboy
SNOWBOYDETECTJAVAPKGDIR = java/ai/kitt/snowboy/
SNOWBOYDETECTSWIGLIBFILE = libsnowboy-detect-android.so
OPENBLASLIBFILE = OpenBLAS-Android/install/lib/libopenblas.a

ARCH := arm
TOPDIR := ../../
LDFLAGS :=

//CXXFLAGS := -O3 --sysroot=$(NDKROOT)/platforms/android-$(APILEVEL)/arch-$(ARCH)
CXXFLAGS := -O3 --sysroot=/home/brian/projects/snowboy_toolchain/arm/sysroot
//LDLIBS := -L$(NDKROOT)/platforms/android-$(APILEVEL)/arch-$(ARCH)/usr/lib
LDLIBS := -L/home/brian/projects/snowboy_toolchain/arm/sysroot/usr/lib        



===========================================================================
Make error LOG: 

/home/brian/projects/snowboy_toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++_static

**Comment by chenguoguo** [comment]
It still feels like your android ndk/toolchain was not set up correctly. Let's move one step back:

1. Set `CXXFLAGS := -O3 --sysroot=/home/brian/android-ndk-r11c/platforms/android-17/arch-arm`
2. Set `LDLIBS := -L/home/brian/android-ndk-r11c/platforms/android-17/arch-arm/usr/lib -L/home/brian/android-ndk-r11c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a-hard/thumb/ -lc++_static -lgcc -lm_hard -ldl -lc -lm`; make sure you have `libc++_static.a` and `libc++_shared.so` under `/home/brian/android-ndk-r11c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a-hard/thumb/`
3. Make sure `which arm-linux-androideabi-g++` gives you `/home/brian/projects/snowboy_toolchain/arm/bin/arm-linux-androideabi-g++` and `which arm-linux-androideabi-strip` gives you `/home/brian/projects/snowboy_toolchain/arm/bin/arm-linux-androideabi-strip`

**Comment by Young910512** [comment]
Thank you very much!  it helped me fix these problems
