### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'model_str'

### ISSUE THREAD

**Issue by Robert-SZ** [Kitt-AI/snowboy#85]
I'm trying to run example demo.py with snowboy.umdl and got next error:

~/Documents/snowboy/examples/Python$ python demo.py resources/snowboy.umdl 
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/parallels/Documents/snowboy/examples/Python/snowboydecoder.py", line 91, in __init__
    resource_filename=resource.encode(), model_str=model_str.encode())
TypeError: __init__() got an unexpected keyword argument 'model_str'

My OS is Ununtu Linux 14.04

**Comment by chenguoguo** [comment]
This two threads should help:

https://github.com/Kitt-AI/snowboy/issues/18
https://github.com/Kitt-AI/snowboy/issues/53

Let me know if they don't solve your issue.

**Comment by loukaskom** [comment]
Ok i have the same problem. 
loukas@loukas:~/snowboy-feature-saas/examples/Python$ python demo.py snowboy.umdl
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/loukas/snowboy-feature-saas/examples/Python/snowboydecoder.py", line 91, in __init__
    resource_filename=resource.encode(), model_str=model_str.encode())
TypeError: __init__() got an unexpected keyword argument 'model_str'


I have installed both swig2.0, swig3.0 and in my Makefile i have SWIG := swig3.0
I am running Debian8

**Comment by chenguoguo** [comment]
@loukaskom What if you use the pre-compiled version for Ubuntu 14.04? See here:

https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/ubuntu1404-x86_64-1.1.0.tar.bz2

The issue could be that we compiled the Snowboy library for Ubuntu, and you run the swig compilation on Debian. I haven't really tried that.
