### ISSUE TITLE
A64 support?

### ISSUE THREAD

**Issue by tomster** [Kitt-AI/snowboy#88]
I tried creating the swig bindings for python on a Pine64 board (running "Debian Base (3.10.102 BSP 2)" found here https://www.pine64.pro/getting-started-linux/) but I get the following error when running `make` inside `swig/Python`:

```debian@pine64:~/snowboy/swig/Python$ make
g++ -I/usr/include/python3.4m -I/usr/include/python3.4m  -Wno-unused-result -g -fstack-protector-strong -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x  -shared snowboy-detect-swig.o \
../..//lib/ubuntu64/libsnowboy-detect.a -L/usr/lib/python3.4/config-3.4m-aarch64-linux-gnu -L/usr/lib -lpython3.4m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lm -ldl -lf77blas -lcblas -llapack_atlas -latlas -o _snowboydetect.so
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../..//lib/ubuntu64/libsnowboy-detect.a(snowboy-detect.o): Relocations in generic ELF (EM: 62)
../..//lib/ubuntu64/libsnowboy-detect.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:50: recipe for target '_snowboydetect.so' failed
make: *** [_snowboydetect.so] Error 1
```

From my (limited) understanding there is simply no matching library in `lib` that match what swig expects on this platform (i tried hardcoding the `android/armv7a` folder in the Makefile but that also gave the same error as above).

Would it be possible for you to add the pine64 as a valid target?

**Comment by chenguoguo** [comment]
We don't have a pine64 by hand so we can't compile/test snowboy on pine64. The better chance is probably to use the rpi library instead of the ubuntu64 or android library, since rpi also uses ARM processors. Let me know if it works.

**Comment by tomster** [comment]
hi @chenguoguo i tried the rpi library, but it did not work. Is it possible to compile the library oneself? i would be glad to test and add the support to the project or is that part closed-source?

**Comment by chenguoguo** [comment]
@tomster we didn't not release the source code, and we do not have a plan to support Pine64 board at this point. So I'm afraid we are out of luck here :-(

**Comment by tomster** [comment]
@chenguoguo ok, thanks for clearing this up!

**Comment by Pine-A64** [comment]
@chenguoguo Hi I am TL Lim, PINE64 founder. If you still interest to receive PINE A64 board to compile/test snowboy, I am happy to provide one.

**Comment by chenguoguo** [comment]
@Pine-A64 hey good to see you here! Sure if we can compile/test Snowboy on Pine-A64, we can definitely provide a library for it!

**Comment by Pine-A64** [comment]
@Chen, Please provide your shipping address and I will ship out one Pine 
A64 1GB board to you. My email address is tllim@pine64.org

**Comment by r00kieone** [comment]
Good to read the issue has been re-opened, looking forward to use this on the pine64! :)

**Comment by chenguoguo** [comment]
I haven't got a chance to work on the Pine-A64 yet. Will keep this updated.

**Comment by xuchen** [comment]
@tomster @r00kieone what's your OS? should we first compile for Debian or Ubuntu or Arch?

**Comment by r00kieone** [comment]
I am using Debian Jessie for the pine64.

Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie

3.10.104-2-pine64-longsleep #113 SMP PREEMPT Thu Dec 15 21:46:07 CET 2016 aarch64 GNU/Linux

**Comment by xuchen** [comment]
@r00kieone where did you download the image? I tried the following one from https://www.pine64.pro/downloads/#Debian-Linux :

![image](https://cloud.githubusercontent.com/assets/543547/23182104/3aed55ac-f82c-11e6-8972-cfa486c4b85c.png)

But the download link does't work.

**Comment by xuchen** [comment]
never mind, got it from here: http://cdn.pine64.uk/Debian/

@Pine-A64 your website download link is invalid?

**Comment by xuchen** [comment]
@tomster @r00kieone model just updated at:

https://github.com/Kitt-AI/snowboy/tree/pine64/lib/pine64

Could you please give it a try to make sure it works? After that I'll merge the PR.

**Comment by r00kieone** [comment]
Thank you for responding very quickly about this! I tried it as part of building Alexa echo for pine64 (using Rasberry Pi instructions), but I didn't get it working yet, but the main cause is that I am not very experienced building programs from sources | - ) Perhaps I should try building this separately, but I need to have another look at it.

**Comment by xuchen** [comment]
@r00kieone yes please build this separately, it should be much much easier.

**Comment by r00kieone** [comment]
I've some dependency problems, e.g.:
 python3-pyaudio : Depends: python3 (< 3.5) but 3.5.1-4 is to be installed

perhaps there's another pine64-user who can try this? I am not that experienced, sorry | -)

**Comment by xuchen** [comment]
@r00kieone if you are using Python 2.7 then you don't have to install `python3-pyaudio`. Give it a try?

**Comment by sepulker** [comment]
I've build it for nodejs running Armbian_5.26_S9xxx_Debian_jessie_3.14.29_server_20170302.img
on Amlogic S905X TVBOX. Nodejs Examples work!
The Build did not work out of the Box - I had to modify binding.gpy to match processor arch:

            ['OS=="linux" and target_arch=="arm64"', {
                'link_settings': {
                    'ldflags': [
                        '-Wl,--no-as-needed',
                    ],
                    'libraries': [
                        '<(module_root_dir)/lib/pine64/libsnowboy-detect.a',
                    ]
                }
            }]

Thank You for releasing ARM64 binary !
I have tried the python example but it fails because of Soundcard setup - I've tried simple
sound examples and can't get them to work
In the next days I will try to build for other languages and enchance the nodejs Examples :)

**Comment by chenguoguo** [comment]
@sepulker You are right, we didn't update that corner case! Would you like to submit a pull request for it?

**Comment by sepulker** [comment]
Im just a  git newbie I haven't read the Docs yet - I will be back ...

**Comment by chenguoguo** [comment]
I have added A64 support, so closing this.

**Comment by chenguoguo** [comment]
See here:
https://github.com/Kitt-AI/snowboy/blob/master/swig/Go/snowboy.go

It is not linking the Pine64 library I believe. If you could fix it and make it more general, feel free to send a PR!
