### ISSUE TITLE
Start shell script when hotword is detected

### ISSUE THREAD

**Issue by hardstylos** [Kitt-AI/snowboy#91]
I have everything up and running. I want to start a shell script when a hotword is detected. I have the following python "code" (which I can start using python test.py):

import os
import sys

os.system("sh ./test.sh")

How can I integrate this so it starts when I use my personal hotword?

**Comment by chenguoguo** [comment]
Answering it on the forum: https://groups.google.com/a/kitt.ai/forum/#!topic/snowboy-discussion/QEZjaVYaxOQ
