### ISSUE TITLE
Error in demo.py on Raspberry Pi

### ISSUE THREAD

**Issue by andrew-veresov** [Kitt-AI/snowboy#94]
Hi! 

I get an error when I run following command on RPi:

```ash
python demo.py eve.pmdl
```

Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import snowboydecoder
  File "/home/pirate/rpi-arm-raspbian-8.0-1.1.0/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pirate/rpi-arm-raspbian-8.0-1.1.0/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pirate/rpi-arm-raspbian-8.0-1.1.0/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

How can fix the issue?

**Comment by evancohen** [comment]
Chances are you are missing a dependency
``` bash
sudo apt-get install libatlas-base-dev
```
Give that a shot and then run it again.

**Comment by andrew-veresov** [comment]
Thank you that helped!

also I installed (don't know do I needed it really)
```bash
sudo apt-get install alsa-tools alsa-utils
```
and added my user to the audio group:
```bash
sudo usermod -a -G audio <user>
```

**Comment by mbissaro** [comment]
It is not working for me. After try to install libatlas-base-dev I got:

```
$ sudo apt-get install libatlas-base-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libatlas-base-dev : Depends: libatlas-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I tried this libatlas-dev, that asked for another and another. Finally, I got:

```
$ sudo apt-get install libblas-dev libatlas-dev libatlas-base-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libblas-dev : Depends: libblas3 (= 1.2.20110419-5) but 1.2.20110419-10 is to be installed
E: Unable to correct problems, you have held broken packages.
```

And I can't proceed. Can't install this libblas3 anymore:

```
$ sudo apt-get install libblas3 libblas-dev libatlas-dev libatlas-base-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libblas3 is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libblas-dev : Depends: libblas3 (= 1.2.20110419-5) but 1.2.20110419-10 is to be installed
E: Unable to correct problems, you have held broken packages.
```

That is my sources.list:
```

$ sudo cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi
```


And my system version:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
```

Any help is welcome here :)

Thanks in advance.

**Comment by chenguoguo** [comment]
It doesn't look like a Snowboy problem. Perhaps you messed your OS up? You
could try to update the software source and perform the installation  again.

Guoguo

**Comment by hack-r** [comment]
It made my initial error go away but the next error was 

> 
ImportError: dynamic module does not define module export function (PyInit__snowboydetect)

**Comment by chenguoguo** [comment]
Did you `make` under `swig/Python` or `swig/Python3`?

**Comment by chenguoguo** [comment]
Could you post the repository fork? Thanks a lot. @hack-r

**Comment by hack-r** [comment]
@chenguoguo sure I was referring to https://github.com/shivasiddharth/GassistPi/

**Comment by GenteelDevil** [comment]
Try:
sudo aptitude install libatlas-base-dev
Instead of:
sudo apt-get install libatlas-base-dev
which might cause the probelm of independence
