### ISSUE TITLE
Implement with node

### ISSUE THREAD

**Issue by sunsgs** [Kitt-AI/snowboy#95]
Hi there, i would like to run a file with node always listening and do something when you say the wake up word. Is that possible ?

**Comment by MexXxo** [comment]
yes

**Comment by sunsgs** [comment]
any guide?

**Comment by chenguoguo** [comment]
@sunsgs you can follow the README and use the example here: https://github.com/Kitt-AI/snowboy/blob/master/examples/Node/microphone.js

One caveat: https://github.com/Kitt-AI/snowboy/issues/87

**Comment by evancohen** [comment]
@sunsgs you might also want to check out [Sonus](https://github.com/evancohen/sonus).

**Comment by MexXxo** [comment]
@sunsgs probably Sonus will be the right choice, as it covers a lot of things.

**Comment by sunsgs** [comment]
@MexXxo is sonus able to answer my voice questions?
